### ISSUE TITLE
selectedFlatRows is an empty array after filtering 

### ISSUE THREAD

**Issue by JANA-afung** [TanStack/react-table#2210]
**Describe the bug (required)**
selectedFlatRows becomes empty when filtering selected values yet, selectedRowId are still showing previously selected values 

**Provide an example via Codesandbox! (required)**
[react-table codesandbox](https://codesandbox.io/s/distracted-meadow-97d7m?file=/src/App.js:6935-6951)

**Steps To Reproduce (required)**
1. Select first two options 
2. Filter on FirstName something other than the two options selected
3. Check results in the "filter" section of  json.stringify() 

**Expected behavior (Recommended)**
selectedRows should have an array of objects that matches what has been selected in selectedRowIds

**Screenshots**

![image](https://user-images.githubusercontent.com/51654520/80022471-1af82c00-84aa-11ea-83ce-cfb07570c22f.png)

selectedRowIds says I selected two rows but selectedRows is empty

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome
- Version:  80.0.3987.163

**Comment by Nuuou** [comment]
Ran into this exact same issue, and it's definitely becoming a problem on my current project.
I'd like to not have to implement a custom "selected" solution, but may have to do so.

Discussion I started last week with some of my info too, seems to match what you're running into:
https://github.com/tannerlinsley/react-table/discussions/2208

At minimum, I'd like to `selectedFlatRows` and `selectedRowIds` to be consistent, so I'm curious which of those two is currently representative of the expected functionality. Hoping `selectedFlatRows` could behave like `selectedRowIds`!

**Comment by Nuuou** [comment]
Related: using methods to clear selected rows (such as `toggleAllRowsSelected`) only deselects  items matching the current filter, which feels odd as well.

**Comment by JANA-afung** [comment]
@Nuuou The hotfix I came up with was to use selectedRowIds to filter through the data props you provide your table ... hope it helps let me know if you need an example..

**Comment by Nuuou** [comment]
That definitely helps, and is what I'll probably be doing too! Unfortunately my other task is to _deselect_ all too, which seems to be bugged as well (only deselects things within the current filter).

Related: Seems like there's a current branch and PR for some work that would effect the underlying work of selection being done here. https://github.com/tannerlinsley/react-table/pull/2166

**Comment by JANA-afung** [comment]
havent tested this myself but iterating through selectedRowIds and setting them to false might do the trick to deselect all...  
 ¯\_(ツ)_/¯

**Comment by Ediste** [comment]
The workaround to set the elements to false works but you have to trigger a refresh of the view to see the changes. For the refresh I simply call toggleAllRowsSelected(false). Not nice but works. I hope there will be a general fix. For example an additional optional parameter for toggleAllRowsSelected and a correct selectedFlatRows object.

Workaround:
```    
const deselectAllRows = useCallback(() => {
      // Workaround to deselect non filtered rows -> toggleAllRowsSelected only works with current filtered rows
      Object.keys(selectedRowIds).forEach((key, index) => {
        selectedRowIds[key] = false
      })
      toggleAllRowsSelected(false) // needed to trigger an update
    }, [selectedRowIds, toggleAllRowsSelected])
```

**Comment by Buuntu** [comment]
> The workaround to set the elements to false works but you have to trigger a refresh of the view to see the changes. For the refresh I simply call toggleAllRowsSelected(false). Not nice but works. I hope there will be a general fix. For example an additional optional parameter for toggleAllRowsSelected and a correct selectedFlatRows object.
> 
> ```
> const deselectAllRows = useCallback(() => {
>       // Workaround to deselect non filtered rows -> toggleAllRowsSelected only works with current filtered rows
>       Object.keys(selectedRowIds).forEach((key, index) => {
>         selectedRowIds[key] = false
>       })
>       toggleAllRowsSelected(false) // needed to trigger an update
>     }, [selectedRowIds, toggleAllRowsSelected])
> ```

Is there a workaround for calling toggleRowSelected on hidden rows, since you can't use selectedFlatRows?  When I set selectedFlatIds[id] = false it doesn't trigger a re-render.

**Comment by nicuvlad7** [comment]
Hello, so I'm new to ReactJS and I just encounted this problem myself, maybe I'm mistaken but could this be solved by moving selectedFlatRows inside the table global state  (parent or what ever the highest level of state is) ?

As I see it now, we are getting the selectedFlatRows (this seems to be set once all the the filters have been applied): 
_flatRows: Array<Row>
An array of all rows, including subRows which have been flattened into the order in which they were detected (depth first)_ 
 from useTable -> useRowSelect.

So basically from what I understand selectedFlatRows has a state that is going to reset every time the data inside the table changes, basically every time I filter something the data that is fed into the table changes. No matter if I use the same filter again and again then go back and start it all over.

but for some reason the selectedRowIds are somehow global, and they don't RESET with the data they just change which should be the case for the selectedFlatRows as well.

I don't know if this makes any sense but hopefully some one can get a better idea.

**Comment by StayInLight** [comment]
> > The workaround to set the elements to false works but you have to trigger a refresh of the view to see the changes. For the refresh I simply call toggleAllRowsSelected(false). Not nice but works. I hope there will be a general fix. For example an additional optional parameter for toggleAllRowsSelected and a correct selectedFlatRows object.
> > ```
> > const deselectAllRows = useCallback(() => {
> >       // Workaround to deselect non filtered rows -> toggleAllRowsSelected only works with current filtered rows
> >       Object.keys(selectedRowIds).forEach((key, index) => {
> >         selectedRowIds[key] = false
> >       })
> >       toggleAllRowsSelected(false) // needed to trigger an update
> >     }, [selectedRowIds, toggleAllRowsSelected])
> > ```
> 
> Is there a workaround for calling toggleRowSelected on hidden rows, since you can't use selectedFlatRows? When I set `selectedRowIds[id] = false` it doesn't trigger a re-render so I still have to call toggleRowSelected, but those arrays are not in sync.

Did you find any solution for this problem?

**Comment by am242** [comment]
Did someone found a solution to this issue? 

In my app, when I filter the items, the selectedFlatRows is empty because the selected items are not in the filter.

Thanks.

**Comment by yanivfranco** [comment]
Hey, just encountered this issue as well. This seems like a bug. 
Both arrays should be consistent regardless of the filters.

Maybe we should have a flag on the table options which control the selected state: ignoreFilterOnSelection
when true: selectedFlatRows  & SelectedRowIds will contain all selected row even if they do no show in the current filter
when false: selectedFlatRows  & SelectedRowIds will contain only the selected rows which are shown in the current filter (meaning they will update on each filter change and may lose rows on narrowing filters)

**Comment by yanivfranco** [comment]
by they way, found a workaround for getting the actual selectedflatRows (synced with SelectedRowIds)
https://spectrum.chat/react-table/general/v7-how-get-selected-rows-outside-of-react-table~2deb9558-c484-4b97-9e1c-6be608f1f275?m=MTU3ODkxODEwNTE3NQ==

**Comment by tannerlinsley** [comment]
This is fixed in v8 but unfortunately I don't have immediate plans to fix this in v7 without introducing breaking changes.

**Comment by GodAlmighty990** [comment]
I solved this problem using redux. I would guess you are using redux anyways since your using a react project?

I created a selectedRow reducer.

`import { UPDATE_SELECTED_ROWS } from '../actions/types';


export default function (state = [], action) {
    switch (action.type) {
       case UPDATE_SELECTED_ROWS: 
       console.log("update_selected_rows state", state)
       if(!state.length) { // this will always be triggered on first click if selection is empty
        return action.payload.selectedFlatRows.map((el) => { return {id: el.id, original_id: el.original._id}}) // return <--- object
       } else {
       const matched = Object.keys(action.payload.selectedRowIds).map((selRow) => {  // map over incoming selectedRowIds
            const foundRow = state.filter((el) => { return el.id === selRow})[0] // if state has an object with matching ID return it
                if(foundRow) {
                    console.log("found row", foundRow)
                return foundRow //< ---- returning our object
                } else {
                    console.log("update_selected_rows payload", action.payload)
                    const newRow = action.payload.selectedFlatRows.filter((el) => { return el.id === selRow})[0]
                    console.log("new row =====> ", newRow)
                return {id: newRow.id, original_id: newRow.original._id} //< --- otherwise return this new object 
                }
        })
        return matched <--- this will be an array with current selected objects
        }

            default:
            return state;
    }
}


Now that this reducer is created, in my react component using the table I have a selectionCallback that is passed to the table wrapper, (just find where you pass your selectionCallback if you dont use a table wrapper)


`

const [isSelected, setIsSelected] = useState(false);



const selectionCallback = useCallback((selectedFlatRows) => { 
    return setIsSelected(selectedFlatRows.map((fr) => {return fr.original._id})), setSelectedRows(selectedFlatRows) },
  [setIsSelected]);


  <Fragment>
                <Card>
                <AdvanceTableWrapper
                  columns={columns}
                  data={contacts} 
                  sortable
                  pagination
                  perPage={10}
                  selection
                  selectionColumnWidth={25}
                  selectionCallback={selectionCallback}
                  
                >
                  <Row className="flex-start-center mb-3 ml-1">
                    <Col >
                      <AdvanceTableSearchBox table/>
                    </Col>
                  </Row>
                 
                  <AdvanceTable
                    table
                    headerClassName="bg-200 text-900 font-weight-bold text-nowrap align-middle"
                    rowClassName="btn-reveal-trigger border-top border-200 align-middle white-space-nowrap"
                    tableProps={{
                      striped: true,
                      className: 'fs--1 font-weight-bold overflow-hidden'
                    }}
                  />
                  <div className="mt-3 mb-2 pr-2 pl-3 ">
                    <AdvanceTableFooter
                      rowCount={contacts?.length}
                      table
                      rowInfo
                      navButtons
                      rowsPerPageSelection
                    />
                  </div>
                </AdvanceTableWrapper>
                
                </Card>
                </Fragment>




Now In my tableWrapper take a look at my useEffects, 




`import React, { useEffect, useCallback } from 'react';
import { Form } from 'react-bootstrap';
import {
  useTable,
  useSortBy,
  usePagination,
  useRowSelect,
  useGlobalFilter,
} from 'react-table';
import { useSticky } from 'react-table-sticky'
import { useDispatch, useSelector } from 'react-redux';
import { UPDATE_SELECTED_ROWS } from '../../actions/types';

const IndeterminateCheckbox = React.forwardRef(
  ({ indeterminate, ...rest }, ref) => {
    const defaultRef = React.useRef();

    const resolvedRef = ref || defaultRef;

    React.useEffect(() => {
      
      resolvedRef.current.indeterminate = indeterminate;
    }, [resolvedRef, indeterminate]);

    return (
      
      <Form.Check
        type="checkbox"
        className="form-check fs-1 mb-0 d-flex align-items-center p-3 pb-1 "
        
       // its registering form-check, just not registering the form-check variable for opacity and other styles?
      >
        <Form.Check.Input type="checkbox" className="w-50 h-50" ref={resolvedRef} {...rest} />
      </Form.Check>
     
    );
  }
);

const AdvanceTableWrapper = ({
  children,
  columns,
  data,
  sortable,
  selection,
  selectionColumnWidth,
  selectionCallback,
  pagination,
  perPage = 10
}) => {

  const {
    getTableProps,
    headers,
    page,
    prepareRow,
    selectedFlatRows,
    flatRows,
    canPreviousPage,
    canNextPage,
    nextPage,
    previousPage,
    setPageSize,
    gotoPage,
    pageCount,
    state: { pageIndex, pageSize, selectedRowIds, globalFilter },
    setGlobalFilter
  } = useTable(
    {
      columns,
      data,
      disableSortBy: !sortable,
      initialState: { pageSize: pagination ? perPage : data.length }
    },
    useGlobalFilter,
    useSortBy,
    usePagination,
    useRowSelect,
    useSticky,
    hooks => {
      if (selection) {
        
        hooks.visibleColumns.push(columns => [
          {
            id: 'selection',
            Header: ({ getToggleAllRowsSelectedProps }) => (
              <IndeterminateCheckbox {...getToggleAllRowsSelectedProps()} />
            ),
            headerProps: {
              style: {
                maxWidth: selectionColumnWidth,
                
              }
            },
            cellProps: {
              style: {
                maxWidth: selectionColumnWidth
              }
            },
            Cell: ({ row }) => (
              <div>
                {
                 <div>

                <IndeterminateCheckbox {...row.getToggleRowSelectedProps()} />
                  </div>
                }
              </div>
            )
          },
          
          ...columns
        ]);
      }
    }
  );

// Here -------------------------------LOGIC for setting redux with filtered rowIds
  const dispatch = useDispatch()
  const reduxSelectedRows = useSelector((state) => state.selectedRows)


  useEffect(() => {
    dispatch({type: UPDATE_SELECTED_ROWS, payload: {selectedRowIds: selectedRowIds, selectedFlatRows: selectedFlatRows}})
  }, [selectedRowIds]) <----- trigger the dispatch to redux everytime selectedRowIds changes


    useEffect(() => {
      selectionCallback(selectedFlatRows)
      console.log("selectedRowsReducer", reduxSelectedRows)
      console.log("flatRows ========> ", selectedFlatRows)
      console.log("selectedRowIds ======> ", selectedRowIds)
    }, [reduxSelectedRows]) // < ------ trigger this only when redux state changes, this keeps us from being one step behind
now you should be able to have access to this state via your reducer, just make to add some logic when you leave the page to reset this to zero

  const recursiveMap = children => {
    return React.Children.map(children, child => {
      if (child.props?.children) {
        return React.cloneElement(child, {
          children: recursiveMap(child.props.children)
        });
      } else {
        if (child.props?.table) {
          return React.cloneElement(child, {
            ...child.props,
            getTableProps,
            headers,
            page,
            data,
            prepareRow,
            canPreviousPage,
            canNextPage,
            nextPage,
            previousPage,
            gotoPage,
            pageCount,
            pageIndex,
            selectedRowIds,
            selectedFlatRows,
            pageSize,
            setPageSize,
            globalFilter,
            setGlobalFilter
          });
        } else {
          return child;
        }
      }
    });
  };

  return (
    <>{recursiveMap(children)}</>
  );
};

export default AdvanceTableWrapper;
