### ISSUE TITLE
selectedRowIds doesn't return pre-selected rows with isSelected key in row data

### ISSUE THREAD

**Issue by ravisojitra** [TanStack/react-table#2776]
**Describe the bug (required)**
I have a requirement where let's say i have selected 2 rows in page 1 and then i navigate to page 2. And now if i again navigate to page 1, those 2 rows should be autoselected. So I'm managing that via isSelected key in row data. But it seems selectedRowIds and selectedFlatRows returns empty array which should not be the case. It should return rows with isSelected set to true.

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/competent-mclaren-f1rfo

**Steps To Reproduce (required)**

1. Go to makeData.js file and change condition according to your need for isSelected prop.
2. It should reflect when page reloads that rows are selected but selectedRowIds returns empty object

**Expected behavior (Recommended)**
It should return all the selected rows both preselected and manually selected. 

**Screenshots**
![Screenshot from 2020-10-15 12-18-25](https://user-images.githubusercontent.com/9591571/96086941-b1992900-0ee0-11eb-83ef-4546966c7571.png)

**Desktop (please complete the following information):**

- OS: ubuntu
- Browser chrome
- Version 84.0.4147.125

**Additional context**
Also, If you check in that codesandbox, preselected rows can't be unselected.

**Comment by felipefrodrigues** [comment]
hey bro, i solved it with that example https://github.com/tannerlinsley/react-table/discussions/2661

**Comment by goesbysteve** [comment]
> hey bro, i solved it with that example #2661

How does that example solve this issue please?

**Comment by goesbysteve** [comment]
@ravisojitra did you find any solution to this?

**Comment by ruge0326** [comment]
I have the same issue.

**Comment by goesbysteve** [comment]
> I have the same issue.

If I find a solution, I'll post back here

**Comment by maitzeth** [comment]
This is not the solution to this issue. 

This is what I do instead: 

Idk if this helps anyone

![image](https://user-images.githubusercontent.com/8760358/138377072-249805c5-781d-4f49-9ba5-ac88eb6bafe8.png)

**Comment by palmer-cl** [comment]
having the same issue. Im using `isSelected: true` yet selectedRowIds is still empty. Its more apparent when you click on the pre-selected row to deslect it, and it gets added to the selectedFlatRows.

**Comment by tannerlinsley** [comment]
This issue is either:
- Outdated
- Stale
- Fixed in v8
- Unable to be fixed in v7 without breaking changes and is slated for v8

If you feel this is incorrect, please reopen a new issue with a codesandbox reproduction or more info regarding the issue.

**Comment by sulphitic786** [comment]
Kindly let me now how to pass it for downloading the selected rows in csv file. Thanks
