### ISSUE TITLE
resetResizing doesn't work with setColumnOrder([]);

### ISSUE THREAD

**Issue by ViieeS** [TanStack/react-table#2811]
**Repro**
```ts
const resetColumnSettings = useCallback(() => {
    toggleHideAllColumns(false);
    setColumnOrder([]);
    resetResizing();
  }, [resetResizing, setColumnOrder, toggleHideAllColumns]);
```

**Bug**
Resizing Settings doesn't reset.

**Work around**
```ts
resetResizing();
toggleHideAllColumns(false);
setTimeout(() => {
    setColumnOrder([]);
});
```

**Comment by OmarAl-Ayoubi** [comment]
I have the same problem

**Comment by ParseDark** [comment]
Have the Same Problem. But I use may plugin-hook. I think maybe it's the reason.
```ts
  const tableObj: any = useTable(
    {
      columns,
      data,
      defaultColumn, // Be sure to pass the defaultColumn option
      filterTypes,
      initialState: { pageIndex: 2 },
    } as any,
    useResizeColumns,
    useFilters, // useFilters!
    useGlobalFilter, // useGlobalFilter!
    useSortBy,
    usePagination,
    useBlockLayout
  );
```

**Comment by ParseDark** [comment]
> ```ts
> tableObj
> ```

and tableObj.resetResizing is undefined I don't know why

**Comment by ParseDark** [comment]
Solve. Just need to update the version to 7.6.x.

**Comment by EugenyPenepok** [comment]
same problem
sandbox
https://codesandbox.io/s/cool-fermi-iykn3

**Comment by akraines** [comment]
It looks as if the defaultsize is recalculated every time the column order changes, so it resets to the new default - that is my guess based on the fact the setTimeout fix doesnt work for me when I resize the columns before reordering them and then triggering resetColumnSizing
