### ISSUE TITLE
TypeError: plugin is not a function when calling useTable

### ISSUE THREAD

**Issue by man-shar** [TanStack/react-table#2825]
Getting this error when running `useTable` which I'm unsure how to reproduce because I'm a noob. Sorry! I'm just using React + TS and trying to run useTable with it. Let me know how I can repro?

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/12295494/97799811-1e474e00-1c6b-11eb-8991-c19db04b03d4.png">

These are my dependencies in my package.json:
- "@material-ui/core": "^4.11.0",
- "@testing-library/jest-dom": "^4.2.4",
- "@testing-library/react": "^9.3.2",
- "@testing-library/user-event": "^7.1.2",
- "@types/jest": "^24.0.0",
- "@types/mapbox-gl": "^1.12.5",
- "@types/node": "^12.0.0",
- "@types/react": "^16.9.0",
- "@types/react-dom": "^16.9.0",
- "@types/react-table": "^7.0.25",
- "@types/react-tabs": "^2.3.2",
- "d3-array": "^2.8.0",
- "mapbox-gl": "^1.12.0",
- "node-sass": "^4.14.1",
- "react": "^16.14.0",
- "react-dom": "^16.14.0",
- "react-scripts": "3.4.3",
- "react-table": "^7.0.0-beta.20",
- "react-tabs": "^3.1.1",
- "typescript": "~3.7.2"

Thanks!!!

**Comment by Hadard753** [comment]
+1

**Comment by nstadelmaier-dev** [comment]
My guess is that you are passing the plugins wrong. Plugins should follow after the options object.
` useTable({options}, plugin1, plugin2, ...)`  
E.g. ` useTable({columns, data}, useSortBy, ...)`

Maybe you have wrapped the plugins in an object by accident or put them into the options?
