### ISSUE TITLE
Resize behavior has downgraded

### ISSUE THREAD

**Issue by yossiHav** [TanStack/react-table#2830]
using the react-table 7.01 (this the version I have used before the latest 7.6.1)

when resizing a column and moving the resizer horizontally on the header I can't resize the column to it minimum, it return always to the size the table loaded with. 

this is the config of the column I'm using
export const columns = (getLocalizationString) =>
  React.useMemo(() => [
    {
      accessor: "id",
      Header: "id",
    },
    {
      accessor: "name",
      Header: getLocalizationString("name"),
      width: 200,
    },
    {
      accessor: "usernamePresentation",
      Header: getLocalizationString("username"),
      width: 200,
    },
    {
      accessor: "credentialTypePresentation",
      Header: getLocalizationString("credentialType"),
      width: 200,
    },
    {
      id: "useProtocol",
      Header: getLocalizationString("protocol"),
      maxWidth: 60,
      disableResizing: true,
      accessor: (originalRow) => {
        return <div>{TrueFalseCellMark(originalRow.useProtocol)}</div>;
      },
      getCellExportValue: (row, column) => {
        return row.original.useProtocol;
      },
    },
    {
      id: "useSudo",
      Header: getLocalizationString("configuration.sudo"),
      maxWidth: 60,
      disableResizing: true,
      accessor: (originalRow) => TrueFalseCellMark(originalRow.useSudo),
      getCellExportValue: (row, column) => {
        return row.original.useSudo;
      },
    },
    {
      id: "useProxy",
      Header: getLocalizationString("configuration.proxy"),
      width: 60,
      disableResizing: true,
      accessor: (originalRow) => TrueFalseCellMark(originalRow.useProxy),
      getCellExportValue: (row, column) => {
        return row.original.useProxy;
      },
    },
    {
      id: "useAgent",
      Header: getLocalizationString("agent"),
      maxWidth: 60,
      disableResizing: true,
      accessor: (originalRow) => TrueFalseCellMark(originalRow.useAgent),
      getCellExportValue: (row, column) => {
        return row.original.useAgent;
      },
    },
  ]);

this behavior is tested on 
1. chrome - Version 86.0.4240.111 (Official Build) (64-bit)
2 firefox- 81.0.2 (64-bit)
3. Webpack 5.x
4. react 16.14.x

**Comment by OmarOmeiri** [comment]
Please format the code properly. Have you tried this?

```
  const autoResetResize = useRef(true);
  const tableDefaultColumn = {
    width: 0,
    minWidth: 50,
    maxWidth: 400,
  };

  const table = useTable(
    {
      columns,
      data: data,
      defaultColumn: tableDefaultColumn,
      SubComponent,
      initialState: {
        pageIndex: 0,
        pageSize: defaultPageSize,
        sortBy: initSortState,
      },
      autoResetResize: autoResetResize.current, // <- HERE
    })
```

You should set the `autoResetResize` to `false` If you want the column widths to persist. I like to start it with it set to `true` because I fetch the columns from a server and the columns start as an empty array. I set it to false only after the columns are ready to be used.

**Comment by yossiHav** [comment]
This issue has been fixed in the last version thanks
