### ISSUE TITLE
UseEffect with React-Table not displaying changes unless the page is refreshed

### ISSUE THREAD

**Issue by francislainy** [TanStack/react-table#2832]
**Describe the bug**
I have this issue where I updated a table to use react-table and now, whenever I either add or delete an item from my api response, I need to refresh the whole page to see the changes take place, whereas before I had my useEffect showing these changes immediately. It seems it won't let you change your data value. (Further details can be found [here](https://stackoverflow.com/questions/64629087/useeffect-with-react-table-not-displaying-changes-unless-the-page-is-refreshed)

**Provide an example via Codesandbox! (required)**
Use a new [react-table codesandbox](https://codesandbox.io/s/confident-drake-e47wm?file=/src/MainTable.js) to reproduce the issue.

**Steps To Reproduce**

Toggle lines 9 and 10 on the Codebox sample and click the Add random button to see the issue happening.

**Expected behavior**
React-table accepting data from props.

**Desktop**

- OS: [Mac]
- Browser [chrome, safari]

Thank you.

**Comment by Dema** [comment]
Why do you think it should work if you uncomment those lines? You are storing the **initial** data in useState (when you first rendered this table) and then you never update it. It works as intended.
