### ISSUE TITLE
Cannot read property 'isGrouped' of undefined 

### ISSUE THREAD

**Issue by kareshi** [TanStack/react-table#2833]
**Describe the bug (required)**

I am using all those hooks in react-table :
- useRowSelect
- useExpanded 
- useRowSelect 

After I group by a column and select a row, the below error will occur :

TypeError
Cannot read property 'isGrouped' of undefined
handleRowById
https://2u2zj.csb.app/node_modules/react-table/dist/react-table.development.js:3571:18
eval
https://2u2zj.csb.app/node_modules/react-table/dist/react-table.development.js:3581:20
handleRowById
https://2u2zj.csb.app/node_modules/react-table/dist/react-table.development.js:3580:34
eval
https://2u2zj.csb.app/node_modules/react-table/dist/react-table.development.js:3581:20
handleRowById
https://2u2zj.csb.app/node_modules/react-table/dist/react-table.development.js:3580:34
reducer$8
https://2u2zj.csb.app/node_modules/react-table/dist/react-table.development.js:3586:7
eval
https://2u2zj.csb.app/node_modules/react-table/dist/react-table.development.js:1055:16
eval
https://2u2zj.csb.app/node_modules/react-table/dist/react-table.development.js:1054:126
updateReducer
https://2u2zj.csb.app/node_modules/react-dom/cjs/react-dom.development.js:10083:26
Object.useReducer
https://2u2zj.csb.app/node_modules/react-dom/cjs/react-dom.development.js:10723:20
Object.useReducer
https://2u2zj.csb.app/node_modules/react/cjs/react.development.js:918:25
useTable
https://2u2zj.csb.app/node_modules/react-table/dist/react-table.development.js:1059:35
Table
/src/App.js:85:4
  82 |   selectedFlatRows,
  83 |   state: { pageIndex, pageSize, selectedRowIds }
  84 | } = useTable(
> 85 |   {
     |  ^
  86 |     columns,
  87 |     data
  88 |   },

Codesandbox :
https://codesandbox.io/s/react-table-userowselect-useexpanded-userowselect-issue-2u2zj

**Steps To Reproduce (required)**

1. Go to https://codesandbox.io/s/react-table-userowselect-useexpanded-userowselect-issue-2u2zj
2. Click on column "First Name"
3. Select first row by clicking on the check box at the beginning of the line

**Expected behavior (Recommended)**
No error is happening.

A first guess analysis is that subRows has been set manually with makeData. 
When grouping the data, the ids has not been generated for those rows.

**Screenshots**

<img width="850" alt="Screenshot 2020-11-03 at 17 59 09" src="https://user-images.githubusercontent.com/1390378/98023192-79f61080-1dfe-11eb-9704-9e070c434120.png">

**Desktop (please complete the following information):**

- OS: iOs but reproduced to on Windows 10 
- Browser Chrome and Safari

**Additional context**

**Comment by kareshi** [comment]
I had another bit of analysis today.

The ids are generated correctly.
However the rowByIds is not populated with underlying elements.

As per screenshot. Row with id 0.0 is at depth 1 of Row with id 0 as expected.
However rowByIds does not contains the reference to row with id 0.0.

<img width="2228" alt="Screenshot 2020-11-04 at 11 19 11" src="https://user-images.githubusercontent.com/1390378/98105742-45329980-1e90-11eb-8b7f-3e886d953ce7.png">

**Comment by kareshi** [comment]
Hello @tannerlinsley,

I was going more on debugging.
I might be wrong but there is something that I find confusing.

When the table is initially build (ie with no groupingBy yet), the rowsById is containing rows from all levels.
When a groupBy is activated, the rowsById will only contain the top level rows.

Attached the screenshot of the debugger when the grouping is done :
- rowsById is representing the state just before grouping where all rows from all level are present.
- groupedRowById is the state that would override the rowsById after the reducer is completed. It only contains top level nodes.

Is this is expecting behaviour ? It seems that other hooks are looking up in rowsById as the full list of rows, not only the top levels.

<img width="1940" alt="Screenshot 2020-11-04 at 16 44 31" src="https://user-images.githubusercontent.com/1390378/98140755-b5a3df80-1ebd-11eb-96cb-cb5ec2723725.png">

**Comment by yuri-scarbaci-lenio** [comment]
I'm affected by this too, Had no time to debug everything yet, but ID are correctly set in my data too.

Any news?

**Comment by simcha90** [comment]
hi, any updates here?

**Comment by jschen2** [comment]
This [PR](https://github.com/TanStack/react-table/pull/3422) should fix this

**Comment by tannerlinsley** [comment]
Merged!

**Comment by simcha90** [comment]
@tannerlinsley @jschen2 thanks, what version of npm react-table I need to install to get this fix? I see latest version looks on v8, but we still use v7

**Comment by tannerlinsley** [comment]
Still working on a release
