### ISSUE TITLE
Page number resets to zero after changing a cell value

### ISSUE THREAD

**Issue by laazaz** [TanStack/react-table#2861]
I'm using editable and row selection at the same time, when I change a cell value on the second page of the table, it goes back to page 1, this problem doesn't occur when I remove the parent component's "setSelectedRows" which is a useState's value changer to know (on the parent's component) what's selected.

Codesandbox:
https://codesandbox.io/s/nice-dew-17y4d?file=/src/App.js

Try commenting the line 200, and the bug won't occur anymore

- OS: Windows 10
- Browser Chrome and Firefox (last versions)

**Comment by gargroh** [comment]
`autoResetPage` is way to go https://react-table-omega.vercel.app/docs/api/usePagination#table-options

**Comment by laazaz** [comment]
I have autoResetPage on my code.

**Comment by datner** [comment]
This exact case is referenced in the [FAQ](https://react-table.tanstack.com/docs/faq#how-do-i-stop-my-table-state-from-automatically-resetting-when-my-data-changes), with an answer and explanation 😄

**Comment by laazaz** [comment]
@datner that's exactly what I have on my codesandbox example and it still doesn't work if I don't ignore the parametre `skipReset`

**Comment by datner** [comment]
The codesandbox is just a link to the "entire kitchen sink" example, there is no way I can narrow down what causes the exact same bug you're experiencing. For that reason, I forked the "Editable Data" example and added a selectable implementation.
https://codesandbox.io/s/fancy-resonance-ivomf?file=/src/App.js

(Un?)fortunately it Just Works™, something completely unrelated to `useSelectableRow`, `usePagination` or the implementation of editable is causing the bug in the kitchen sink example. If I missed something, please let me know.

Also, for future issues, please do your best to submit a repro case with the minimum possible variables.. You wouldn't submit pizza to a judge to argue that Tomatoes make you fat 😉
