### ISSUE TITLE
Vertical and Horizontal Headers?

### ISSUE THREAD

**Issue by wassim** [TanStack/react-table#2863]
This is a dumb question but how can we achieve this kind of table?

```html
         header1 header2 header3 
header1    1        1      1
header2    2        2      2 
header3    3        3      3 
```

**Comment by herodrigues** [comment]
Just use one header for all columns and hide it.

See https://github.com/tannerlinsley/react-table/issues/2407

**Comment by a8hokkumar** [comment]
@wassim I am also situated  to form a kind of table you asked. any luck for you? did you achieve it?

Please do the needful.
