### ISSUE TITLE
Property 'selectedFlatRows' does not exist on type 'TableInstance<object>'.

### ISSUE THREAD

**Issue by climaxwres** [TanStack/react-table#2874]
i was following this [example ](https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/row-selection?file=/src/App.js:0-4193)
and trying to add selectedFlatRows,state: { selectedRowIds } in instance but both return this error

packages  "react-table": "^7.6.2","@types/react-table": "^7.0.25","@types/react": "^16.9.56","react": "^17.0.1",

**Comment by easteryard** [comment]
I've run into the same problem.

"react": "^17.0.1"
"@types/react": "^17.0.0"

"react-table": "7.6.3"
"@types/react-table": "7.0.28"

**Comment by SZharkov** [comment]
Guys follow instructions here - https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-table .
Create a `react-table-config.d.ts` with all the code mentioned in docs.
