### ISSUE TITLE
using controlled pagination default rows are not working

### ISSUE THREAD

**Issue by SandeepKapalawai** [TanStack/react-table#2880]
Hello Every one,

Not sure if this is a bug or code issue.

I started using the react table few days ago , i was trying to customize my table having a button which should should +10 more records, but up on initial loading i need to display only 10 records per page.o

I read the documentation even though if i didn't mention the pageSize it will take as default to 10, but what i see from my code it is defaulting to total number of available rows i.e, 14 which i was expecting 10 should be displayed at the first instance then later on when i click on the show more button it should the other 4 records.

I tried the same example but am i missing something or is it abug,

Please find the below code sandbox

https://codesandbox.io/s/gifted-dream-xbqnd?file=/src/App.js

Thank you

**Comment by AgmarTorres** [comment]
It is not a bug, it is just that the product array contains 14 items, and each page is captured the property of the data.length component of that product array. Each changed page restarts the cycle and displays the same result. It would be interesting to have a limit on the quantity of items to present, I think it is an interesting feature to implement
