### ISSUE TITLE
How to use row selection with virtualized tables

### ISSUE THREAD

**Issue by dobrakmato** [TanStack/react-table#2899]
**Describe the bug (required)**
The checkbox doesn't turn blue when I click on it.

**Provide an example via Codesandbox! (required)**
I basically merged to example codesandboxes.

https://codesandbox.io/s/serene-shaw-9susg?file=/src/App.js

**Steps To Reproduce (required)**

1. Go to sandbox
2. Click on any checkbox
3. Checkbox isn't checked
4. Scroll down
5. Now the checkbox is updated.

**Expected behavior (Recommended)**
I expect the row to be selected and checkbox to be checked when I click on it, not after I scroll the table.

**Screenshots**
After I click:

![image](https://user-images.githubusercontent.com/779469/100542877-2cc65c80-324d-11eb-8e34-7770c074742a.png)

After I scroll:

![image](https://user-images.githubusercontent.com/779469/100542890-3a7be200-324d-11eb-9ffb-bf068e8cf638.png)

**Desktop (please complete the following information):**

- OS: Windows 64bit
- Browser Chrome
- Version Version 86.0.4240.198 (Official Build) (64-bit)

**Comment by datner** [comment]
Huh, interesting. My guess would be because the rows somehow retains its reference due to `tableInstance` being a static ref since adding `rows.map(row => row.isSelected)` to the `renderRow` deps array does make sure things are updated on time. Either way, this is easily solvable by either doing just that (but get linting errors), or better yet, make the callback return a callback

```tsx
const RenderRow = React.useCallback(
    (rows) => ({ index, style }) => {
      const row = rows[index];
      prepareRow(row);
      return (
        <div
          {...row.getRowProps({
            style
          })}
          className="tr"
        >
          {row.cells.map((cell) => {
            return (
              <div {...cell.getCellProps()} className="td">
                {cell.render("Cell")}
              </div>
            );
          })}
        </div>
      );
    },
    [prepareRow]
  );


/// Later
<VirtualListThing>
  {renderRow(rows)}
</VirtualListThing>
```

Either way, it's not really a bug, its how react works

**Comment by cactusjosh** [comment]
@datner, is this 'behaviour' documented? If not, should we consider adding it? This tripped me up too, purely by blindly copy-pasting and combining the examples.
