### ISSUE TITLE
[Documentation] autoResetFilters is triggered when `columns` changes

### ISSUE THREAD

**Issue by phoenixeliot** [TanStack/react-table#2901]
**Describe the bug (required)**
It appears that the behavior that `autoResetFilters` prevents is triggered not just when `data` changes (as the docs say), but also when `columns` changes.

This is based on observation in my own code. My `columns` property has a custom render in the Header to implement a filter select UI for that column, so my `columns` useMemo has as a dependency a state variable tracking whether that menu is open.

When that visibility state variable changes, the filters are wiped clean. (This took a good while to figure out why.)

This may be true of a few other "autoReset" options like pagination and thus need updating to the docs there as well, but I'm not in a position to check easily right now.

**Provide an example via Codesandbox! (required)**
Use a new [react-table codesandbox](https://codesandbox.io/s/m5lxzzpz69) to reproduce the issue.
^ The provided codesandbox link is broken. If fixed, I can try to create a demo for this.

**Steps To Reproduce (required)**

1. Set up a table using `useTable`. Do not set `autoResetFilters`. Include useFilters.
2. In the call to useMemo for `columns`, pass a variable as a dependency. You might have to use that variable in the columns definition somehow, not sure.
3. Set a filter with setFilter(columnKey, ...)
4. Trigger a change to the columns dependency state variable

The filter applied is now cleared.

**Expected behavior (Recommended)**
The documentation should say that changes to `columns` also triggers a filter reset. The documentation should perhaps also say more loudly that this auto-reset behavior exists, as I found it very unexpected.

Or, the functionality should change to not trigger a filter reset.

**Screenshots**
None for now.

**Desktop (please complete the following information):**

- OS: macOS 10.14.6
- Browser: Chrome 87

**Comment by phoenixeliot** [comment]
Oddly, I'm finding that Jest is unable to reproduce this behavior when I was trying to write a regression test for it. But it still consistently repros in my component demo page unless I set `autoResetFilters: false`.

**Comment by datner** [comment]
This is a pretty specific example, please provide a codesandbox with the minimal repro. I am a bit discouraged that a dead link stopped you from making a repro, but here is a replacement:
https://codesandbox.io/s/amazing-leakey-fmvss?file=/src/App.js

I've looked through the source code for `useTable` and `useFilters` and if I understand the logic, the docs are correct. Filters should reset when only the data changes (if you don't prevent it from resetting the filters)

**Comment by phoenixeliot** [comment]
I've never set up dependencies on codesandbox and didn't want to break my workflow to figure out how ;)

But to update on the actual issue: Bah, I'm finding that this only happens on the second demo component where I forgot to use `useMemo` for the data, so this may all be a false positive on my end anyway. Haven't found a proper repro yet that I can share, so, womp. Sorry to waste your time.

**Comment by datner** [comment]
`useRef` for the data? you mean `useMemo`?

**Comment by phoenixeliot** [comment]
Ah, either seems to work here actually if the data doesn't change (you still need to destructure the value out of it and pass that through). Forgot which one was the official one (useMemo, I remember now), but in this case the data wasn't changing so useRef prevented it from being regenerated as a new object.

**Comment by datner** [comment]
You should delve into what these hooks actually do, because you might be introducing hard to find bugs
