### ISSUE TITLE
Parent rows lose the ability to select all subRows when paginateExpandedRows is disabled

### ISSUE THREAD

**Issue by bgilm** [TanStack/react-table#2908]
**Describe the bug (required)**
Whenever the paginateExpandedRows is set to false, subRows lose the selection props needed and the parentRow isn't able to check/uncheck them all.

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/useexpanded-userowselect-parent-indeterminate-bug-forked-8jq2p?file=/src/App.js

Here's a small implementation with the bug showing, set paginateExpandedRows to true and you'll get it to work normally.

**Steps To Reproduce (required)**

1. Go to the rendered table
2. Click on any parent row to expand its subRows
3. Click select all on the parent row
4. See error by subRows not updating
5. Additionally see the console.log of the rows and see the subRows lose their selection props

**Expected behavior (Recommended)**
I'd expect parent rows to be able to select/unselect all subRows regardless of if subRows are being paginated or not.

Other way to say this is that subRows should preserve selection props even though they are not paginated.

**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOs
- Browser: Firefox Developer
- Version: 84.0b4

**Additional context**
Not sure if I am missing something, but if you use page to iterate over the rendered rows you lose this ability when dropping the pagination. I tried to see if looking at the rows instance object would help but it's the same.

**Comment by JonatanGarciaClavo** [comment]
@bgilm I face the same situation, did you find a workaround or something to deal with it?
I did a quick search in the repository and there aren't that many places where that flag has been used. Not sure how that could affect the selection.

**Comment by JonasRothmann** [comment]
Any updates on this? I am facing this problem too
