### ISSUE TITLE
alphanumeric sort is inconsistent for decimals if decimal part is not equal length

### ISSUE THREAD

**Issue by kyriediculous** [TanStack/react-table#2909]
**Describe the bug (required)**
When trying to sort decimals using alphanumeric sorting the results are inconsistent depending on the length of the decimal part. 

The values to be sorted are split into a string but if the decimal part consists of less decimal numbers  and the integer part is equal, it will automatically be treated as a smaller number despite that the decimal number as a whole might be larger. This can occur when a decimal number is truncated / rounded. 

Example: 

0.05 vs 0.045  will indicate that 0.045 > 0.05 

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/exciting-river-ghde9?file=/src/index.js

**Expected behavior (Recommended)**
Decimal number should be consistent regardless of decimal part length 

**Screenshots**
![image](https://user-images.githubusercontent.com/22256858/101077807-a17afd00-35a5-11eb-8d94-479e5143cd79.png)

**Comment by boatcoder** [comment]
And sorting by words and numbers is even stranger.

https://codesandbox.io/s/sorting-gone-wild-fujl5

This is the same example from the repo with 
```
export default function makeData(...lens) {
  const makeDataLevel = (depth = 0) => {
    const len = lens[depth]
    return range(len).map(d => {
      return {
        ...newPerson(),
        subRows: lens[depth + 1] ? makeDataLevel(depth + 1) : undefined,
      }
    })
  }

  const result = makeDataLevel();
  result[0].firstName='888';
  return result;
}
```
This small change added to makeData.  In this case, numbers sort AFTER words instead of before them.  Not exactly the same bug, but still kind of bizarre.

**Comment by boatcoder** [comment]
The problem is in this file in the alphanumeric sort code

https://github.com/tannerlinsley/react-table/blob/master/src/sortTypes.js

**Comment by datner** [comment]
Classic JS. Pretty sure the line at fault is [this one](https://github.com/tannerlinsley/react-table/blob/434376295cde749d80b6253b37a4b50c26a89ef1/src/sortTypes.js#L26), `.sort`, if not supplied a sort function, just converts everything to string and sorts lexicographically [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort). 

>If compareFunction is not supplied, all non-undefined array elements are sorted by converting them to strings and comparing strings in UTF-16 code units order. For example, "banana" comes before "cherry". In a numeric sort, 9 comes before 80, but because numbers are converted to strings, **"80" comes before "9" in the Unicode order**. All undefined elements are sorted to the end of the array.

Do take care that I might be completely wrong here, as I did not have the focus to understand the snippet in depth. But this popped out 😃
