### ISSUE TITLE
useFlexLayout - invalid flex value for width defined

### ISSUE THREAD

**Issue by krzysztof-kabala** [TanStack/react-table#2920]
**Describe the bug**
Let's create a new table:
```
const {
    ...
  } = useTable<T>(
    {
      ...props,
    },
    useFlexLayout
  )
```
with columns:
```
  const columns = React.useMemo<Column<DepositTableRow>[]>(
    () => [
      {
        Header: 'X',
        accessor: 'x',
        width: 100,
      },
      {
        id: 'y',
        accessor: row => row.something
        width: 80,
      },
      {
        Header: 'Z',
        accessor: 'z'
        width: `auto`,
      },
    ],
    []
  )
``` 
When you check the `style` property for `HeaderGroup<T> -> getHeaderProps` and `Cell<T> -> getCellProps`, it's generated from `src/plugin-hooks/useFlexLayout.js` methods.

Now please check (line 38):
```
flex: column.totalFlexWidth
        ? `${column.totalFlexWidth} 0 auto`
        : undefined,
```
and also line 52:
```
flex: `${cell.column.totalFlexWidth} 0 auto`,
```
it simply can't work because of a few things:
- we allow to set width as a `string or number`, so once we use `auto` as width value, or any other string, the `calculateHeaderWidths` (`src/hooks/useTable.js`) won't work - because `header.width` is used as a number
- setting `width` and `minWidth` along with `flex` doesn't make a lot of sense
- allowed `flex` value is: `flex: none | [ <'flex-grow'> <'flex-shrink'>? || <'flex-basis'> ]`, so the right value for `width = 80` is:
`flex: 0 0 80px;` (optionally `flex: 0 1 80px;` is `minWidth` is not defined). For `width = auto` the right value is `flex: 1`

**Provide an example via Codesandbox!**
Use a default `useFlexLayout` sample from the documentation [examples/full-width-resizable-table codesandbox](https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/full-width-resizable-table)

**Steps To Reproduce**

1. Go to codesandbox
2. check `width = 150` -> `flex: 150 0 auto;`, then check `width = '150px'` -> `flex: undefined` + `width: NaNpx`

**Expected behavior**
- `width = 150` -> `flex: 0 0 150px;`
- `width = '150px'` -> `flex: 0 0 150px;`
- `width = 'auto'` -> `flex: 1;`

**Desktop :**

- OS: all versions
- Browser all versions

**Additional context**
I think the `width` property should be typed as `width: 'auto' | unsigned number` then `auto` width is calculated as zero, and `0` value is not allowed (actually it doesn't make sense to create a column with zero width).
Then we can calculate total width correctly (flex will adjust the "auto width" column automatically - but we can also set 150 as default value for calculation when resize mode is enabled).
And we can support a dynamic column width along with static width then :)

**Comment by codeaid** [comment]
Having the same issue. I've defined my column width as `150` and I end up with `flex` set to `150 0 auto` on the cell. Not sure how to work around this without removing the `useFlexLayout` hook.

**Comment by Kepro** [comment]
and I will add one more mystery... check this example https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/full-width-resizable-table

it's using flexLayout but it's adding correct flex styles to checkbox and it respect
```
          minWidth: 35,
          width: 35,
          maxWidth: 35,
```

generated styles
```
    box-sizing: border-box;
    flex: 0 0 auto;
    min-width: 35px;
    width: 35px;
    justify-content: flex-start;
    align-items: flex-start;
    display: flex;
```

but rest of the fields same issue as mentioned in this issue
```

element.style {
    box-sizing: border-box;
    flex: 150 0 auto;
    min-width: 30px;
    width: 150px;
    justify-content: flex-start;
    align-items: flex-start;
    display: flex;
}
```
also started discussion here https://github.com/tannerlinsley/react-table/discussions/3564
