### ISSUE TITLE
subRows are set to empty lists if filter is returns no items

### ISSUE THREAD

**Issue by wbolduc** [TanStack/react-table#2928]
**Describe the bug (required)**
When you are using useFilter or useGlobalFilter, if you set and clear a filter subRows which matched no items get set to empty lists

**Provide an example via Codesandbox! (required)**
Use a new [react-table codesandbox]https://codesandbox.io/s/filters-are-broken-di3v6?file=/src/App.js) to reproduce the issue.

**Steps To Reproduce (required)**
Steps to reproduce are in the codepen

**Expected behavior (Recommended)**
Clearing a filter to it's original state should result in the table as it was *before* filtering

**Desktop (please complete the following information):**
- OS: Windows
- Browser: [firefox, chrome...]
- Version: 83

**Comment by mdaj06** [comment]
@tannerlinsley  is this still open if so can i contribute, this needed fixing

**Comment by Lingxiao-Ma** [comment]
I run into this issue too.
react-table memoized instance.rows, however instance.rows.subrows is mutated in filter and global filter hooks.
A quick fix is to disable the memoization for instance.rows, apparently it have negative impact in performance.

any thoughts, @tannerlinsley ?
