### ISSUE TITLE
Add Plugin Guide

### ISSUE THREAD

**Issue by vegetabill** [TanStack/react-table#2930]
**Describe the bug (required)**
The docs imply there is a plugin guide but it's not a link.

https://github.com/tannerlinsley/react-table/blob/e266c5b666b6b464941727b5e42995f7179634e9/docs/src/pages/docs/api/overview.md#L63

Please add one. 

I ended up looking at the source to learn about them.

**Comment by carsondarling** [comment]
In addition to just documenting which hooks are available for plugins, I would love to see some guidance on which hooks to use for specific use cases.

For example, the "Row Selection" example uses the `visibleColumns` hook ([ref](https://github.com/tannerlinsley/react-table/blob/master/examples/row-selection/src/App.js#L70)), but I believe it used to use the `allColumns` hook and I still don't fully understand the tradeoffs with that switch.

**Comment by datner** [comment]
I don't think there's much value in in-depth explaining why every part of the inners of a hook is like that in the documentation. But a simple example of how to make hooks is in order I agree

**Comment by beamery-tomht** [comment]
I agree with @carsondarling , the use cases for each of the hooks are lacking. What's the purpose for each of the hooks?

- useOptions
- stateReducers
- columns
- columnsDeps
- allColumns
- allColumnsDeps
- visibleColumns
- visibleColumnsDeps
- headerGroups
- headerGroupsDeps
- useInstanceBeforeDimensions
- useInstance
- prepareRow
- useControlledState
- getTableProps
- getTableBodyProps
- getHeaderGroupProps
- getFooterGroupProps
- getHeaderProps
- getFooterProps
- getRowProps
- getCellProps
- useFinalInstance

That's quite a lot of hooks to be digging through source code to understand ^.

**Comment by Hexavolus** [comment]
I need to write a plugin so I've now come across this as well. It's going to be a lot of trial and error to determine how to do things and what is the best way to do things.

Besides the big lengthy list of hooks that you can hook into there's also a bunch of utility functions that are a bit of a guessing game.

`ensurePluginOrder` seems fairly important, what exactly is `useGetLatest` doing? I can figure these out by digging through the source and such but it's a bit of a slog.

**Comment by seanonthenet** [comment]
I doubt it will happen as plugins are being removed in v8.

**Comment by tannerlinsley** [comment]
You are correct

Tanner Linsley
