### ISSUE TITLE
React Table Selection trigger rerender on React Native Web / Another Custom Component

### ISSUE THREAD

**Issue by fortezhuo** [TanStack/react-table#2933]
**Describe the bug (required)**
I want to create universal React Native component that using react table. 
And I have found React Native component (WEB) like View, Text will be rerendered with checkbox ticked. But no rerender component triggered while I use html component like tr, td.

I have forked react table useRowSelect codesandbox, and replace header with View and Text component, and still keep body component as usual. And we will find header component will rerender while checkbox toggled quickly.

![image](https://user-images.githubusercontent.com/9128724/102674561-ff742b00-41c8-11eb-8019-bf7a625cedee.png)

**Updated**  
I have created dummy Component named Div, 

```
const Div = ({ children, style }) => <div style={style}>{children}</div>;
```
And also trigger rerender while checkbox ticked. So I think this problem caused if we use custom component instead html component

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/friendly-pond-bx1nh?file=/src/App.js

**Steps To Reproduce (required)**

1. Go to the codesandbox above
2. Click Open in new window with Inspect Element / React Dev Tools.
3. Toggle on off checbox quickly 
4. We will found header component that created using View, Text will rerender (orange color) 

**Another step to reproduce**
1. Replace tr with Div on codesandbox
2. Toggle on off checbox quickly 
3. We also found body row component that created using Div will rerender 

```
<tbody {...getTableBodyProps()}>
          {rows.slice(0, 10).map((row, i) => {
            prepareRow(row);

            // replace below tr with Div will trigger rerender

            return (
              <tr {...row.getRowProps()}>
                {row.cells.map((cell) => {
                  return (
                    <td {...cell.getCellProps()}>{cell.render("Cell")}</td>
                  );
                })}
              </tr>
            );
          })}
        </tbody>
```
to 
```
<tbody {...getTableBodyProps()}>
          {rows.slice(0, 10).map((row, i) => {
            prepareRow(row);

            // replace below tr with Div will trigger rerender

            return (
              <Div {...row.getRowProps()}>
                {row.cells.map((cell) => {
                  return (
                    <td {...cell.getCellProps()}>{cell.render("Cell")}</td>
                  );
                })}
              </Div>
            );
          })}
        </tbody>
```

**Expected behavior (Recommended)**
No unnecessary rerender triggered while checbox toggled

**Screenshots**
![image](https://user-images.githubusercontent.com/9128724/102674561-ff742b00-41c8-11eb-8019-bf7a625cedee.png)

![image](https://user-images.githubusercontent.com/9128724/102675748-27658d80-41cd-11eb-87e6-aee381faf078.png)

**Desktop (please complete the following information):**

- OS: macOS 11 Big Sur
- Browser Firefox
- Version 83

**Comment by skychavda** [comment]
@fortezhuo Is there any documentation for react-table that how to use in react native application? If there is can you ping me that one that will be help full. 

I am using `react-table-6` in my native application but stuck with errors like this 

> Error: Text strings must be rendered within a <Text> component.

If you have any idea regarding to this error then also help me to overcome it.

Thank you.

**Comment by fortezhuo** [comment]
I think we should use react table 7 with own custom component. Here some code of my postponed  repo.. I still don't have time to optimize. Hope this helps 

```
export const TableContent: React.FC<JSONObject> = React.memo(
  ({ view, useSelection, isLoading, data, actions }) => {
    const isMobile = view.app.temp.isMobile
    const { columns, columnsFormat, collection } = data
    const TableWrapper = isMobile || isLoading ? Table.Default : Table.Scroll
    const {
      headerGroups,
      prepareRow,
      selectedFlatRows,
      page: rows,
    }: any = useTable(
      {
        columns,
        data: collection,
        initialState: { pageIndex: 1 },
        manualPagination: true,
        defaultColumn: columnsFormat,
        pageCount: data.max,
      } as any,
      useSortBy,
      usePagination,
      useRowSelect,
      useSelection
    )
    isLoading = isLoading || headerGroups[0].headers.length === 1

    useMountedLayoutEffect(() => {
      if (!isLoading)
        view.store.ref.selected.current = selectedFlatRows.map(
          (row: any) => row.original._id
        )
    }, [selectedFlatRows, isLoading])

    return (
      <>
        <TableWrapper sx={{ flex: 1 }}>
          {headerGroups.map((headerGroup: any, i: number) => {
            const style = isMobile ? { height: 0, opacity: 0 } : {}
            return (
              <Table.Header key={random()} style={style}>
                {headerGroup.headers.map((column: any, j: number) => {
                  return <TableHeaderCell key={random()} column={column} />
                })}
              </Table.Header>
            )
          })}
          {isLoading ? (
            <View
              sx={{ flex: 1, alignItems: "center", justifyContent: "center" }}
            >
              <Loader dark />
            </View>
          ) : (
            <FlatList
              data={rows}
              keyExtractor={() => random()}
              renderItem={({ item, index }: any) => {
                prepareRow(item)
                return (
                  <TableRow
                    {...{
                      view,
                      isMobile,
                      isLoading,
                      dark: index % 2,
                      data: item.values,
                      actionLeft: isMobile && actions.swipe[1],
                      actionRight: isMobile && actions.swipe[0],
                    }}
                  >
                    {item.cells.map((cell: any, i: number) => {
                      const isHide =
                        isMobile && colMobileHidden.indexOf(cell.column.id) >= 0
                      return (
                        <View key={`cell_${i}`}>
                          {isHide ? <></> : cell.render("Cell")}
                        </View>
                      )
                    })}
                  </TableRow>
                )
              }}
            />
          )}
        </TableWrapper>
      </>
    )
  }
)
```
