### ISSUE TITLE
Performance very slow when managing 50,000 rows aprox (v6)

### ISSUE THREAD

**Issue by liben96** [TanStack/react-table#2935]
Refreshing 50K rows slows down the performance of the table. We are showing 20-30 elements per page, and we have a total of 2000 pages. When we try to jump to page X, the table takes around 10-15 seconds to refresh. When we try to search or filter the table, we experience the same issue.

Any ideas how to fix this?
Is someone managing thousands of rows with no delay?

This is using react table v6.11

We cant provide an example/screenshot due to data protection

- OS: iOS and Windows
- Browser: Chrome and Safari

**Comment by mrceperka** [comment]
AFAIK v6.11 is no longer supported.

A possible solution for your problem is to move pagination and filtering to server.
The server will then return only subset of those 50K rows.

**Comment by ledbetterljoshua** [comment]
@mrceperka are you aware of any examples of filtering being moved to the server?

**Comment by mrceperka** [comment]
@ledbetterljoshua No, I am not. I had to figure it out on my own. I've ended up not using `onFetchData` because is caused me infinite loops.

6.x is deprecated anyway so it would be best for you to start with 7.x if you can.

**Comment by ledbetterljoshua** [comment]
@mrceperka Yep, I am. After a little more digging, I think the solution is to set manualFilters to true and send the filters to the server, returning the filtered data. I don't have anything working yet, but I think I'm on the right track.

**Comment by siddharth-283** [comment]
I'm facing the same issue i have an idea is it possible to fetch the 10 or 20 or 30 records based on the pagination clicked than it must retrieve the data from the database not all record at on call . I'm using the datatable library
