### ISSUE TITLE
MultiSelect Dropdown (react-select)  options appears below the table 

### ISSUE THREAD

**Issue by nitishnivedan** [TanStack/react-table#2945]
Hi,

I am using Multi select dropdown (importing Select from "react-select") in one  of the columns of react table and the dropdown appears below the table. issue with the css part. 

I am attaching the screenshot.

![image](https://user-images.githubusercontent.com/30456511/103208986-eafe0400-4927-11eb-9b98-a35b9c7d381d.png)

instead of dropdown options going over the table, it goes down the table and as a result vertical scroll appears. have tried z-index and stuff but no luck as of now.  Kindly help. thanks in advance.

**Comment by datner** [comment]
This is unrelated to react-table, it's just how html works.
please refer to react-select and search their documentation how to use portals

**Comment by nitishnivedan** [comment]
@datner - yeah, I have checked portals, still no luck.  may be portal works well with react-select when used in react table version 6, not the version 7. Anyways thanks for your suggestion.

If any  one else has faced this issue while using react-select (multiple dropdown) in react-table, then please do suggest. Any lead is appreciated. Thanks

**Comment by datner** [comment]
react-table 7 is headless and does not render Dom at all, I can't even think where to begin

**Comment by nitishnivedan** [comment]
Agreed. but portal isnt the solution in this case.

**Comment by datner** [comment]
Why not? Protals exist for that exact reason, z-index can't help you here

**Comment by nitishnivedan** [comment]
@datner - applied portals and the dropdown menu is appearing completely outside the table. Please see my screenshot.

![image](https://user-images.githubusercontent.com/30456511/103509152-788da680-4e88-11eb-986f-97b8e46b671a.png)

Some piece of code I am attaching here:-

(MultiSelectDropdown Component)

<Select
      value={selectedOptions}
      onChange={onChangeHandler}
      options={options}
      isMulti={true}
      styles={customStyles}
      menuPortalTarget={document.body}
    />


The below code is for one particular column to render the above multi select dropdown in each column
{
    Header: () => (
      <div>
        WBSE
        <span
          class="required"
          style={{ color: "#ff0000" }}
        >
          *
        </span>
      </div>
    ),
    accessor: "WBSE",
    disableFilters: true,
    canGroupBy:false,
    Cell: ({row}) => {
      return <WBSE rowno={row.index}  />;
    },
  },

**Comment by datner** [comment]
I have to say I no idea why you would think this is related to `react-table`, and I don't really understand anything from the pictures. So to lay this issue to rest, here is a [codesandbox example](https://codesandbox.io/s/immutable-night-olrsn?file=/src/App.js) of how you can make react-select exist above the table



note  that `First Name` is without a portal, the `Last Name` is with a portal. Everything is working as expected

**Comment by nitishnivedan** [comment]
@datner  - i really dont understand why u keep saying its not related to react-table if u can fix it. anyways not convinced by the cosmetic look of the table u have given in first place.

To end this issue, i have shared the link below in codesandbox. Have added u in code sandbox and modify it if u r abe to fix it.Appreciate ur time.


https://codesandbox.io/s/hopeful-thompson-trs9f

**Comment by datner** [comment]
there you go, fixed. My change is @ `Columns.js:29`

**Comment by nitishnivedan** [comment]
@datner Not so easy bro. I have added some more columns. try to scroll while the dropdown is open, u will find the issue. But appreciate your effort.

![image](https://user-images.githubusercontent.com/30456511/103802434-2198f480-5075-11eb-861f-618f5f8241fe.png)

**Comment by datner** [comment]
again, completely unrelated to `react-table`. Please follow [this issue](https://github.com/JedWatson/react-select/issues/3734) if you want more help

**Comment by nitishnivedan** [comment]
@datner  - haan related/unrelated, separate thing. But its not fixable with your portal thing. right? :D .

**Comment by nitishnivedan** [comment]
@datner - one request. sorry if i am being rude but you should refer the documentations after you go through it once. the above link which u just shared,has the limitiation of scrolling not happening within once you apply the workaround, menuShouldBlockScroll={true}.

**Comment by ProtestSoftware** [comment]
> This is unrelated to react-table, it's just how html works.
> please refer to react-select and search their documentation how to use portals

Thanks mate, this helped a lot, portals work perfectly!

**Comment by nitishnivedan** [comment]
@datner - bro, need ur help. is there any solution for this issue: https://github.com/tannerlinsley/react-table/issues/2945

let me know if u need any more information

**Comment by nitishnivedan** [comment]
@datner  - bro is there any solution for this https://github.com/tannerlinsley/react-table/issues/3152 

please let me know if u need any more information
