### ISSUE TITLE
[useGlobalFilter] sets the undocumented flag `canFilter`

### ISSUE THREAD

**Issue by datner** [TanStack/react-table#2949]
**Describe the bug (required)**
`useGlobalFilter` sets `column.canFilter` to `true` when it's filtering, breaking generic abstractions that support this `useGlobalFilter` and `useFilters` separately.

for example:
```tsx
/* many infra functions, just imagine them */
function TableFriend() {
  // memoized stuff here
  const instance = useTable({data, columns, globalFilterFn: fuzzyTextFilterFn}, useGlobalFilter)

  // imagine a lot of table rendering before this line
  return column.canFilter ? filter.render('Filter') :  null
} 
```

I've omitted a lot of stuff, but that is because you can read the whole thing in the code sandbox below
**Provide an example via Codesandbox! (required)**
[global filter only](https://codesandbox.io/s/eloquent-voice-nhbkx?file=/src/App.js)

**Steps To Reproduce (required)**

1. create basic table
2. import `useGlobalFilter`
3. implement filter whichever way
4. log `column.canFilter` 
5. interact with filter
6. see `canFilter` is suddenly set

**Expected behavior (Recommended)**
Either `canFilter` is unaffected or is documented and supported

**Desktop (please complete the following information):**

- OS: iOS
- Browser chrome
- Version 87

**Additional context**
The docs also use outdated api, mismatching with the documentation and the types in `@types/react-table`

I'm trying to build an internal grid using react-table, and I want it to support as many cases as possible (since product people sometimes don't really make sense).

I vaguely remember seeing something about this already, but I couldn't find it. 
For quick reference I found the culprit line [here](https://github.com/tannerlinsley/react-table/blob/a87f62cc379b6aa5ef9acaa29ec1114e7d5e12a9/src/plugin-hooks/useGlobalFilter.js#L116)
excerpt: 
```ts
  allColumns.forEach(column => {
     const { disableGlobalFilter: columnDisableGlobalFilter } = column
     column.canFilter = getFirstDefined(
       columnDisableGlobalFilter === true ? false : undefined,
       disableGlobalFilter === true ? false : undefined,
       true
     )
   })
```

**Comment by datner** [comment]
in case this comes up, it can be easily patched by supplying a default `Filter` 

```tsx
const defaultColumn = useMemo(() => ({
  Filter: () => null
})
```

idk if it's best-practice but here is a hook to do it all at once:
```ts
import {
  Column,
  ensurePluginOrder,
  Hooks,
  TableInstance,
  useGlobalFilter,
  emptyRenderer,
} from 'react-table';

const pluginName = 'useSafeGlobalFilter';

export function useSafeGlobalFilter<D extends object>(hooks: Hooks<D>) {
  hooks.columns.push(columns);
  hooks.useInstance.push(useInstance);
  useGlobalFilter(hooks);
}

useSafeGlobalFilter.pluginName = pluginName;

function columns<D extends object>(columns: Column<D>[]) {
  return [...columns.map(column => ({ Filter: emptyRenderer, ...column }))];
}

function useInstance<D extends object>(instance: TableInstance<D>) {
  const { plugins } = instance;
  try {
    ensurePluginOrder(plugins, ['useGlobalFilter'], pluginName);
  } catch (e) {
    throw new Error(
      `You don't need to supply a useGlobalFilter hook when supplying useSafeGlobalFilter since it contains it`
    );
  }
}
```

**Comment by DDeredec** [comment]
Encountered the same issue today.

It would be great to either document it if this is intended, or fix this unexpected behaviour 🙌
