### ISSUE TITLE
Property 'getResizerProps' does not exist on type 'HeaderGroup<object>' 

### ISSUE THREAD

**Issue by chyyran** [TanStack/react-table#2952]
**Describe the bug (required)**
`getResizerProps()` property does not work when using TypeScript with `@types/react-table@7.0.26`

**Steps To Reproduce (required)**
```typescript
  
    const tableInstance = useTable(
        { columns, data },
        useBlockLayout,
        useResizeColumns,
    );
        
    const {
        getTableProps,
        headerGroups,
    } = tableInstance;
    
return (
    // apply the table props
   <div {...getTableProps()} className="table">
       <div className="table-header">
           {
               headerGroups.map(headerGroup => (
                   <div {...headerGroup.getHeaderGroupProps()} className="table-header-row">
                        { headerGroup.headers.map(column => (
                            <div {...column.getHeaderProps()} className="th">
                            {column.render('Header')}
                            <div
                              {...column.getResizerProps()} //Property 'getResizerProps' does not exist on type 'HeaderGroup<object>'.  TS2339
                            />
                          </div>
                        ))}
                   </div>
               ))
           }
       </div>
   </div>
  )
```
**Expected behavior (Recommended)**

`getResizerProps` should exist on `column`

**Comment by chyyran** [comment]
It seems the other plugins don't work either. `useSortBy` doesn't add any of its properties onto the `column`.

**Comment by samyan** [comment]
I have a similar issue with other plugin. I think the main problem comes from index.d.ts. They need to update it.

**Comment by DaniAkash** [comment]
As per `@types/react-table` package it only supports up to [react-table 7.0.4](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9c1e78c99106fc3e1be574ca1b968d01963e032d/types/react-table/index.d.ts#L9)

**Comment by anvlkv** [comment]
It needs this additional d.ts in your project to work with typescript https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-table#example-type-file

**Comment by oltodo** [comment]
Simply add the bellow lines in a `.d.ts` file:

```typescript
import { UseResizeColumnsColumnProps } from "react-table";

declare module "react-table" {
  export interface ColumnInstance<
    D extends Record<string, unknown> = Record<string, unknown>
  > extends UseResizeColumnsColumnProps<D> {}
}
```
