### ISSUE TITLE
[Typescript] "Footer" is not inferred from Column type

### ISSUE THREAD

**Issue by baeharam** [TanStack/react-table#2983]
**Describe the bug (required)**

I'm using Typescript with react-table, I wanted to add footer to table. However, when I define `columns` data `Column` type couldn't infer `Footer` type. 

**Provide an example via Codesandbox! (required)**

https://codesandbox.io/s/test-react-table-wwemm?file=/src/data.ts
You can see `Footer` is causing type error

**Expected behavior (Recommended)**

`Column` type should be able to infer `Footer` type

**Screenshot**

![스크린샷 2021-01-12 오후 3 25 59](https://user-images.githubusercontent.com/35518072/104277614-7c55a480-54ea-11eb-9799-891d9852599f.png)

**Additional context**

Related discussion: https://github.com/tannerlinsley/react-table/discussions/2882 (unsolved)

**Comment by ckifer** [comment]
+1 experiencing the same issue. If you have multiple columns you can set the footer on all column items except for one. For example:
```
// doesn't work with the same error as above
const columns = [
    {
       Header: 'header1',
       Footer: 'footer1',
       accessor: 'test'
    },
    {
       Header: 'header2',
       Footer: 'footer2',
       accessor: 'test2'
    },
    {
       Header: 'header3',
       Footer: 'footer3',
       accessor: 'test3'
    },
];
```
```
// works and resolves just fine by removing first Footer item
const columns = [
    {
       Header: 'header1',
       accessor: 'test'
    },
    {
       Header: 'header2',
       Footer: 'footer2',
       accessor: 'test2'
    },
    {
       Header: 'header3',
       Footer: 'footer3',
       accessor: 'test3'
    },
];
```

**Comment by EctordAniel** [comment]
Tengo el mismo problema.
![captura](https://user-images.githubusercontent.com/57757074/111915803-d167e680-8a56-11eb-9463-e527ec11e63a.png)

**Comment by minemanemo** [comment]
I solved it by setting it like this:

- focus is that do not modify `@types/react-table`.

- Follow code is my `react-table-config.d.ts` (this code is base to [URL](https://gist.github.com/ggascoigne/646e14c9d54258e40588a13aabf0102d))

```
import { UseTableColumnOptions as BasicUseTableColumnOptions } from 'react-table'

declare module 'react-table' {

  export type FooterProps<D extends object> = TableInstance<D>

  export interface UseTableColumnOptions<D extends object>
    extends BasicUseTableColumnOptions<D> {
    Footer?: Renderer<FooterProps<D>>
  }

```
