### ISSUE TITLE
'Select all' Checkbox also selects disabled checkboxes / rows 

### ISSUE THREAD

**Issue by nitishnivedan** [TanStack/react-table#2988]
'Select all' also selects disabled checkboxes / rows 

Expected:  Disabled rows can never be selected, not on checkbox-click, and not with 'select all'

Happening: Disable rows also getting selected

codesandbox link: https://codesandbox.io/s/hopeful-thompson-trs9f?file=/src/MOCK_DATA.json

![image](https://user-images.githubusercontent.com/30456511/104459735-2577ca00-55d3-11eb-943f-c4132c73eac6.png)

**Comment by nitishnivedan** [comment]
you can see the code in the above code sand box link mentioned or else, will below:-

index.js
------------------
const tableInstance = useTable(
    {
      columns,
      getRowId(row) {
        return row.CRPInitiativeID;
      },
      data,
      defaultColumn,
      autoResetPage: false,
       autoResetSortBy: false,
      autoResetSelectedRows: false,
       autoResetFilters: false,
    },
    useFilters,
    useGlobalFilter,
    useGroupBy,
    useSortBy,
    useExpanded,
    usePagination,
    useRowSelect,
    (hooks) => {
      hooks.visibleColumns.push((columns) => [
        {
          id: "selection",
          Header: ({ getToggleAllPageRowsSelectedProps }) => (
            ****<div>
              <Check {...getToggleAllPageRowsSelectedProps()} />
            </div>****
          ),
          Cell: ({ row }) => {
           // console.log(row,'RA');
            return(

            <div>
              <Check {...row.getToggleRowSelectedProps()} disabled={row.original.DisableCheckbox === "1"}
              />
            </div>
          )},
        },
        ...columns,
      ]);
    }
  );

  ----------
Check.js (Check component)

import React from "react";

export const Check = React.forwardRef(({ indeterminate, ...rest }, ref) => {
  const defaultRef = React.useRef();
  const resolvedRef = ref || defaultRef;

  React.useEffect(() => {
    resolvedRef.current.indeterminate = indeterminate;
  }, [resolvedRef, indeterminate]);

  return (
    <>
      <input type="checkbox" ref={resolvedRef} {...rest} />
    </>
  );
});

---------------

**Comment by linxianxi** [comment]
same problem.any idea?

**Comment by martijnhalekor** [comment]
Same problem! How can I exclude certain rows conditionally when using a 'Select All' checkbox in the header row?

**Comment by liranh85** [comment]
Facing exactly the same problem. I thought I had found a workaround, but it turned out to only work UI-wise, not selection-state-wise

```js
const columns = [
	{
		accessor: 'foo',
		Header(props) {
			// This is the relevant part: I tried to change `row.isSelected` based on some condition
			// It worked in the sense that the rows satisfying my condition did not get selected in the UI,
			// But the selection state did not actually change
			props.page.forEach(row => {
				if (someCondition) {
					row.isSelected = false
				}
			})

			const checkboxProps = props.getToggleAllRowsSelectedProps()
			return (
				<Grid container alignItems="center">
					<Grid item>
						<Checkbox
							color="primary"
							{...checkboxProps}
							onClick={e => {
								e.stopPropagation()
							}}
						/>
					</Grid>
					<Grid item>Foo</Grid>
				</Grid>
			)
		},
	},
	// ...
],
```

**Comment by PhilipAB** [comment]
I figured out a solution! I worked with Typescript and without pagination, but I try to explain briefly how I solved this problem so that you can adapt the solution to your scenarios.

Usually our header looks something like this:
```
Header: ({ getToggleAllRowsSelectedProps }) => {
	return (
		<div>
			<CheckBox {...getToggleAllRowsSelectedProps()} />
		</div>
	);
},
```

The problem here is that the getToggleAllRowsSelectedProps() method returns us those props that select all rows, regardless of their properties.  
To fix this, we need to define our own props and pass them to the checkbox.

If only a few props need to be reassigned, it could be done as follows:
```
Header: ({ getToggleAllRowsSelectedProps }) => {
	const { onChange, title, ...propsWithoutOnChangeAndTitle } = getToggleAllRowsSelectedProps();
	const overridenOnChange = (event: React.ChangeEvent<Element>) => {
		// Implement new onChange behaviour for your "header" checkbox here!
	};
	const newTitle: string = "Your new title!";
	const newProps = { onChange: overridenOnChange, title: newTitle };
	return (
		<div>
			<CheckBox {...{ ...newProps, ...propsWithoutOnChangeAndTitle }} />
		</div>
	);
},
```

Implementing the behaviour above, the "header" checkbox now should not change if you click on it. Moreover while hovering over it you should see a textbox displaying "Your new title!".

Let's implement the default behaviour by defining all props by ourselves:
```
Header: ({ getToggleAllRowsSelectedProps, toggleRowSelected, isAllRowsSelected, selectedFlatRows, rows }) => {
	const { onChange, title, ...propsWithoutOnChangeAndTitle } = getToggleAllRowsSelectedProps();
	const overridenOnChange = (event: React.ChangeEvent<HTMLInputElement>) => {
		// Toggle all checkboxes to selected/unselected depending on whether the header checkbox is checked or not. 
		rows.forEach(row => {
			toggleRowSelected(row.id, event.currentTarget.checked);
		});
	};
	const style = {
		cursor: 'pointer',
	}; // Cursor should be set to pointer while hovering over checkbox
	const checked: boolean = isAllRowsSelected; // header checkbox is only checked if all rows are checked
	const indeterminate: boolean = !isAllRowsSelected && selectedFlatRows.length > 0; // if some but not all rows are checked, header checkbox is indeterminate
	const newTitle: string = "Your new title!"; // your title 
	const newProps = { onChange: overridenOnChange, style: style, checked: checked, indeterminate: indeterminate, title: newTitle };
	return (
		<div>
			<CheckBox {...newProps} />
		</div>
    );
},
```

Now we can adapt the props and change them to our needs. Here is the example of how I prevented the selection of disabled checkboxes in my case:
```
Header: ({ toggleRowSelected, rows, selectedFlatRows }) => {
	const style = {
		cursor: 'pointer',
	};
	const checked: boolean = rows.length > 1 && rows.length - selectedFlatRows.length === 1; // In my case: If all but one rows are selected -> all selectable rows are selected and header checkbox should be checked
	const title: string = 'Toggle All Rows Selected'; 
	const indeterminate: boolean = !checked && selectedFlatRows.length > 0; // If my header checkbox is not checked (therefore not all rows are selected) but some rows are selected -> header checkbox is indeterminate
	const disabled: boolean = rows.length === 1; // In my case: If only one row exists, it is a row with a disabled checkbox. Hence, we can disable the header checkbox because it can and should not modify the row's selection.
	const overiddenOnChange = (event: React.ChangeEvent<HTMLInputElement>) => {
		rows.forEach(row => {
			// The condition whether a row is selectable or not
			if (isJwtPayloadWithExp(payload) && row.original.id !== payload.userId) {
				toggleRowSelected(row.id, event.currentTarget.checked);
			}
		});
	};
	const modifiedToggleAllRowsProps = {
		onChange: overiddenOnChange,
		style: style,
		checked: checked,
		title: title,
		indeterminate: indeterminate,
		disabled: disabled
	};
	return (
		<div>
			<CheckBox {...modifiedToggleAllRowsProps} />
		</div>
	);
},
```

Note: The implementation details on [this page](https://github.com/tannerlinsley/react-table/blob/8ec25cabccf915991ec00cf67bfb26a83aa0c0b2/src/plugin-hooks/useRowSelect.js) helped me a lot in developing the solution.

**Comment by liranh85** [comment]
@PhilipAB that was exactly what I needed, thank you very much for sharing this awesome step-by-step guide 🙏🏼 

In my case, I needed this to work with pagination and with Select Page / Select All (as opposed to only Select All).

Here is how I adapted Philip's solution to my needs:

```js
const columns = [
	{
		accessor: 'foo',
		Header(props) {
			// For conditional select: Filter the rows based on your business logic, e.g:
			const isRowSelectable = (row) =>
				row.original.someData !== 'some value'
			const areAllSelectableRowsSelected = (rows) =>
				rows.filter(isRowSelectable).every(row => row.isSelected)
			// Standard: Here we define the logic for the next click (Select Page / Select All)
			const isSelectPage = props.page
				.filter(isRowSelectable)
				// Standard: `isSelectPage === true` if some of the rows are not yet selected
				// This (standard) logic might be confusing to understand at first, but - as a side note - the idea is as follows:
				// This is the variable that defines whether the props that will be received FOR THE NEXT CLICK will be for Select Page or for Select All
				// Try to play this out in your head:
				//  - Initially, none of the rows are selected, so when we clicking the button initially, we will select only the (selectable) rows on the page (i.e. Select Page), hence the next click will be for Select All, hence `isSelectPage` will be `false`
				//  - When clicking again, we will select the rest of the (selectable) rows (i.e. Select All). The next click will again be Select All (for de-selecting all), hence `isSelectPage` will be `false`
				//  - Finally, when clicking again, we will de-select all rows. The next click will be for Select Page, hence `isSelectPage` will `true`
				.some(row => !row.isSelected)
			console.log({ isSelectPage })
			// Standard: Get the props based on Select Page / Select All, but omit the standard `onChange` callback function, so we can override it
			const { onChange, ...checkboxProps } = isSelectPage
				? props.getToggleAllPageRowsSelectedProps()
				: props.getToggleAllRowsSelectedProps()

			// This is where the magic happens
			const overridenOnChange = () => {
				// if we're in Select All and all selectable rows are already selected: deselect all rows
				if (!isSelectPage && areAllSelectableRowsSelected(props.rows)) {
					props.rows.forEach(row => {
						props.toggleRowSelected(row.id, false)
					})
				} else {
					// Otherwise:
					// First, define the rows to work with: if we're in Select Page, use `props.page`, otherwise (Select All) use props.rows
					const rows = isSelectPage ? props.page : props.rows
					// Then select every selectable row
					rows.forEach(row => {
						const checked = isRowSelectable(row)
						props.toggleRowSelected(row.id, checked)
					})
				}
			}

			return (
				<Checkbox
					{...checkboxProps}
					onChange={overridenOnChange}
				/>
			)
		},
	// ...
]
```

**Comment by jan-dh** [comment]
@PhilipAB great solution! Was wondering, is there a way to implement this behavior on the row level to add a custom onChange event where I also toggle some extra rows? I have a custom property "level" on a row and have a function that also checked if the next rows are a lower level than the current. Would love to be able to set the children with a lower level as checked as well when I check a row, but no idea how I would target those.

**Comment by giovanniantonaccio** [comment]
@liranh85 thanks!! Your code helped me a lot!

Based on it I tried to simplify things a little bit and will share my results here in case anyone has the same issue.

Instead of passing the cb function to check if the row is disabled on Headers, I passed it as a prop to my Table component. Then, before calling the `prepareRow` function, I assign a new property to inform if the row is disabled or not (it makes more sense to me, since this function belongs to the Row context).
```js
// Add property to inform if row is disabled
const row = Object.assign(originalRow, { isDisabled: !! isRowDisabled && isRowDisabled(originalRow) });
// Prepare the row for display
prepareRow(row);
```

Then, you can use this custom Header for the Toggle All checkbox:
```js
Header: ({ rows }) => {
  // Toggle checkboxes manually to dont toggle disabled cells
  const changeableRows = !isRowDisabled
    ? [...rows]
    : rows.filter((row) => !!isRowDisabled && !isRowDisabled(row));

  const allSelected = changeableRows.every((row) => row.isSelected);
  const allUnselected = changeableRows.every((row) => !row.isSelected);
  
  return (
    <Checkbox
      checked={!allUnselected}
      indeterminate={!allSelected && !allUnselected}
      onChange={() => changeableRows.forEach((row) => row.toggleRowSelected(!allSelected))}
    />
  )
```

**Comment by its-dk-dev** [comment]
> I figured out a solution! I worked with Typescript and without pagination, but I try to explain briefly how I solved this problem so that you can adapt the solution to your scenarios.
> 
> Usually our header looks something like this:
> 
> ```
> Header: ({ getToggleAllRowsSelectedProps }) => {
> 	return (
> 		<div>
> 			<CheckBox {...getToggleAllRowsSelectedProps()} />
> 		</div>
> 	);
> },
> ```
> 
> The problem here is that the getToggleAllRowsSelectedProps() method returns us those props that select all rows, regardless of their properties. To fix this, we need to define our own props and pass them to the checkbox.
> 
> If only a few props need to be reassigned, it could be done as follows:
> 
> ```
> Header: ({ getToggleAllRowsSelectedProps }) => {
> 	const { onChange, title, ...propsWithoutOnChangeAndTitle } = getToggleAllRowsSelectedProps();
> 	const overridenOnChange = (event: React.ChangeEvent<Element>) => {
> 		// Implement new onChange behaviour for your "header" checkbox here!
> 	};
> 	const newTitle: string = "Your new title!";
> 	const newProps = { onChange: overridenOnChange, title: newTitle };
> 	return (
> 		<div>
> 			<CheckBox {...{ ...newProps, ...propsWithoutOnChangeAndTitle }} />
> 		</div>
> 	);
> },
> ```
> 
> Implementing the behaviour above, the "header" checkbox now should not change if you click on it. Moreover while hovering over it you should see a textbox displaying "Your new title!".
> 
> Let's implement the default behaviour by defining all props by ourselves:
> 
> ```
> Header: ({ getToggleAllRowsSelectedProps, toggleRowSelected, isAllRowsSelected, selectedFlatRows, rows }) => {
> 	const { onChange, title, ...propsWithoutOnChangeAndTitle } = getToggleAllRowsSelectedProps();
> 	const overridenOnChange = (event: React.ChangeEvent<HTMLInputElement>) => {
> 		// Toggle all checkboxes to selected/unselected depending on whether the header checkbox is checked or not. 
> 		rows.forEach(row => {
> 			toggleRowSelected(row.id, event.currentTarget.checked);
> 		});
> 	};
> 	const style = {
> 		cursor: 'pointer',
> 	}; // Cursor should be set to pointer while hovering over checkbox
> 	const checked: boolean = isAllRowsSelected; // header checkbox is only checked if all rows are checked
> 	const indeterminate: boolean = !isAllRowsSelected && selectedFlatRows.length > 0; // if some but not all rows are checked, header checkbox is indeterminate
> 	const newTitle: string = "Your new title!"; // your title 
> 	const newProps = { onChange: overridenOnChange, style: style, checked: checked, indeterminate: indeterminate, title: newTitle };
> 	return (
> 		<div>
> 			<CheckBox {...newProps} />
> 		</div>
>     );
> },
> ```
> 
> Now we can adapt the props and change them to our needs. Here is the example of how I prevented the selection of disabled checkboxes in my case:
> 
> ```
> Header: ({ toggleRowSelected, rows, selectedFlatRows }) => {
> 	const style = {
> 		cursor: 'pointer',
> 	};
> 	const checked: boolean = rows.length > 1 && rows.length - selectedFlatRows.length === 1; // In my case: If all but one rows are selected -> all selectable rows are selected and header checkbox should be checked
> 	const title: string = 'Toggle All Rows Selected'; 
> 	const indeterminate: boolean = !checked && selectedFlatRows.length > 0; // If my header checkbox is not checked (therefore not all rows are selected) but some rows are selected -> header checkbox is indeterminate
> 	const disabled: boolean = rows.length === 1; // In my case: If only one row exists, it is a row with a disabled checkbox. Hence, we can disable the header checkbox because it can and should not modify the row's selection.
> 	const overiddenOnChange = (event: React.ChangeEvent<HTMLInputElement>) => {
> 		rows.forEach(row => {
> 			// The condition whether a row is selectable or not
> 			if (isJwtPayloadWithExp(payload) && row.original.id !== payload.userId) {
> 				toggleRowSelected(row.id, event.currentTarget.checked);
> 			}
> 		});
> 	};
> 	const modifiedToggleAllRowsProps = {
> 		onChange: overiddenOnChange,
> 		style: style,
> 		checked: checked,
> 		title: title,
> 		indeterminate: indeterminate,
> 		disabled: disabled
> 	};
> 	return (
> 		<div>
> 			<CheckBox {...modifiedToggleAllRowsProps} />
> 		</div>
> 	);
> },
> ```
> 
> Note: The implementation details on [this page](https://github.com/tannerlinsley/react-table/blob/8ec25cabccf915991ec00cf67bfb26a83aa0c0b2/src/plugin-hooks/useRowSelect.js) helped me a lot in developing the solution.

thanks! This solution is working for me.

**Comment by nerdyman** [comment]
For anyone still runnning into this, you can force the checkbox to be unchecked by conditionally applying `checked={false}` to it when it's disabled.

Using the checkbox example from the v7 docs:

```jsx
const IndeterminateCheckbox = React.forwardRef(
  ({ indeterminate, ...rest }, ref) => {
    const defaultRef = React.useRef();
    const resolvedRef = ref || defaultRef;

    React.useEffect(() => {
      resolvedRef.current.indeterminate = indeterminate;
    }, [resolvedRef, indeterminate]);

    React.useEffect(() => {
      resolvedRef.current.addEventListener("change", (ev) => {
        ev.preventDefault();
        ev.stopPropagation();
      });
    }, []);

    const optionalProps = {};

    if (rest?.disabled) {
      optionalProps.checked = false;
    }

    return (
      <input type="checkbox" ref={resolvedRef} {...rest} {...optionalProps} />
    );
  }
);
```

https://codesandbox.io/s/jovial-bohr-k55rdg?file=/src/App.js:618-1293

**Comment by KevinVandy** [comment]
In Table v8, you do `enableRowSelection: (row) => /*condition*/`

Then the select all functions will skip selecting rows where row selection is not enabled.

**Comment by YUNHANKYU** [comment]
This is my solution. I'd just want to share my code with someone who's struggling with similar issues as me.

**Problems**
1. I wanted the 'select all' function to run except for the disabled checkboxes.
2. Also, I wanted it to run on the rows of the current page, not all rows in the table.

**Code**
I solved the problem like this. I hope it will be helpful.

```
Header: ({ page }) => {
  const isRowDisabled = page.filter((row) => /*condition*/ ).length !== 0;

  const changeableRows = !isRowDisabled
    ? [...page]
    : page.filter((row) => ! /*condition*/ ); // don't forget '!' before condition

  const allSelected = changeableRows.every((row) => row.isSelected);
  const allUnselected = changeableRows.every((row) => !row.isSelected);

  const modifiedToggleAllRowsProps = {
    checked: !allUnselected,
    indeterminate: !allSelected && !allUnselected,
    onChange: () =>
      changeableRows.forEach((row) =>
        row.toggleRowSelected(!allSelected)
      ),
  };

  return (
    <div>
      <CheckBox {...modifiedToggleAllRowsProps} />
    </div>
  );
},
```

**Comment by with-key** [comment]
```tsx
  enableRowSelection: (row) => {
    return row.original.address('korea') ? false : true; // conditional
  },
```
