### ISSUE TITLE
Weird Bug related to production build - when expanding feature is used - development build working fine

### ISSUE THREAD

**Issue by KunalAtDure** [TanStack/react-table#2997]
**I am using Expanding feature which works perfectly on development but crashes on production**

**Versions used**
"react": "^16.14.0",
"react-table": "^7.6.3"

**Browser console has below error for production**
Error: Minified React error #152; visit https://reactjs.org/docs/error-decoder.html?invariant=152&args[]=Cell for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
<img width="1440" alt="Screenshot 2021-01-20 at 2 25 39 AM" src="https://user-images.githubusercontent.com/10560176/105092088-ccbe9a80-5ac6-11eb-8e0a-c3464094754c.png">

**Comment by GhassenRjab** [comment]
@KunalAtDure What did you do to fix this?

BTW I have this issue with react-table@8.7.3. It happens when I toggle column visibility (I based my development on this example).

Everything works fine on development but on production I have the issue.
