### ISSUE TITLE
react-dom@17.x + `useSortBy` bug

### ISSUE THREAD

**Issue by linde12** [TanStack/react-table#3002]
**Describe the bug (required)**
As i was developing i forgot to memoize some mocked data and encountered an interesting bug, which led me down a rabbit hole instead of actually seeing the problem (missed useMemo on my data)

It only happens when you use `useTable` combined with `useSortBy`, and only with `react-dom@17.x` (event delegation rewrite release), e.g `react-dom@16.x` works fine.

It is hard to put to words, but i have attached a minimal example (codesandbox) and will try my best to explain. In the codesandbox i have three components:
- `Modal` which has a `useEffect`  that adds a click event listener to `document`. This listener acts like a backdrop (where if i click the backdrop the "modal" should close. Rendered by App.
- `Table` which is the component that calls `useTable` (but doesn't use anything it returns) - also rendered by App.
- `App` which is the main application and controls the state that decides whether `Modal` is rendered or not. Here i actively "forgot" to use `useMemo` on my data.

What happens is that when you click "Open Modal" using `react-dom@17.x` the callback to `document.addEventListener('click', ..)` is called, but this element shouldn't have been rendered yet at the point when the click event from the button was fired. The result is that you never, or very briefly, see the "modal". Doing the same using `react-dom@16.x` (you can change in the sandbox) results in the expected behavior of the "modal" actually showing.

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/react-table-react-17-5nw4d?file=/src/App.js

**Steps To Reproduce (required)**

1. Go to https://codesandbox.io/s/react-table-react-17-5nw4d?file=/src/App.js
2. See `react-dom` version is `17.0.1`
3. Press "Open Modal" button
4. Nothing happens
5. Change version of `react-dom` to 16.14.0 for example.
6. Press "Open Modal" button
7. See the modal get opened as expected.

**Expected behavior (Recommended)**
Even if i missed `useMemo` on my data, i would expect my components to render properly. I get that i can't expect everything to be as performant, or even work properly, but i would not expect it to have the weird observed behavior. I also would not expect it to have different behaviors across `react-dom` versions.

**Additional context**
I am fully aware that i didn't use the library properly by not memoizing my data first, but the behavior is very confusing and misleading. Also, i am _very_ curious to what is actually going on and whether this is a bug of `react-dom` or `react-table` or a combination of both. I've been debugging to try and find the root cause, but unfortunately i'm not very familiar with the code and i believe there are things happening asynchronously which is very hard for me to follow.

**Comment by linde12** [comment]
Update: This also seems to happen when i pass `useFilters` instead of `useSortBy`, so maybe it's not actually related to the "plugin" itself, but rather what happens when a plugin is added.

**Comment by aannaassalam** [comment]
Yes, I am also facing the same issue and dont know if there's a solution to it...
Have you fixed it @linde12 ??

**Comment by linde12** [comment]
> Yes, I am also facing the same issue and dont know if there's a solution to it...
> Have you fixed it @linde12 ??

Unfortunately not, feel free to read/react/comment on the related issue i made in the react repo. There were some breaking changes to the way rendering works in react 17 but it seems to be a very niche issue because no one has cared to look further into it. You can see my findings and a workaround (stopPropagation) in the fb issue.

**Comment by aannaassalam** [comment]
> > Yes, I am also facing the same issue and dont know if there's a solution to it...
> > Have you fixed it @linde12 ??
> 
> Unfortunately not, feel free to read/react/comment on the related issue i made in the react repo. There were some breaking changes to the way rendering works in react 17 but it seems to be a very niche issue because no one has cared to look further into it. You can see my findings and a workaround (stopPropagation) in the fb issue.

yeah sure! so this means there's no progress in this after all
