### ISSUE TITLE
Invalid `isAllRowsExpanded` behaviour at start, when all rows expanded

### ISSUE THREAD

**Issue by turansky** [TanStack/react-table#3008]
**Describe the bug (required)**
Invalid `isAllRowsExpanded` behaviour
`isAllRowsExpanded` is false, even when all rows is really expanded

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/blue-wood-nk3y2

**Steps To Reproduce (required)**

1. Open example
2. Check `All rows expanded` value

**Expected behavior (Recommended)**
2. `All rows expanded` value is `true`

**Screenshots**
<img width="331" alt="Screen Shot 2021-01-22 at 9 59 24 PM" src="https://user-images.githubusercontent.com/9942723/105533574-5f487f00-5cfd-11eb-8ed9-1ab7e851a7f7.png">

**Desktop (please complete the following information):**

- OS: macOS
- Browser: chrome
- Version: 88.0.4324.96

**Additional context**
Is there option to expand all rows at start without manual `expanded` calculation?

**Comment by turansky** [comment]
@tannerlinsley FYI - codesandbox template link, declared in issue template, is invalid

**Comment by d-mather** [comment]
I'm also experiencing this issue (even without StrictMode). Is there any update to this being fixed?

**Comment by Bromilow** [comment]
is there any update on this issue?

**Comment by johnbarhorst** [comment]
Similar issues for me. It will expand all rows on initial click, but will not collapse all rows. If I close a few rows individually, and then click again, it will expand all the rows, but still won't collapse all.
Also, if I open a few rows first, then click the open/close all button, it will close the few I've opened. Click again, it will open all rows, but then still will not close all rows.

**Comment by stuthib** [comment]
Hey folks. I have a deeply nested table. Clicking on each row works fine. But expand all is not rendering rows from depth 2 onwards. Any idea if expand all supports deep nesting of rows? Thank you.

**Comment by turansky** [comment]
> Any idea if expand all supports deep nesting of rows?

My WA - fill `initialState.expanded` on data changes

**Comment by stuthib** [comment]
I was able to narrow down the issue. It seems like the issue is with my data. I am recursively making API calls and fetching the subRows. Passing this data to the table, and it does not render the subRows. When I hard code the data, it seems to render. Not sure what is wrong here.
