### ISSUE TITLE
Uncaught TypeError: Cannot read property 'includes' of null  at filterTypes.js:45

### ISSUE THREAD

**Issue by aruprakshit** [TanStack/react-table#3020]
**Describe the bug (required)**
When any column has null value, filter `includes` throws error.

```sh
filterTypes.js:45 Uncaught TypeError: Cannot read property 'includes' of null
    at filterTypes.js:45
    at Array.some (<anonymous>)
    at filterTypes.js:43
    at Array.filter (<anonymous>)
    at ge (filterTypes.js:42)
    at useFilters.js:225
    at Array.reduce (<anonymous>)
    at n (useFilters.js:197)
    at useFilters.js:194
    at Object.pi [as useMemo] (react-dom.production.min.js:162)
```

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/sharp-burnell-89sif?file=/src/App.js

**Steps To Reproduce (required)**

1. Go to first name search box
2. type some character
3. Scroll down to browser console you will see above mentioned uncaught error.

**Expected behavior (Recommended)**
It shouldn't break the code, should ignore rows having null values.

**Desktop (please complete the following information):**

- OS: Osx
- Browser chrome
- Version latest

**Comment by aruprakshit** [comment]
I added a PR for a possible fix of this https://github.com/tannerlinsley/react-table/pull/3021 .

**Comment by Keshavdulal** [comment]
While we wait for PR to be merged, a temporary/workaround solution around this could be overriding the Cell Render function in the table's columns configuration as
`
{
  accessor: 'id',
  Header: 'ID',
  Cell: instance => instance?.cell?.value || '',
},
`
I did check the data that I was feeding to the table and some of them were null and was causing the filters to break.
This allows me to handle null data in the table while having various Column filters from repo's example section.
Also, I don't have a lot of data on my table right now, say less than 100 cells.

**Comment by sicarius97** [comment]
@Keshavdulal, @fseitun, @aruprakshit did this fix ever get merged to resolve the issue? Still seem to be running into the problem currently and need either a fix or some sort of workaround

**Comment by Keshavdulal** [comment]
It doesn't look it has been merged yet.
It's still on the "Needs Triage" column of the projects' kanban board.
I somehow managed to work with the workaround I mentioned above and haven't really worked much with react-table since last year.

**Comment by WillGoad** [comment]
https://github.com/TanStack/react-table/blob/v7/examples/filtering/src/App.js

Workaround is to make a custom includes function by copying the custom ‘filterGreaterThan’ filter in the docs changing >= to ===
