### ISSUE TITLE
React build shows empty rows

### ISSUE THREAD

**Issue by vinayakshahdeo** [TanStack/react-table#3027]
**Describe the bug (required)**

This is a very strange issue but I was using react-table 7.0.0.rc16 and I recently upgraded to react-table 7.0.1 the problem is my data works in dev mode but as soon I create a react build it wont render anything I would like to know why and I am attaching my package.json in sandbox link for the same.

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/quizzical-paper-hmzxh?file=/src/App.js to reproduce the issue.

**Steps To Reproduce (required)**
whenever the build is deployed it renders an empty table

**Expected behavior (Recommended)**
table should render with data

**Desktop (please complete the following information):**

- OS: [ubuntu 16.04]
- Browser [mozilla]
- Version [84.0.2]

**Additional context**
here is a link to the deployed code https://csb-hmzxh-ap5fj53r4.vercel.app/

**Comment by AxelThomsonEk** [comment]
@vinayakshahdeo did you work out a fix for this in the end? I am experiencing the same issue on version 7.6.3 (Chrome)

**Comment by nuno-ferrao** [comment]
Hi guys, I am experiencing the same problem. Locally my react table works fine, but when I use it on a build version, the rows come out empty. After spending 1 week working on a dynamic table and ready to present it to my client, I moved it to build only to see that no row was showing up, despite all the functionality (filters, etc) working as displayed by the row count attribute.

**Comment by horppe** [comment]
I am also facing this issue. Both the Header and Cells are empty when i build for production but everything works fine in dev mode. Can someone pls help out?

**Comment by kamskr** [comment]
I was also facing this issue with version 7.7.0. It worked perfect locally, but in production build I couldn't see anything. Downgrading to 7.0.2 helped.

**Comment by vinayakshahdeo** [comment]
I had to downgrade too
