### ISSUE TITLE
react-table v7. The column filter input appears when maintaining the global filter value in the select header

### ISSUE THREAD

**Issue by didoshakra** [TanStack/react-table#3057]
react-table v7.
I want to use react-table in my future projects written with Next.js. I'm trying to create a table that has sorting, fottert, filtering, row-selected, paginations and fixed head and footer. Based on the examples https://react-table.tanstack.com/docs/api/useFilters,
 I have already created a table that has sorting, fottert, filtering, row-selected. But here I have a not very important nuance that I can not overcome. When maintaining the value of the global filter in the select header appears filter input by columns. It seems that somewhere it gives properties canFilter: true. I can overcome it.
 Maybe you need to add another condition to the code: <div> {column.canFilter? column.render ("Filter"): null} </div>
![image](https://user-images.githubusercontent.com/20404838/107507114-c6907b00-6ba7-11eb-90e2-667a78bc0851.png)
![image](https://user-images.githubusercontent.com/20404838/107507166-d8721e00-6ba7-11eb-8e37-1c04204c10e3.png)

**Comment by MA-MacDonald** [comment]
Yes it appears typing in the global filter is changing the canFilter prop to true on disabled columns. Is this a bug or just something I'm not understanding in the docs?
