### ISSUE TITLE
`isAllRowsExpanded` incorrect state when running in strict mode

### ISSUE THREAD

**Issue by adamb70** [TanStack/react-table#3061]
When using `React.StricttMode` you are unable to collapse all rows using the "expand/collapse all" button after expanding them. This can be seen in the React Table "Expanding" official example just by running the app in strict mode.

https://codesandbox.io/s/exciting-bartik-hrbeu?file=/src/index.js

1. Expand all rows
2. Try to collapse all rows

This is possibly related to #3008, however I am only seeing this behaviour in strict mode.

**Comment by blovato** [comment]
I am also encountering this issue! However, I am not running my table in Strict Mode so it might be a more general bug with this expand all logic.
I've disabled this button for now, but I'd love to be able to use it as soon as possible.

**Comment by dumbbell** [comment]
I confirm this behavior. Disabling strict mode works around the problem.

**Comment by d-mather** [comment]
I'm also experiencing this issue (even without StrictMode). Is there any update to this being fixed?

**Comment by Bromilow** [comment]
has there been any progress on this issue?

**Comment by twjackysu** [comment]
I have the same problem
