### ISSUE TITLE
Use drag-drop row with pagination

### ISSUE THREAD

**Issue by enes-get-local** [TanStack/react-table#3069]
I need to use row drag-drop and pagination together. But when i add drag-drop props pagination don't work.
There is any way to use both of these ?

Example Here
[https://stackblitz.com/edit/react-ts-uthr9y?file=index.tsx](https://stackblitz.com/edit/react-ts-uthr9y?file=index.tsx)

React-table version : 7.6.3

**Comment by maolivieri** [comment]
I have the exact same question. Appreciate if anyone could help.

**Comment by enes-get-local** [comment]
> I have the exact same question. Appreciate if anyone could help.

I've found a way to do that. My problem was pagination resetting all data when drag and drop any row. İf you share example demo i can help

**Comment by maolivieri** [comment]
> > I have the exact same question. Appreciate if anyone could help.
> 
> I've found a way to do that. My problem was pagination resetting all data when drag and drop any row. İf you share example demo i can help

Thanks,
I got it now.

**Comment by maolivieri** [comment]
If anyone else has this problem.. you can stop the table from resetting as shown below.

......useTable(
    {
      data: records,
      columns,
      getRowId,
      initialState: { pageSize: defaultPageSize ? defaultPageSize : 5 },
      **autoResetPage: false,**
    },.......
