### ISSUE TITLE
react-table crashes using manualPagination, useRowSelect, and toggleRowSelected

### ISSUE THREAD

**Issue by anjunatl** [TanStack/react-table#3071]
## Describe the bug (required)

When using react-table with row selection & server-side pagination configured, `toggleAllRowsSelected(false)` only affects visible rows and `toggleRowSelected(rowId, false)` crashes the page with the following error when it is called on a row that is no longer visible: `Uncaught TypeError: Cannot read property 'isGrouped' of undefined` at [`handleRowById` in `useRowSelect.js` on line 157.](https://github.com/tannerlinsley/react-table/blob/master/src/plugin-hooks/useRowSelect.js#L157)  

## Provide an example

Since this is a complicated bug (using server-side pagination, row selection, and batch row action behavior that resets the selected rows on completion) I've created a docker-based test environment to demonstrate the issue: 

https://github.com/anjunatl/react-table-bug-repro/ 

[Here's the usage of `react-table` in context.](https://github.com/anjunatl/react-table-bug-repro/blob/main/demo/laravel/resources/js/DemoGrid.jsx) [And here are more files of note for the example if it helps](https://github.com/anjunatl/react-table-bug-repro/#example-source-highlights)

I have a fix for this to enable `toggleRowSelected` to work on invisible rows without crashing, but I'm not sure if it both fully fixes the problem and does not also cause more trouble in concert with other plugin hooks - 
https://github.com/anjunatl/react-table-bug-repro#potential-fix 

### toggleAllRowSelected - not all rows get cleared

1. Clone the reproduction repo & run `docker-compose up` to start the example
2. Choose one to many rows on the first page
3. Change to another page
4. Choose another one to many rows
5. Click the "Do something" button

#### Expected behavior

The selected row counter should reset to 0.

#### Actual behavior

The selected row counter is not 0 & is the sum of selected rows on non-visible pages

### toggleRowSelected - crashes

1. Clone the reproduction repo & run `docker-compose up` to start the example
2. Click the "Mode" button to change it from "All" to "Row" to enable use of `toggleRowSelected`
3. Choose one to many rows on the first page
4. Change to another page
5. Choose another one to many rows
6. Click the "Do something" button

#### Expected behavior

The selected row counter should reset to 0.

#### Actual behavior

The page crashes

## Screenshots

[video screenshot](https://user-images.githubusercontent.com/157208/108133591-d2d27780-7082-11eb-85ca-64950c90694a.mp4)

## Desktop (please complete the following information):

- OS: Mac Big Sur
- Browser: Chrome & Firefox
- Version: Latest

# Thank you for the awesome library! 🙏

**Comment by anjunatl** [comment]
[I tried reproducing this in codesandbox by adding row selection to the controlled pagination example](https://codesandbox.io/s/react-tablecontrolled-pagination-row-selection-loses-state-8yd2x) - This version doesn't behave like my original example because my example tracks selected row IDs externally & this example uses the table's state. 

The [pagination + row selection codesandbox example](https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/row-selection-and-pagination?file=/src/App.js) can keep row selection state across page changes but when using controlled pagination the selection state is lost each time the page is changed.

**Comment by hst-pierre** [comment]
This bug also prevent manually pre-selecting all rows of all pages when controlling the selection externally since there is no way to update `selectedRowIds` after it has been sent to the initial state and as already mentioned all toggle methods are for the current page only (or more precisely on known data).
