### ISSUE TITLE
Special characters (square brackets) cause a bug in the accessor

### ISSUE THREAD

**Issue by anna-kol** [TanStack/react-table#3087]
**Describe the bug (required)**
When the accessor of the column has square brackets - [] 
The data that i receive from useTable has undefined in this column. (Even though i sent a value)
Is this a bug or a wanted behavior? I didn't find anything in the documentation, are there any more special chars i should filter?

**Provide an example via Codesandbox! (required)**
Example :
https://codesandbox.io/s/white-snowflake-5e5h3?file=/src/App.js

**Steps To Reproduce (required)**

1. create a column with an accessor that has square brackets for example "age [bla]"
2. make sure you return a value with same accessor in the data
3. look at the "rows" object returned from useTable 
4. rows[0].values["age [bla]"] is undefined while rows[0].values["visits !@#$%^&*()"] has a value

**Expected behavior (Recommended)**
rows[0].values["age [bla]"] should return the value i sent, or add to the docs the characters we are not allowed to use in the accessor

**Desktop (please complete the following information):**
- OS: IOS
- Browser: chrome
- Version: Version 88.0.4324.146 (Official Build) (x86_64)

**Comment by mcmcphillips** [comment]
This issue with the accessors failing to access the columns also occurs when there is a "." character.

**Comment by tnrich** [comment]
Related to https://github.com/tannerlinsley/react-table/issues/3094

**Comment by janabal123** [comment]
I am facing this same issue as well. What does the function evaluate to in your suggested work around? I mean what would be actual value that gets assigned to the accessor with your work around? Thanks.
