### ISSUE TITLE
included sort types don't make sense

### ISSUE THREAD

**Issue by ianstormtaylor** [TanStack/react-table#3093]
**Describe the bug**
The included sorting types don't make sense because they don't handle the most common use cases...

The `alphanumeric` default doesn't work with floats, which are extremely common in tables. It also doesn't use case insensitive matching for strings, which is the most common need if you have values that aren't all of the same case. (For values that are already all of the same case the default doesn't matter, so it's best to use case insensitive anyways.)

Right now the options for getting proper sorting are not good. You either have to define your own `sortType` on each and every column, or define it somewhere else and remember to pass it in to every `useTable` definition. For edge cases this makes sense, but for the most common data types it doesn't.

**Expected behavior**
I think the included sort types should be expanded slightly and made more clear:

- `default` would be the current magic-but-hard-to-understand default (to not break backwards compat).
- `string` would be a case-insensitive sort for string values.
- `number` would be an integer, float, or currency-supporting sort for numeric values.
- `date` would the same as the current `datetime`.

It would make it very simple to choose a specific type because you'd know exactly what you were getting. And it would accurately solve 90% of the use cases.

**Comment by caravinci** [comment]
This is a good feature request, at risk of falling through the cracks... 

@fseitun podés abrirlo de nuevo, por favor?

**Comment by fseitun** [comment]
Ha, how did you know I speak Spanish?
I'll re open, but I'm no longer maintaining though

**Comment by caravinci** [comment]
Thank you! @ianstormtaylor opened this a while ago and I've been keeping an eye on it.
Maybe you can point us towards the right maintainer to discuss contributing a PR?

Y supuse que sabés castellano por tu nombre y ubicación en el perfil de usuario.
Me pareció buena oportunidad para practicar el mío 🤝

**Comment by tannerlinsley** [comment]
I think you'll all appreciate the new sortTypes in v8: https://github.com/TanStack/react-table/blob/alpha/packages/table-core/src/sortTypes.ts

**Comment by tannerlinsley** [comment]
Implementing these changes in v7 would be breaking. So if you want to fork v7, take these sortingFns and implement them in your fork, that would probably work. Otherwise, I would consider this "fixed" or implemented in v8.

**Comment by caravinci** [comment]
Great turn-around, @tannerlinsley! thanks for sharing that link. 
Just checked the code and I'm excited to try that version! (which I was obviously not aware was in the pipeline already.)

In the project I'm currently working on, I'm migrating from v6 to v7... that's why I'm interested in the sorting.
While I realise it's still in `Alpha` stage, maybe I'll give this new version a try instead.
Not only may the TS introspection come in handy, but it could hopefully help testing.

This package kicks names... thanks for all the hard work!

**Comment by tannerlinsley** [comment]
Thanks for using it! Join the discord! https://tlinz.com/discord. We have a dedicated v8 channel.
