### ISSUE TITLE
strange select behavior when using useExpanded and useRowSelect

### ISSUE THREAD

**Issue by adsee42** [TanStack/react-table#3106]
**Describe the bug (required)**
See the screenshot below

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/nervous-shaw-fqy2x

**Steps To Reproduce (required)**

1. Expand the only top level row
2. Select all its children
3. See error

**Expected behavior (Recommended)**
The "select all" checkbox is expected to be selected.

**Screenshots**
![image](https://user-images.githubusercontent.com/54787881/109266712-bd600900-784b-11eb-9390-c25dadef787f.png)

**Comment by dnquang1996vn** [comment]
The issue is like that:
**Steps To Reproduce (required)**
- select a parent row => all the children rows will be selected
- toggle select children rows => the selection of parent row does not change => error
**Expected behavior**
- when toggling children rows, It affects to the selection of parent row also

**Comment by dnquang1996vn** [comment]
the solution for it add 
`
function getAllParentId(id) {
      const array = id.split('.');
      const parents = [];
      while (array && array.length > 1) {
        array.pop();
        parents.push(array.join('.'));
      }
      return parents;
    }`
    
    `    const parentIds = getAllParentId(id);
    if (!shouldExist) {
      parentIds.forEach((i) => delete newSelectedRowIds[i]);
    }`
    
    to the reducer handle `action.type === actions.toggleRowSelected` in hook `useRowSelect`. 
    need to create a PR

**Comment by dnquang1996vn** [comment]
here is the solution https://codesandbox.io/s/nifty-matsumoto-to2sx?file=/src/App.js
need a PR to fix it.
