### ISSUE TITLE
column.setFilter isn't memoized

### ISSUE THREAD

**Issue by PaulCordo** [TanStack/react-table#3129]
**Describe the bug (required)**
`column.setFilter` isn't memoized (and leads to excessive update)

**Provide an example via Codesandbox! (required)**
`API rate limit exceeded for app ID c07a89833b557afc7be2.`   
Providing a MR, fix is quite simple

**Steps To Reproduce (required)**

1. Use useFilter
2. in a filter make use of column.setFilter in a useEffect that calls setFilter on change
3. React should say maximum depth exceeded

**Comment by Zhouzi** [comment]
By the way, this issue was raised some time ago already: #2319 It was closed as the intention was to improve it with v8.

**Comment by tannerlinsley** [comment]
This issue is fixed in v8 and we have a pending PR open to fix it in v7.
