### ISSUE TITLE
Date filtering not working in column filter

### ISSUE THREAD

**Issue by mobi20** [TanStack/react-table#3138]
One of the columns is displaying the date and when I try to filter it using column filter it's not working. How can I filter date using a column filter?

**Comment by imtmh** [comment]
I am facing the same issue, couldn't filter using a date range, I tried all the possible ways.

**Comment by imtmh** [comment]
I got the workaround for this problem. Since the date range filter (between) works only for numbers, convert the date to number (date.getTime()) before passing it as data to the table. Use appropriate formatted when you are rendering it on table. This worked fine for me.
