### ISSUE TITLE
While using controlled pagination and selection `toggleAllRowsSelected` works only for the current page

### ISSUE THREAD

**Issue by emberist** [TanStack/react-table#3142]
**Description**

Using both controlled pagination and selection with the `autoResetSelectedRows: false` and using a custom row identifier using the `getRowId` prop, I want to control the selection in all the pages, for example, from an external button to deselect all the selected items.

The problem is using the `toggleAllRowsSelected(false)` function, doesn't deselect all the elements, but deselect only the element on the currently visible page.

**Example**

Example [here](https://codesandbox.io/s/example-controlled-pagination-n-selection-u4hup)

**Steps To Reproduce**
Steps to reproduce the behaviour:

1. Open the example
2. As you can see there are 2 default items selected, one on the first page and one on the second
3. Go to page one
4. Click the button "Deselect all" (it will execute `toggleAllRowsSelected`)
5. Go to page two, you will see the element with index 18 selected

**Expected behaviour (Recommended)**
I expect the "Deselect all button" to deselect all the items on all pages!

**Desktop**

- OS: MacOS Big Sur 11.2.1
- Browser Chrome
- Version 88.0.4324.192

**Comment by ajkl2533** [comment]
Hi @tannerlinsley, first of all, great talk at the React Summit last week 👍 

I hit the same issue, is there any workaround for deselecting all rows?

**Comment by riccardocaranfil** [comment]
Thanks @ajkl2533, I've noticed from your code the `stateReducer` prop 🤦

**Comment by thisisgurkaran** [comment]
Did anyone find a solution to this problem ??? I am currently facing this.  @[ajkl2533](https://github.com/ajkl2533)

**Comment by ajkl2533** [comment]
Hi @thisisgurkaran I didn't find anything better than dispatching custom action.

**Comment by GiorgioCapaccio** [comment]
Hi all! I'm facing the same issue. 

I have a table with controlled pagination and an external button that handles the rows selection of all pages. The button click triggers the `toggleAllRowsSelected()` but it doesn't work as expected because deselect only the rows of the current visible page.
Exactly like the @emberist example.

**Comment by emberist** [comment]
Hey @GiorgioCapaccio, the [example](https://github.com/TanStack/table/issues/3142#issuecomment-822482864) provided by @ajkl2533 fix the issue!

**Comment by tasos-boxlabs** [comment]
Is there an updated solution that works with Table v8?

**Comment by poofy25** [comment]
I am also facing this issue, anyone got a better solution ?
