### ISSUE TITLE
Sorting is getting applied when focusing on the input field in the table header

### ISSUE THREAD

**Issue by vigneshwaran-natarajan** [TanStack/react-table#3146]
In the table header I'm using both the filter (based on the text entered in the input) & as well as sortBy. When clicking on the input field sorting is getting applied. We focus is moved out & again clicking on the input field sorting is applied. Is there any way to stop the sorting when clicking on the input box?

https://codesandbox.io/s/input-filed-sort-in-the-table-header-forked-twshb?file=/src/App.js to reproduce the issue.

1. Click on the input field available in the header
2. Sorting will be applied when input field in focused

**Expected behavior**
Sorting should not be applied when clicking on the input field.

https://user-images.githubusercontent.com/16484526/111007246-67937100-83b4-11eb-80f6-eb52bb10c0f2.mov

**Comment by mobi20** [comment]
<th {...column.getHeaderProps()}>
<span {...column.getSortByToggleProps()}>


Call the getSortByToggleProps() like this the issue will be solved.
