### ISSUE TITLE
tab issue in react table 7

### ISSUE THREAD

**Issue by nitishnivedan** [TanStack/react-table#3152]
i will tell the scenario, so suppose there are 5 rows.

i am on the first row last column (its a editable textfield), i give some value and press **tab**. it doesnt come to next row (2nd row). 

Expected: On press of tab once, should go to next row
Happening: On press of 2 tabs, it goes to next row.

Note: the row data is edited on blur of the textfield. 
if i edit the row data on change of the text field then it works. on single tab it goes from end of the row to the new row beginning.

**Comment by nitishnivedan** [comment]
and my first column of the react table is checkbox (react table 7) which is managed through react table hooks.

had it been a normal editable dropdown or textfield  for which i would have managed through columns for first column then focus would have been back on tab on last cell tab.

**Comment by nitishnivedan** [comment]
@gargroh @tannerlinsley  - any solution for the above. Will really appreciate

**Comment by gargroh** [comment]
You need to check which item is getting focused on doing the tab, may be there are multiple items between last cell of first row and first cell of second row, also this is unrelated to react-table, as react-table offers to provide your own custom dom.

**Comment by nitishnivedan** [comment]
@gargroh  - no dude, there is no item in between last cell of first row and first cell of second row.  

One thing i can tell, the first cell of 2nd row(i.e.the checbox), if the checbox is disabled then tab works perfectly. On press of tab on last cell of first row, the focus comes to the 2nd row editable field which is expected result.

if checbox(first column of any row) is not disabled then, it taken 2 tabs from the above row to come to new row first column (i.e.checbox), if is not disabled.

----------------------------------------------------------------------------

const tableInstance = useTable(
    {
      columns,
      getRowId(row) {
        return row.CRPInitiativeID;
      },
      data,
      defaultColumn,
      autoResetPage: false,
       autoResetSortBy: false,
      autoResetSelectedRows: false,
       autoResetFilters: false,
    },
    useRowSelect,
    (hooks) => {
      hooks.visibleColumns.push((columns) => [
        {
          id: "selection",
          Header: ({ getToggleAllPageRowsSelectedProps }) => (
            <div>
              <Check {...getToggleAllPageRowsSelectedProps()} />
            </div>
          ),
          Cell: ({ row }) => {
            return(
            <div>
              **<Check {...row.getToggleRowSelectedProps()} disabled={row.original.DisableCheckbox === "1"}**
              />
            </div>
          )},
        },
        ...columns,
      ]);
    }
  );

----------------
Check component 

import React from "react";

 export const Check = React.forwardRef(({ indeterminate, ...rest }, ref) => {
  const defaultRef = React.useRef();
  const resolvedRef = ref || defaultRef;

  React.useEffect(() => {
    resolvedRef.current.indeterminate = indeterminate;
  }, [resolvedRef, indeterminate]);

  return (
    <>
      <input type="checkbox" ref={resolvedRef} {...rest} />
    </>
  )
})

**Comment by nitishnivedan** [comment]
@gargroh - if i maintain my own checkbox in first column, instead of using react table hooks to pass the checkbox to usetable instance for selection feature, then there is no issue in the tab thing
