### ISSUE TITLE
UseControlledState does not remember value

### ISSUE THREAD

**Issue by rossm6** [TanStack/react-table#3161]
**Describe the bug (required)**
Setting the pageIndex for the state does not actually set it.

**Provide an example via Codesandbox! (required)**
Use a new [react-table codesandbox](https://codesandbox.io/s/blissful-fermi-0vn4s?file=/src/App.js) to reproduce the issue.

**Steps To Reproduce (required)**

1. Go to a page above 1.
2. Click on Reset button at the top.
3. Click on the Reset button again to turn off the resetOn state. This causes a re-render and now the page is the original page number greater than 1 you chose at step 1.

**Expected behavior (Recommended)**
It would be best if react-table allowed you to just setState and through this set the pageIndex.  It seems though this isn't possible so I assumed and was hoping that useControlledState would do the same.

**Additional context**
My overall aim is to implement server side filtering.  Possibly I am going about this problem the wrong way although my approach seems straightforward.  On fetching the filtered data from the server I want to reset the pageIndex manually to 0.  When the user uses the pagination buttons, like before filtering, it works based on the last page index being 0.  At the moment I cannot do this because the last pageIndex is the pageIndex before it was set in useControlledState.

If there is another way of implementing this basic requirement in the meantime please advise.

**Comment by ardnahcivar** [comment]
facing similar issue, once passed the updated pageIndex to the useControlledState, the upodated pageIndex is not reflecting , it is still showing the previous value

**Comment by goesbysteve** [comment]
I am seeing the same issue. I'd appreciate it if we can get an official response on this. If it doesn't work that's fine but I don't want to go down a rabbit hole trying to see what I'm doing wrong needlessly.:-)

**Comment by huangbinjie** [comment]
I'm suffering from the same problem. This issue is easy to reproduce if you are using `useControlledState`.
