### ISSUE TITLE
column resize is not optimized and hard to optimize

### ISSUE THREAD

**Issue by gsouf** [TanStack/react-table#3165]
**Describe the bug (required)**

Using useResizeColumns has poor performances

**Provide an example via Codesandbox! (required)**

See example from the documentation https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/column-resizing

**Steps To Reproduce (required)**

1. resize a column
2 observe it being not fluid

It actually triggers render for every single cell for every resize that we do. It is thousands of redners everytime we resize by a few pixels if the table has a few rows. The more rows and columns you have the more the performances degrade.

There is no easy way to optimize it and to prevent unecessary renders for non affected columns.

**Comment by theopak** [comment]
i'm also seeing this problem when i use this library

in my app i've been using a short performance optimization that seems to really help, i just opened a pr to contribute that back here: https://github.com/tannerlinsley/react-table/pull/3231 

i'd appreciate code review from anyone who has time to take a look!

**Comment by gsouf** [comment]
@theopak I quickly looked at the PR without testing it yet. I can see how it can improve the performances and that's probably a great first step. Thank you for this!

With that said I think an optimal solution would be to prevent react to rerender all unmodified cells so often, so like something based around not passing new value for props everytime. I haven't taken time to see how all this work internally, by lack of time, so I don't what is possible though.

**Comment by FezVrasta** [comment]
What really helped to me in the past was to use CSS variables to define the cells sizes. This way you can completely skip the React render phase.

What you do is to define a CSS variable for each column, and then use the CSS variable to set the cell width rather than an actual property.

When you resize the column, only the definition of the CSS variable is updated, and the rest of the table is automatically resized by CSS.

**Comment by gsouf** [comment]
@tannerlinsley Sorry to bug you directly, me and @theopak are eager to help improving this, but as you are at the heart of this project it is hard to get it done without knowing your point of view on the question.

Could you please give us your opinion on this to get a chance to improve this? There was also a pull request proposed
