### ISSUE TITLE
Empty column values when accessor is given a function

### ISSUE THREAD

**Issue by vidyashreen1991** [TanStack/react-table#3173]
When the accessor of the column is a function returning a value. The whole column shows empty values.

**Provide an example via Codesandbox! (required)**
Use a new [react-table codesandbox](https://codesandbox.io/s/m5lxzzpz69) to reproduce the issue.

const data = [
    { "name": "skube", rate: 1000,  score: 0.2 },
    { "name": "jimmy", rate: 2000, score: 0.2 },
    { "name": "xiu", rate: 3000, score: 0.2 }
  ];
  const columns = [
    { Header: "name", accessor: (row)=>{row['name']} },
    { Header: "rate", accessor: "rate" },
    { Header: "score", accessor: "score" }
  ];

Expected behaviour (Recommended)
It should display a column even when accessor is a function

**Comment by NaveenDA** [comment]
Hi @vidyashreen1991 
I guess your codesandbox link is broken, plus I can't able to re-create the issue. Please check out this [codesandbox link](https://codesandbox.io/s/admiring-surf-78uz4)
