### ISSUE TITLE
`disableFilters` maintains filtered state when disabled, `disableGlobalFilters` shows no rows at all when `state.globalFilter` has value before being disabled

### ISSUE THREAD

**Issue by alspdx** [TanStack/react-table#3184]
**Describe the bug (required)**
I've searched existing issues and am fairly confident this is not a duplicate.

The description for [Plugin Hook Order & Consistency](https://react-table.tanstack.com/docs/api/overview#plugin-hook-order--consistency) has this to say about programatically disabling hooks:
> NOTE: In the event that you want to programmatically enable or disable plugin hooks, most of them provide options to disable their functionality, eg. options.disableSortBy

I have a use case where a user may want to change whether a filter is enabled in their interface. We also need to be able to save and recall their preferences from a stored table configuration. If the user has any current active filters for either a column filter or the global filter, disabling either does not behave as expected. 

**Provide an example via Codesandbox! (required)**
I forked the global filter sandbox and added checkboxes to toggle `disableFilters` and `disableGlobalFilter`.
https://codesandbox.io/s/elastic-star-xlk9j

**Steps To Reproduce (required)**

- **Column Filter:**
1. Type a value in any column filter, preferably one that shows a limited set of results
2. Check the "Disable Filters" checkbox
3. Note that the rows are still filtered with the same filter state — I would expect no rows to be filtered out since the filters are disabled

- **Global Filter:**
1. Type a value in the global filter
2. Check the "Disable Global Filter" checkbox
3. Note that _all rows are filtered out_

**Expected behavior (Recommended)**
Disabling filters shouldn't just remove the UI filter inputs, it should also return rows without those filters applied. Maintaining the filter state in the table instance would be good though so filters could be toggled on and off with existing state.

**Desktop (please complete the following information):**

- OS: MacOS v10.15.7
- Browser: Firefox Developer Edition
- Version: 88.0b4

**Comment by RickeyWard** [comment]
I'm seeing this same issue and I agree with your findings. `disableFilter` should disable the filtering, not just set `canFilter` to false.

the docs state that 
`disableFilters: Bool`
  -  Disables filtering for every column in the entire table.

It stands to reason that "disabled" filtering means that the data is no longer being filtered.

The work around I found was to call `tableInstance.setAllFilters([]);` when disabling filters to clear them. Unfortunately there doesn't appear to be a simple way to get the filter values so you can't store them to restore them later.
