### ISSUE TITLE
typeError: data.forEach is not a function

### ISSUE THREAD

**Issue by Fomba-Daouda** [TanStack/react-table#3200]
When i use data from api , i have this error

const data = useMemo(()=>{
          return axios.get(url,{ headers :{
          }})
        .then(res=>res.data) 
    },[])

**Comment by BradBailey-web** [comment]
https://stackoverflow.com/questions/61751728/asynchronous-calls-with-react-usememo
According to SO: 
You should use useState to save your data from an api.

Since this library wants you to memoize your data via useMemo, you could use useMemo on your state after the api call.
```
const [state, setState] = useState();
useEffect(()=>{
  axios.get(url)
    .then(res=>setState(res.data))
},[])
const data = useMemo(()=>state, [state])
```

**Comment by Fomba-Daouda** [comment]
Thank you sir ,
I have another problem.I want to perform manualGlobalFilter so that the
filter is done on the server side.
If you have an example it will be helpful for me .
Thank you.
Regards.

Le dim. 30 mai 2021 à 01:59, BradBailey-web ***@***.***> a
écrit :

**Comment by joeyfigaro** [comment]
Same boat as @Fomba-Daouda – my global filter handler does not get called when using `manualGlobalFilter`. If I set it to false or remove it, the handler is called as expected. Unclear what the expectation for using both is.
