### ISSUE TITLE
TypeError: rowValue.includes is not a function

### ISSUE THREAD

**Issue by sdelabra** [TanStack/react-table#3222]
Anytime I click on a column filter, I get this error. Also, the SelectColumnFilter is not filtering out the null options.

![image](https://user-images.githubusercontent.com/35790409/115453261-06e22a00-a1e5-11eb-8bb2-7a5ac3fe2c4f.png)

**Comment by hardikhere** [comment]
Hey have you inserted html/jsx elemnt in row/col, I was also facing this thinking what I can contribute

**Comment by jonespi** [comment]
This isn't a great fix, but resolved the app from crashing it by using `exactTextCase` instead of `includes`.
