### ISSUE TITLE
Inconsistent sort behavior within grouped subrows after unsort.

### ISSUE THREAD

**Issue by tearingItUp786** [TanStack/react-table#3251]
**Describe the bug (required)**
If you have a table that supports grouping + sorting, the unsorted state of the subrows is different depending on which columns you toggle sorting on. 

**Provide an example via Codesandbox! (required)**
[the example](https://codesandbox.io/s/affectionate-beaver-9w1rq?file=/src/App.js) to reproduce the issue.

**Steps To Reproduce (required)**

1. Go to sandbox
2. Create a mental snapshot of how the subrows are ordered for "test" group.
3. Click on the text inside of the "Last Name" column (be sure not to accidentally toggle grouping) until you have moved from sort ascending, sort descending, unsorted. You should have to click a total of 3 times.
4. See error; the unsorted state of the "test" groups subrow should not match what you saw in step 2. 

**Expected behavior (Recommended)**
The unsorted state of the subrows for a group should be consistent. 

**Screenshots**
Will get these to you if there's any issues with my instructions!

**Desktop (please complete the following information):**

- OS: MacOS Version 10.13.6 (17G14042)
- Browser: Chrome 
- Version 88.0.4324.96 (Official Build) (x86_64)

**Additional context**

**Comment by dgattey** [comment]
Also encountering this problem - after unsorting, this is the state of my `subRows`, 100% reversed from what it starts out as:

![image](https://user-images.githubusercontent.com/982182/143172058-7b61e672-8732-4c59-8fc0-99f707a2cac5.png)
![image](https://user-images.githubusercontent.com/982182/143172081-849b90b6-a786-41ff-b144-5a4d5b7e9fc3.png)

I don't have grouping on, but I have `useGlobalFilter`/`useFilters`/`useSortBy` on
