### ISSUE TITLE
Header row selection not working as expected for table with pagination, groupBy , expansion and row selection 

### ISSUE THREAD

**Issue by tsukhu** [TanStack/react-table#3282]
**Describe the bug (required)**
First of all thank you for this excellent library it has solved all the complex requirements I had. 
There is one issue I have run into 
If we have a paginated table with groupBy and expansion added plus enabled with Row Selection, the parent (Header) toggle for the checkbox is able to select all the rows of the page but no unselect it. 
Also after selection it should show the intermediate state of the table (-) sign on the parent checkbox. However it does not show any indication.

**Reproduction of the issue in codesandbox**
Here is the codesandbox [react-table codesandbox](https://codesandbox.io/s/rt-grp-pg-sel-6kwb7) to reproduce the issue.

**Steps To Reproduce (required)**

1. Go to the above mentions sandbox
2. Group it by one of the columns "First Name"
2. Click on the parent checkbox to mark all the rows in the page
3. There will be no display of state in the parent checkbox (selection)
4. Now try to uncheck the parent checkbox , it does not work
5. If there are no grouped columns it works fine.

**Expected behavior (Recommended)**

**Screenshots**
1) When go grouping is selected the parent check box works and shows the (-) on selecting one row
![RT_works_1](https://user-images.githubusercontent.com/846306/118921056-1de77980-b955-11eb-892b-6813de526afa.PNG)
2) Within the grouped and expanded row it works as expected
![RT_works_2](https://user-images.githubusercontent.com/846306/118921104-38215780-b955-11eb-912b-270a8fefe11c.PNG)
3) However if group it by one of the columns , in this case I have selected "First Name". Then we select the Parent checkbox , it selects all the rows in the page and there is no indication of the selection in the parent (like in previous case)  . Now it stops working and you cannot deselect the selected rows.
![RT_does_not_work](https://user-images.githubusercontent.com/846306/118921214-66069c00-b955-11eb-9512-cfc0188363ca.PNG)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser : Chrome
- Version : Latest

**Comment by vani-adpr** [comment]
I am facing similar issue...did you get any solution?
