### ISSUE TITLE
Table filter is very slow

### ISSUE THREAD

**Issue by iadibar** [TanStack/react-table#3288]
**Describe the bug (required)**
I have table with multiple rows (about 400 rows) and I have search filter on specific row (by 'accessor') .
When I start typing a letter in the search input the letter appears only after 2 seconds and the table filtered after 2 seconds, take too long time for just filter table by text input.
Im getting the filter value as a props (props.filterValue as string type).
My search input is a custom component (my code).

**I want to note that all the information (table rows data) exists when I start to search, which means it is a filter that executed just in the UI.**

**Steps To Reproduce (required)**
1. search (input) enter latter 
2. set filter value 
3. get filter value as props (Table props) , by listening to change in useEffect hook inside my table component
4. get the filter value 
5. set globalFilterValue with my filter value 
**after about 2-3 seconds the latter appears in search input box and the data filtered**

**Expected behavior (Recommended)**
Fast search behaviour (when I have multi data in table) 

**Additional context**
using latest react-table version

**Comment by dutta-pratik** [comment]
@iadibar  you can try using useCallback hook for a search function. and sometimes it might happen because of the useEffect dependency and will re-render the whole component which takes time.
