### ISSUE TITLE
Virtualized Rows (React-Window) with Sub Components does not working

### ISSUE THREAD

**Issue by iadibar** [TanStack/react-table#3305]
**Describe the bug (required)**
When I try to connect `Virtualized Rows (React-Window)` and `Sub Components` and I clicked on a row in the table I do not see the sub component open under the row I clicked.

**Provide an example via Codesandbox! (required)**

`  const RenderRow = useCallback(
    ({ index, style }) => {
      const row = rows[index];
      const tableRowStyle = cn(styles.table_row,
        styles.table_row_hover,
        { [styles.expanded_row]: row.isExpanded },
        { [styles.show_cursor]: props.onRowClick },
        { [styles.active_row]: activeRowId === row.id });
      prepareRow(row);
      return (
        <Fragment key={row.id}>
          <div
            role='button'
            tabIndex={0}
            onClick={() => handleRowClick(row)}
            {...row.getRowProps({ className: tableRowStyle, style })}
          >
            {row.cells?.map((cell: any) => (
              <div
                role='button'
                tabIndex={0}
                onClick={(e: Event) => { handleCellClick(cell, row); e.stopPropagation(); }}
                key={cell.column.id}
                title={cell.value}
                className={cn('table-column', styles.table_row_td, cell.column.cellClassName)}
                {...cell.getCellProps(cellProps)}
              >
                {cell.render(ColumnFieldType.CELL)}
              </div>
            ))}
          </div>
          {row.isExpanded && props.SubComponent && (
            <div className={cn({ [styles.table_row_sub_component]: visibleColumns.length }, styles.table_row)}>
              <div className={styles.table_row_td}>
                <props.SubComponent row={row.original} />
              </div>
            </div>
          )}
        </Fragment>
      );
    },
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [prepareRow, rows, props, visibleColumns.length],
  );`

`      <div {...getTableProps()} className={styles.table}>
        <TableHeader {...tableHeaderProps} />
        <div {...getTableBodyProps()}>
          <FixedSizeList
            height={props.tableHeight}
            itemCount={rows.length}
            itemSize={53}
            width='100%'
          >
            {RenderRow}
          </FixedSizeList>
        </div>
      </div>`

**Steps To Reproduce (required)**

1. click on row

**Expected behavior (Recommended)**
click on row should open sub component under the clicked row

**Additional context**
Im using latest react version & typescript.
using react hooks

**Comment by bezsinnyidmytro** [comment]
Must say that it is really hard to understand anything for sure with code provided. You stated "Provide an example via Sandbox" but didn't actually provide any link to sandbox, but a piece of unfinished code.
Anyway I'll try to help you. A good thing to start with is that `FixedSizeList` display items with fixed size, for your case it is `height: 53px`. And I'm not sure that any operations which you did to handle `expanded` logic will change the height of item, even if it somehow does it will result in virtualization mechanism malfunction.
Please check for `VariableSizeList` from `react-window` and API for it

**Comment by soliyapintu** [comment]
I am facing same issue.
