### ISSUE TITLE
Resize columns feature with Material UI

### ISSUE THREAD

**Issue by zhitomir-oreshenski-mm** [TanStack/react-table#3314]
Hi guys,

Is it possible to provide me a codesandbox or example on how to implement resize feature with Material UI?

Basically, at the moment I have already imported material ui and the table is working. But I am not able to manage the resize functionality and it seems that it is not working.

BR,
Zhi

**Comment by zhitomir-oreshenski-mm** [comment]
Hello @fseitun,

Is there any progress on this?

I tried again to implement a resizing functionality. So far I noticed that in order to work we need to add useResizeColumns and useFlexLayout hooks into useTable. But it seems that useFlexLayout hook somehow broke the table and put everything alltogether into a single column.

Br,
Zhi

**Comment by pashkes** [comment]
i have the same problem
i don't want to use alpha version

**Comment by oliviertassinari** [comment]
@pashkes for more context, MUI might provide an headless API in the future, with all the Pro features in the MIT version, https://github.com/mui/mui-x/issues/1016

**Comment by tannerlinsley** [comment]
V8 is beta now and the column resizing is very performant and easy to implement.
