### ISSUE TITLE
aggregateValue's results are only available for aggregations on top level groups (depth = 0)

### ISSUE THREAD

**Issue by lucas-koehler** [TanStack/react-table#3323]
Hello,

first of all thanks for this awesome project.

**Describe the bug (required)**
The bug occurs when using the `useGroupBy` plugin with nested groupings (at least two columns to group by) in combination with the `aggregateValue` and `aggregate` column options.

Scenario:

- `aggregateValue` is used to define a function that calculates an aggregation basis for each leaf row.
- The `aggregate` function uses the values calculated by `aggregateValue` to calculate the groups aggregated values.

For top level groups (depth = 0) this works as expected: `aggregate` gets the values calculated with `aggregateValue`.
However, nested groups with depth > 0 only get the raw cell values instead of the ones calculated by `aggregateValue`.

I investigated this in the react-table code and this seems to be caused by the depth check here: https://github.com/tannerlinsley/react-table/blob/8c77b4ad97353a0b1f0746be5b919868862a9dcc/src/plugin-hooks/useGroupBy.js#L256

The `!depth` check leads to `aggregateValue` only being used for groups with depth 0. When I removed the check locally, the issue no longer occurred.

**Provide an example via Codesandbox! (required)**
I adapted the group by example to show this.
https://codesandbox.io/s/goofy-cloud-gextu?file=/src/App.js:6401-6786

Therefore, I adapted the Profile Progress column to calculate an `aggregateValue`. In this example, simply an empty array `[]`.
The `aggregate` function takes all leaf values and sums up the array lengths. This should result in an aggregated value of `0`.

**Steps To Reproduce (required)**

1. Aggregate by First Name and Last Name columns at the same time
2. Expand first group
3. The aggregated value of the expanded group is `0` but the aggregated value of the sub groups is `NaN` because they get the original value (a number) and try to get the array length from it. 

**Expected behavior (Recommended)**
Nested groups' `aggregate` functions get values calculated by `aggregateValue` instead of the the column's raw values.

**Screenshots**
![image](https://user-images.githubusercontent.com/6959840/122029675-5c921780-cdcd-11eb-8004-038c9984d334.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04
- Browser: Chrome 91.0.4472.101; Firefox 89.0 (64-bit)

**Possible Solution**
As mentioned earlier, it should be sufficient to remove the `!depth` check at https://github.com/tannerlinsley/react-table/blob/8c77b4ad97353a0b1f0746be5b919868862a9dcc/src/plugin-hooks/useGroupBy.js#L256 to fix the issue. However, I do not know if this has other unwanted implications.

**Comment by darkzairen** [comment]
Hello and thank you @tannerlinsley for this robust project.

But I am experiencing also the same issue where in I need to aggregate base from different set of columns as leaf values.
I would like to achieve it by using the `aggregateValue` callback function but it seems to apply only on groups with `depth=0`.
Base from my screenshot below, the 3rd log is from the group with depth 0 having the custom `leafValues`.

![image](https://user-images.githubusercontent.com/5230275/123236279-4132b500-d50f-11eb-981d-88c3e9bee8ab.png)

Btw, @lucas-koehler may I ask if you've figured a workaround or any temporary solution on this matter? TIA 😃

**Comment by lucas-koehler** [comment]
@darkzairen There is a sorta workaround that can be used for some use cases:
You can use a custom `Aggregated` renderer and do the aggregation there from scratch as you have access to the group's row and, thus, to all of its child leaves (via `row.leafRows`). This allows you to show the correct value.
The problem with this "workaround" is that sorting will **not** work based on the displayed, grouped values because sorting operates on the values computed with `aggregate` which is still not computed properly.

**Comment by darkzairen** [comment]
> You can use a custom `Aggregated` renderer

hi @lucas-koehler thank you! Yes I can confirm that approach, so far my case doesn't need sorting yet, thus the `Aggregated` render function will enough for me. 

Thank you again! 😁

**Comment by porebskp** [comment]
Hi, is there any chance to merge this patch not only into alpha but also v7?

**Comment by tannerlinsley** [comment]
This is fixed in v8. Aggregator functions can now choose to use leaf values or child values in their computations.
