### ISSUE TITLE
React-table doesn't calculate pageIndex correctly if manualPagination is true and pageCount is undefined.

### ISSUE THREAD

**Issue by RustamKarimov3** [TanStack/react-table#3338]
Worked in version 7.0.4
Doesn't work in version 7.7.0

React 16.8.0

**Comment by patrickmcdougle-okta** [comment]
Not a maintainer, but an answer to this question might help them:

Can you explain how it currently behaves and how you'd expect it to behave?

**Comment by RustamKarimov3** [comment]
I would like to implement controlled server side pagination by this example.
https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/pagination-controlled

But I have cases when pageCount is unknown.  I would be appreciate if react-table could calculate actual pageIndex correctly despite the unknown pageCount. It worked so in 7.0.4 version of react-table, but in version 7.7.0 this does not.

**Comment by patrickmcdougle-okta** [comment]
Yeah, I had a similar problem, for a while I was just setting pageCount to currentPage + 1 until I hit the end when I left it at the final pageCount. It probably would still help the maintainers for you to describe what currently happens vs what you think should happen.

**Comment by awaismehmood88** [comment]
try default autoResetPage to false
