### ISSUE TITLE
Number sort type does not handle negative values

### ISSUE THREAD

**Issue by amy-mac** [TanStack/react-table#3352]
**Describe the bug (required)**
A new number sort function was added to sortTypes to handle numbers since the default alphanumeric sort type does not handle floats. However, the number sort function does not handle negative numbers and treats the negative number the same way as its positive counterpart because the numbers are converted to strings that then get stripped of the negative sign [with this regex](https://github.com/tannerlinsley/react-table/blob/master/src/sortTypes.js#L106)

**Provide an example via Codesandbox! (required)**
Use a new [react-table codesandbox](https://codesandbox.io/s/m5lxzzpz69) to reproduce the issue.
This create codesandbox link is not working ⬆️ 

**Steps To Reproduce (required)**

1. Have a column that has "number" as its `sortType`
2. Have values in the cell that are negative as well as positive
3. Try to sort

**Expected behavior (Recommended)**
I would expect a sorting function that handles numbers to be able to sort negative numbers as lower values than positive numbers.

**Comment by Jeffdude** [comment]
Ensure the value returned by the accessor is a Number type, then use `sortType: 'basic'`

Fixed docs in #3359
