### ISSUE TITLE
changing of initialState.sortBy doesn't re-sort rows

### ISSUE THREAD

**Issue by DarthVitalus** [TanStack/react-table#3376]
**Describe the bug (required)**
Change `initalState.sortBy` prop - rows remain sorted by previous value

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/misty-wind-ctl1q?file=/src/App.js
forked from "Sorting" example

**Steps To Reproduce (required)**

1. Provide `initialState.sortBy` by `firstName` column, `desc: false`
2. Watch rows being sorted by this column in this direction
3. Click on `firstName` column header
4. See direction has changed (console output)
5. Rows order has not changed

**Expected behavior (Recommended)**
Rows order has changed to new direction (`desc: true`)

**Desktop (please complete the following information):**

- OS: iOS
- Browser: chrome
- Version: 91

**Additional context**
If you uncomment 156th line of code (`key` prop) - you'll see expected behavior.
It seems like `initialState` has been memoized incorrectly.

**Comment by Mandaglio94** [comment]
Hi, i edited your sandbox. 
Read the comments inside the code into: https://codesandbox.io/s/restless-cloud-9r8fk?file=/src/App.js

Hope it help! :)
