### ISSUE TITLE
Sticky headers won't work

### ISSUE THREAD

**Issue by bdata42** [TanStack/react-table#3386]
**Describe the bug (required)**
Whilst `react-table` is designed for utility, I've found that trying to add sticky headers just won't work. I've tried a few different methods of achieving sticky headers, including:

- position: sticky
- Moving headers outside of the table

Each of those solutions has its own issues.

Which leads to my question. Even if `react-table` does not support this feature, is there any way to achieve a recommended "third party solution"?

Any help whatsoever is greatly appreciated, as I might have to use a different library as I need this feature.

My attempts to turn it upside down to get it working, have been unsuccessful.

[I added a feature request here](https://github.com/tannerlinsley/react-table/discussions/3349), but actually I just need any guidance anyone can offer.

Thank you!

**Comment by Mandaglio94** [comment]
Hi bdata42, into my project i use Material-ui.

I created an example for you that show you how to do.

[https://codesandbox.io/s/stickyheaders-p6c20?file=/src/App.js](https://codesandbox.io/s/stickyheaders-p6c20?file=/src/App.js)

I don't understand what do you mean with "Moving headers outside of the table", because the headers must be into <table> tag.

**Comment by bdata42** [comment]
Thanks @Mandaglio94, really appreciate it. I will give this a try!

**Comment by AdirTrichter** [comment]
I have a question for you regarding this solution @simonemandaglio , I saw that you added the `stickyHeader` prop to the `Table` component, but the problem that I faced with is that it overrides the components that I wrote, and it changed it's looks completely.

The layout of the Header is as follows:

```
<Table stickyHeader>
	<TableHead>
		<TableRow>
			{headers.map(h => <HeaderCell />)}
		</TableRow>
	</TableHead>
	{...restOfTableComponents}
</Table>
```

As you can see below:
![image](https://github.com/TanStack/table/assets/32979877/766286c5-78d3-4028-8e50-404b1f84fb06)
![image](https://github.com/TanStack/table/assets/32979877/40bc7607-5591-4875-b86e-d56e954ff230)

Thanks ahead !
