### ISSUE TITLE
Mouse cursor is not sticking with the resizer when using useFlexLayout with useResizeColumns.

### ISSUE THREAD

**Issue by aravindsurya77** [TanStack/react-table#3399]
**Describe the bug**
I was trying to create a table with resizable columns and flexLayout. Resizing works fine but the problem is, when resizing, the cursor is not sticking to the resizer and this creates a confusion for the user, cause it is a bad UX.

**Provide an example via Code sandbox!**
***Please open the app in full browser window for a better view***
Code: https://codesandbox.io/s/vigorous-raman-xhie9?file=/src/App.js:1444-1457
App: https://xhie9.csb.app/

**Steps To Reproduce**
Steps to reproduce the behaviour:

1. Open the app in full window
2. Resize any column

**Expected behaviour**
Mouse cursor should always stick with the resizer when resizing

**Screen Recording**

https://user-images.githubusercontent.com/11169994/126684992-ba5be54b-b133-4aa9-827d-6ce73ef3889a.mov

**Desktop:**

- OS: macOs Big Sur
- Browser: Chrome
- Version: 91.0.4472.164

**Comment by aravindsurya77** [comment]
Hey @tannerlinsley,

Any idea why this is happening?

**Comment by tarasmck** [comment]
duplication of https://github.com/tannerlinsley/react-table/issues/2972
