### ISSUE TITLE
useResizeColumns breaks when used in a controlled way

### ISSUE THREAD

**Issue by FezVrasta** [TanStack/react-table#3403]
**Describe the bug (required)**
When you use the `useResizeColumns` plugin and the columns configuration is updated while the user is resizing a column, the sizes are reset back to their original value.

If you make your code update the columns configuration with the new user-defined sizes, the resize action breaks, the user is unable to resize the column if the columns state is updated while the user is resizing.

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/romantic-cherry-v2bew?file=/src/App.js

**Steps To Reproduce (required)**

1. Resize a column for more than 1 second
2. Observe the columns are reset to their original sizes

**Expected behavior (Recommended)**
It looks like react-table lacks of a system to allow the `useResizeColumns` plugin to work in a fully controlled/stateless way. Consumers are forced to rely on the internal state of the plugin.

**Desktop (please complete the following information):**

- OS: macOS
- Browser Chrome
- Version 7.7.0

**Additional context**

`useResizeColumns` should ideally provide a way to define the columns width state from the outside.

**Comment by crutch12** [comment]
@paulSerre You've saved my day

**Comment by OBKoro1** [comment]
@paulSerre  Thank you, boss. I also spent an afternoon on this issue. You saved me
