### ISSUE TITLE
Cell background color is not updated when the row is deleted

### ISSUE THREAD

**Issue by jaure96** [TanStack/react-table#3412]
The table (is a paginated one) has the functionality to add or delete rows, as well as edit cell values. Each time the user adds a new row or edits a cell, the cell or row is updated with a blue background.

Up to this point, everything works correctly. The problem comes when deleting a row. After deleting the row from the data structure, the row is removed from the table, but the **color of the row remains in the table until the pagination is updated**.

I have also opened a [thread on StackOverflow](https://stackoverflow.com/questions/68663749/update-cell-background-color-when-deleting-the-row-react-table) where the problem/bug is explained in more detail.
Any help there is welcome

**Comment by aditya211935** [comment]
I've added detailed explanation to your question on StackOverflow. Please mark it as accepted if you find it useful,
https://stackoverflow.com/a/68710932/16623462
