### ISSUE TITLE
column.getResizerProps is not a function

### ISSUE THREAD

**Issue by dlanorf** [TanStack/react-table#3428]
applying "disableResizing" option to useTable hook cause this issur.

This can be easily reproduced by adding "disableResizing: true" in the Column Resizing example of the react-table document (https://react-table.tanstack.com/docs/examples/column-resizing).

![resizing](https://user-images.githubusercontent.com/44251003/129527547-a983b70b-3984-4c15-9ba1-e90b34077e25.PNG)

**Comment by exsesx** [comment]
@dlanorf You should update your render. You can use `column.canResize` boolean property to handle this case.

**Comment by stofferd** [comment]
I'm having the same issue also adding canResize false to the column doesn't stop resizing - again you can try this out in the example: https://react-table.tanstack.com/docs/examples/column-resizing 
![Screenshot 2021-09-15 at 15 45 35](https://user-images.githubusercontent.com/26344373/133455744-5ab5e5e6-1391-4eec-b382-d4cebd430156.png)

**Comment by exsesx** [comment]
@stofferd you should use disableResizing property when you setup columns. I've mentioned column.canResize property so you could update your render method and don't apply resize props or avoid rendering resizer in the first place.

**Comment by stofferd** [comment]
Hey @exsesx  thanks for the quick reply. Apologies if I wasn't clear, if you add `disableResizing: true` to the column you get the error. 
![Screenshot 2021-09-15 at 16 38 36](https://user-images.githubusercontent.com/26344373/133466973-c760cab8-d506-40ba-ba10-f4b66eac729f.png)


However adding any `getResizerProps` function to the column resolves the issue:
![Screenshot 2021-09-15 at 16 51 31](https://user-images.githubusercontent.com/26344373/133467086-e8bfef48-bf8c-429f-a37e-e33ee89758d3.png)

Hope this helps someone else, though in hindsight it could just me! I realise the error is quite clear - "column.getResizerProps isn't a function"

**Comment by exsesx** [comment]
Hey again @stofferd!

We didn't understand each other completely 😄 
Let me try to explain what I mean one more time.

I'm suggesting using `disableResizing` in the column setup and `canResize` in the render:

```tsx
  const columns = React.useMemo(
    () => [
      { Header: 'Name', columns: [{ Header: 'First Name', accessor: 'firstName', disableResizing: true }] },
      // ...
    ],
    [],
  );

  // ...

  return (
    // ...

    <div className="header">
      {headerGroups.map((headerGroup) => {
        const { key, ...headerGroupProps } = headerGroup.getHeaderGroupProps();

        return (
          <div key={key} {...headerGroupProps} className="tr">
            {headerGroup.headers.map((column) => {
              const { key, ...headerProps } = column.getHeaderProps([
                {
                  className: (column as unknown as { className: string }).className,
                  style: (column as unknown as { style: CSSProperties }).style,
                },
              ]);

              return (
                <div key={key} {...headerProps} className={classNames('th', { ['resizing']: column.isResizing })}>
                  {column.render('Header')}
                  {column.canResize && (
                    <div
                      {...column.getResizerProps()}
                      className={classNames('resizer', { ['resizing']: column.isResizing })}
                    />
                  )}
                </div>
              );
            })}
          </div>
        );
      })}
    </div>

    // ...
  );
```

Pay attention to this part:

```tsx
{column.canResize && (
  <div
    {...column.getResizerProps()}
    className={classNames("resizer", { ["resizing"]: column.isResizing })}
  />
)}
```
