### ISSUE TITLE
useResizeColumns and useAbsoluteLayout hooks incompatible

### ISSUE THREAD

**Issue by phal0r** [TanStack/react-table#3432]
**Describe the bug (required)**
This is a regression of #1827 

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/elated-sound-nbyov

**Steps To Reproduce (required)**
Just rendering shows, that the layout is broken

**Expected behavior (Recommended)**
useAbsoluteLayout sets `position: absolute` for getHeaderProps(). useResizeColumns is required to be added after useAbsoluteLayout and sets `position: relative` for getHeaderProps(). The combination of position relative and the width/height from useAbsoluteLayout breaks the layouting of the header.

Expected behaviour is, that useResizeColumns is agnostic to all available layouts and works out-of-the-box. If this is not possible, incompatibilities should be pointed out in the docs.

**Comment by LeeChingYin** [comment]
Has this been fixed yet ？
