### ISSUE TITLE
Browser error inside the useTable call

### ISSUE THREAD

**Issue by CZHach** [TanStack/react-table#3446]
**Describe the bug (required)**
My web app uses the latest version of React-Table and I am getting an error when I try to run it on an IIS Server.  Here is the error:

```
TypeError: t.forEach is not a function
    at se (useTable.js:591)
    at useTable.js:195
```

My web app runs successfully locally on IIS Express.  It's only after publishing to an IIS Server that I encounter errors.

I have tried deleting node_modules folder and using `npm install` to rebuild.

The web app builds successfully when I run `npm run build`.

It publishes successfully to the IIS Server.

It starts to load the web app in the browser when it goes through the non-React Table code, but as soon as it hits the React-Table part, I encounter the errors.

If I remove the React-Table part, it loads fine with no errors.

I have tried both Chrome and Firefox.

**Desktop (please complete the following information):**

- OS: Windows Server 2016
- Browser Chrome and Firefox

Here is the `useTable` part of the code:

```
} = useTable(
        {
            columns,
            data,
            defaultColumn,
            filterTypes,
            // updateMyData isn't part of the API, but
            // anything we put into these options will
            // automatically be available on the instance.
            // That way we can call this function from our
            // cell renderer!
            updateMyData,
            // We also need to pass this so the page doesn't change
            // when we edit the data. Undefined tells it to use the default
            autoResetPage: !skipReset,
            autoResetSelectedRows: !skipReset,
            disableMultiSort: true,
        },
        useFilters,
        useGroupBy,
        useSortBy,
        useExpanded,
        usePagination,
        useRowSelect,
    )
```

**Comment by Kestutis** [comment]
I had same problem. In my case, data was not array, but blob on Firefox. Check what are you passing as data to useTable.
