### ISSUE TITLE
Row/SubRow selection not working as expected

### ISSUE THREAD

**Issue by natalia-mh** [TanStack/react-table#3465]
**Describe the bug (required)**
When I select a parent row and deselect a subRow, the parent row remains checked

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/react-table-grouping-selection-subrows-forked-kkftb?file=/src/makeData.js:70-79

**Steps To Reproduce (required)**

1. Go to table
2. Select parent row (+)
3. Expand subRows (+)
4. Deselect a subRow/subRows
5. Error: The parent row remains checked

**Expected behavior (Recommended)**
The parent row should not be checked when subRow/subRows is/are deselected

**Screenshots**
![image](https://user-images.githubusercontent.com/85306505/133661070-0d74efdd-bf66-4bcb-886c-beb1b7bbfa13.png)  
![image](https://user-images.githubusercontent.com/85306505/133661124-3a578d49-d9d5-48ca-93fb-d78698c0bbf7.png)

**Desktop (please complete the following information):**

- OS: iOS
- Browser: chrome, safari, firefox
- Version 7.7.1

**Additional context**
It does not happen if we first select the subRows and deselect them

In grouping selection, the expanded rows selection works as expected
https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/kitchen-sink?from-embed=&file=/src/App.js

**Comment by dgattey** [comment]
I just came here to report the same bug - here's another CodeSandbox reproduction of it https://codesandbox.io/s/condescending-germain-lbn07. Thanks!

**Comment by dgattey** [comment]
Additionally, it looks like if a subrow is indeterminately selected, its parent is NOT also indeterminately selected (but should be) 
<img width="304" alt="image" src="https://user-images.githubusercontent.com/982182/144144626-b0501c30-e2bf-471b-ad0e-1b26328528f6.png">

**Comment by dgattey** [comment]
https://github.com/tannerlinsley/react-table/issues/3106 This looks to be the same bug

**Comment by simpleesnehil** [comment]
The following bug only occurs when the prop `paginateExpandedRows` is turned to false. When that is removed, the behaviour is as one expects.
