### ISSUE TITLE
@types/react-table not working for 7.7.0 and @types/react-table 7.7.3

### ISSUE THREAD

**Issue by maciej-bartynski** [TanStack/react-table#3468]
**PROBLEM TLDR:**
I am not able to use react-table (getSortByToggleProps method) in typescript project.

**CONFIGURATION:**

```
react-table 7.7.0 
@types/react-table 7.7.3
typescript: 4.4.2
```
and also I have files:
- tsconfig.json in root dir.
- react-table-config.d.ts available on path: './types/react-table-config.d.ts' from root dir.
- content of above file is copied from documentation, from here https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-table

and also I added to my tsconfig.json following lines (after several tries without following statements in tsconfig):
```
    "typeRoots": [
      "./node_modules/@types",
      "./types/react-table-config.ts"
    ]
```
I imported useSortBy (correclty) and added as option to useTable (correctly).

**BUG DETAIL:**

I have this bug:
`Property 'getSortByToggleProps' does not exist on type 'HeaderGroup<object>'`
when using method:
`column.getHeaderProps(column.getSortByToggleProps())`
and also all interfaces in react-table-config.d.ts has following error:
`All declarations of 'Hooks' must have identical type parameters.`
and also iwhole import statement in react-table-config.d.ts has this error:
`All imports in import declaration are unused`

**I TRIED ALSO:**
I tried also:
- renaming react-table-config.d.ts to index.d.ts and changing in tsconfig.json "./types/react-table-config.d.ts" to "./types" (in field typeRoots: [ ... ] in tsconfig
- not adding "./types" directory (or react-table-config.d.ts path) to tsconfig.json,
- moving react-table-config.d.ts to root directory.

FILE DETAILS:

1. tsconfig.json:
```
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "experimentalDecorators": true,
    "baseUrl": "src",
    "noFallthroughCasesInSwitch": true,
    "typeRoots": [
      "./node_modules/@types",
      "./types"
    ]
// this configuration was tested with and without "typeRoots" field
  },
  "include": [
    "src"
  ]
}
```

2. project file: 
```

const ReactTable = () => {
    const {
        getTableProps,
        headerGroups,
        rows,
        prepareRow,
    } = useTable({ columns, data }, useSortBy)

    return (
        <div {...getTableProps()}>

            {headerGroups.map((headerGroup, idx) => {

                const { key, ...headerGroupProps } = headerGroup.getHeaderGroupProps();
                return (
                    <StyledListHeader
                        {...headerGroupProps}
                        key={key}
                    >
                        {headerGroup
                            .headers
                            .map((column, idx) => {
                                return (
                                    <span {...column.getHeaderProps(column.getSortByToggleProps())}>
                                        {column.render("Header")}
                                    </span>
                                )
                                )
                        })}
                    </StyledListHeader>

                )
            })}

{...rest of jsx }
</div>
)}}

```

**Comment by MoSheikh** [comment]
I installed `react-table` yesterday as well and am running into the same issue. 

The current documentation around extending declarations provides a generic type signature for various interfaces as similar to the following:
```ts
export interface Cell<D extends Record<string, unkown>= Record<string, unkown>, V = any>
  extends UseGroupByCellProps<D>,
    UseRowStateCellProps<D> {}
```
which conflicts with the actual types in `@types/react-table 7.7.3`:
```ts
export interface Cell<D extends object = {}, V = any>
  extends UseGroupByCellProps<D>,
    UseRowStateCellProps<D> {}
```

The latter type declaration is warned against by `eslint-typescript` due to the ambiguous nature of the `object` type. 

While I'm currently unable to use the library, I'm incredibly impressed by the features in the documentation and look forward to being able to try it out. Thanks for all your hard work on this!

**Comment by kurt1288** [comment]
Same issue here. I've tried extending the type defs as suggested in some of the other similar issues but I just get compiler errors about conflicting definitions.

**Comment by raduflp** [comment]
having a similar issue with `useSortBy` 
here's a simple reproduction with the latest `react-table@7.7.0` and `@types/react-table@7.7.5`
https://codesandbox.io/s/react-table-usesortby-ts-issues-1k7rf
