### ISSUE TITLE
setSortBy doesn't set column sort to descending

### ISSUE THREAD

**Issue by langfordG** [TanStack/react-table#3508]
**Describe the bug (required)**
Setting the sort of a column to be descending (by calling setSortBy) results in a column that is sorted ascending. E.g setSortBy([{columnId: column.id, desc: true}]) does not set column.isSortedDesc to be true.

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/funny-kepler-zm32f?file=/src/App.js

**Steps To Reproduce (required)**
In the above sandbox,
1. Click inside the red box in the first table header (which calls setSortBy([{columnId: column.id, desc: true}])
2. The sort for that column is now ascending rather than descending, as the arrow is facing upwards.

**Expected behavior (Recommended)**
I expected to see the sort for that column to be descending, since descending was specified as true in the call to setSortBy. The value of column.isSortedDesc changes from undefined to false (instead of true).

**Desktop (please complete the following information):**

- OS: MAC OS Catalina
- Browser: Chrome
- Version: 94.0.4606.71

**Comment by Go1dExperience** [comment]
Hi, unfortunately I don't think this is possible. Your onClick event does fire, but after that the default behavior kicks in:
https://github.com/TanStack/react-table/blob/76a4a861ee56b782404ef91987c3b5691ecf2ebc/src/plugin-hooks/useSortBy.js#L33-L46
You can see every header is given a default onClick event as well, and unfortunately `undefined` means it will sort by ascending value. I've tried to change it to `true`, and it works like you want, but I don't know if there is even a way to overwrite this.

**Comment by Shivank12batra** [comment]
@Go1dExperience did you find a way? I m stuck with the same issue
