### ISSUE TITLE
Multisort does not work when providing a custom sort function

### ISSUE THREAD

**Issue by reinrl** [TanStack/react-table#3512]
Multisort seems to work just fine...as long as you are using built-in sort types (see [this example](https://codesandbox.io/s/winter-butterfly-oe02f), which loads with the first two columns included in the default sort). As soon as I attempt to use a custom sort function, sorting only seems to take into account the first column specified (see [this example](https://codesandbox.io/s/inspiring-glade-y8pxx), which is identical to the functional first example - although it specifies a custom sort function). I tried looking through the documentation, as well as looking through the source code for the built-in sort types, and I don't see anything different from what I am doing?

(Interestingly enough, the sort icons would make it seem like both columns were sorted; but if you put a breakpoint in the custom sort function, you can clearly see that it never gets called for the second column. Also potentially worth noting is that this only seems to be an issue if both columns use a custom sort. If I alter the second example such that the first column uses one of the built-in sort types - either by manually using one, or just accepting the default - then the multisort appears to function as expected.)

**Comment by reinrl** [comment]
@sbdfh gooooood eyes - thanks for catching that!

**Comment by TungTTHybrid** [comment]
ccc
