### ISSUE TITLE
Select All rows from all pages with controlled pagination

### ISSUE THREAD

**Issue by ioanarucareanu** [TanStack/react-table#3514]
### Discussed in https://github.com/tannerlinsley/react-table/discussions/3513

<div type='discussions-op-text'>

<sup>Originally posted by **ioanarucareanu** October 26, 2021</sup>
Hi! 
I have been using react-table and implemented back-end pagination, select functionality and it all works great. However, I have been trying to wrap my head around implementing also the functionality of selecting all the rows in all the pages (for e.g like in Gmail, having a link/button allowing you to select/unselect the total number of items) and all my efforts were in vain until now. 
Any lead on this? How could I accomplish a Select All from all pages functionality, since my data in not fully loaded at the point of selection? Any help/ suggestion is welcome :) Thank you in advance!
</div>

**Comment by paulSerre** [comment]
Hi,

Just use a custom state in the parent component
`const [allSelected, setAllSelected] = React.useState<boolean>(false);`

Then, use it in your column. The trick is to pass the function as a parameter to the cell.

```
        hooks => {
            if (rowSelect) {
                hooks.visibleColumns.push(columns => [
                    {
                      id: 'selection',
                      Header: (/*{_getToggleAllRowsSelectedProps}*/{allSelected, setAllSelected}) => (
                        <div>
                          <HCheckbox checked={allSelected} onClick={() => setAllSelected(prev => !prev)}/>
                        </div>
                      ),
                      Cell: ({ row, allSelected }) => (
                        <div>
                          <HCheckbox checked={allSelected ||row.getToggleRowSelectedProps()?.checked} onClick={row.getToggleRowSelectedProps().onChange} />
                        </div>
                      ),
                      disableResizing: true,
                      width: 50,
                      minWidth: 50,
                    },
                    ...columns,
                  ])
            }
        }
```

**Comment by vamsigugulothu** [comment]
> 

Please send HCheckbox component implementation also
