### ISSUE TITLE
Fetching data in component that doesn't render the table causes an infinite rerender loop

### ISSUE THREAD

**Issue by Gusis93** [TanStack/react-table#3522]
**Describe the bug (required)**
When using `usePagination` and fetching data in a component that doesn't render the table, there is a `Maximum update depth exceeded.` error.

Example: 
- Have a Component1 create a `tableInstance` with `useTable` and also fetch some random unrelated data.
- Have a Component2 render an empty table or a table with some data.
- Make Component1 render Component2.

**Only happens** when `manualPagination` is set to false, cannot be reproduced if the `manualPagination` is set to true. Can be tried in the sandbox.

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/competent-jennings-91rps

**Steps To Reproduce (required)**
- Create a Table component
- Create another component that creates a table instance
- Fetch data in that component.
- Check the `Maximum update depth exceeded.` error.

**Expected behavior (Recommended)**
- Infinite loop shouldn't happen when I'm fetching data in another component

**Desktop (please complete the following information):**
- OS: MacOS
- Browser: Firefox
- Version 93

**Additional context**
The only way I got it working is by setting `autoResetPage` to false when using automatic pagination, tough I don't know if this is the proper way of handling this, the docs don't specify anything like it.

**Comment by trumbitta** [comment]
I think (and hope, since I've yet to try this on my own app) this covers it: https://react-table.tanstack.com/docs/faq#how-do-i-stop-my-table-state-from-automatically-resetting-when-my-data-changes
