### ISSUE TITLE
Virtualization makes cell to remount everytime the data changes

### ISSUE THREAD

**Issue by JulienDemarque** [TanStack/react-table#3535]
**Describe the bug (required)**
We are using state in our Cells (for example inputs). The issue is that when we update the data passed to the table, it remounts entirely all the cells. This seems to happen only with the virtualization from react-window.
It's a problem because it becomes impossible to have an editable virtualized table.

**Provide an example via Codesandbox! (required)**
here is an example of it, you can see in the console log that the cell remounts every time the data changes...
https://codesandbox.io/s/jolly-tess-fzyzj?file=/src/App.js

**Steps To Reproduce (required)**

create a virtualized table, update the data, see your cell remount

**Expected behavior (Recommended)**
Cells should rerender but not remount.

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. iOS] macOS Catalina
- Browser [e.g. chrome, safari] Chrome
- Version [e.g. 22] 95

**Additional context**

**Comment by kacperkapusciak** [comment]
@JulienDemarque the whole point of virtualization is to unmount unnecessary elements and mount them when they are needed.

You can resolve your problem by 'lifting the state' from the cell to the component higher in the hierarchy. You'll end up in quite a huge js object/array that will keep an individual state of each cell and you'll need to update that accordingly.

Hope that helps

**Comment by JulienDemarque** [comment]
@kacperkapusciak shouldn't it unmount elements only when the elements are scrolled out of sight? Otherwise, when the data change, it would make sense to keep the elements mounted if the keys/ids are the same...
Not sure if lifting the state is a solution, if the elements are still mounted/unmounted, I would need to keep in the state the focus on the input and force the focus again when the component remounts. It feels a bit wacky.
My use-case is real-time updates on the table, so I can't expect the updates to happen only after input blur for exemple

**Comment by tdurand** [comment]
I have the same issue, did you find a way around @JulienDemarque ?

**Comment by JulienDemarque** [comment]
@tdurand Yes! we use react-virtuoso instead of react-virtualized for the virtualization part and it worked.
