### ISSUE TITLE
hooks.visibleColumns not rerendering correctly

### ISSUE THREAD

**Issue by colinluzio** [TanStack/react-table#3545]
When this hook is initially called on page load, the column is rendered correctly depending on whether showing is set to true or false:

```       hooks => {
      hooks.visibleColumns.push(columns => {
        return !showing ? [
          {
            id: 'selection',
            // Make this column a groupByBoundary. This ensures that groupBy columns
            // are placed after it
            groupByBoundary: true,
            // The header can use the table's getToggleAllRowsSelectedProps method
            // to render a checkbox
            Header: ({ getToggleAllRowsSelectedProps }) => (
              <div>
                <IndeterminateCheckbox {...getToggleAllRowsSelectedProps()} />
              </div>
            ),
            // The cell can use the individual row's getToggleRowSelectedProps method
            // to the render a checkbox
            Cell: ({ row }) => (
              <div>
                <IndeterminateCheckbox {...row.getToggleRowSelectedProps()} />
              </div>
            ),
          },
          ...columns,
        ] : []
      })
    }
```

If however the showing variable changes, while the hook is being called and visibleColumns is updated, the first column is not being re-rendered and it shows the initial state.

**Comment by fseitun** [comment]
Hi, could yo provide a working example (codesanbox or similar) of this situation?

**Comment by bbernovici** [comment]
Hi, I think you have encountered the same problem that I had earlier, somehow that component does not get re-rendered when you are passing a prop or functional component state variable, in your case the `showing` variable. 
You can try to declare a stateReducer in your useTable() like this (TypeScript ahead):
`
useTable({
initialState: {
      showing: false
} as any,
stateReducer: (newState, action, prevState) => {
      console.log(action, newState, (newState as any).showing);
      switch (action.type) {
        case "show":
          return {
            ...newState,
            showing: action.payload
          };
        default:
          return newState;
      }
    }
})
`
And then handle the effect in your FC like this:
`
useEffect(() => {
    dispatch(({ type: "selected", payload: props.showing}))
  }, [props.showing])
`
Not entirely sure this is _the way_ but it worked for me. Though, I'm curious why an external prop does not refresh it, is it related to memoization?

**Comment by jitendra88299** [comment]
For me it is saying dispatch is undefined

**Comment by El-Omar** [comment]
Whoever is still having an issue with this, I fixed this issue using the hook `visibleColumnsDeps` to pass in additional dependencies I needed to rerender the `visibleColumns` hook.

```tsx
hooks.visibleColumnsDeps.push(deps => [...deps, showing, extraDependenciesYouHave]);
```
