### ISSUE TITLE
Control of row selection by several checkboxes

### ISSUE THREAD

**Issue by AnnaKuhir** [TanStack/react-table#3557]
### Discussed in https://github.com/tannerlinsley/react-table/discussions/3549

<div type='discussions-op-text'>

<sup>Originally posted by **AnnaKuhir** November 17, 2021</sup>
Good evening! Thank you for your work, I am actively using this library and have a very interesting question.

Do we have the ability to control the selection of a row not with one checkbox, but with several (I attach a sample picture of how it might look)
And so that at the same time we return an array with approximately the following data

[
    {
        id: checkboxId1
        selectedElement: {selectedElementObj}
    }
    {
        id: checkboxId2
        selectedElement: {selectedElementObj}
    }
]

![image](https://user-images.githubusercontent.com/58226384/142234232-a0525e33-6cd9-490d-afbd-22c868a515fe.png)
</div>

**Comment by fseitun** [comment]
Hi! Could you please expand on a use case for a feature such as the one you're proposing?

**Comment by AnnaKuhir** [comment]
> Hi! Could you please expand on a use case for a feature such as the one you're proposing?

Hey!
I don't know how detailed my description will seem to you, but I need such logic for the following case:

For example, I have the possibility of choosing lenses for the eyes, I can choose the same lens for both the left eye and the right eye, for this I can use a single selection in the table and display on the page which lens was selected (Figure 1)

![image](https://user-images.githubusercontent.com/58226384/144027829-53e3fc40-23fd-4d9c-82f4-48548f7ee897.png)


But I may also be able to choose different lenses for the left eye and the right eye. In this case, I need to be able to choose one lens for the left eye and a completely different one for the right eye (while I still have a single choice) and display it on the page (Figure 2)

![image](https://user-images.githubusercontent.com/58226384/144028190-a57fd4b6-08bb-4dae-89d8-bd03c4fb5ddb.png)


So far I could not think of how I can control this, having 2 checkboxes in a row, since when I click on one checkbox, the second one is automatically selected, since row.isSelected = true
That is, I need to control not only the selected row but also the state of the checkboxes ... as I understand it
