### ISSUE TITLE
Resizing simple two columns full width column flickers and reflect odd behavior

### ISSUE THREAD

**Issue by danielpaz6** [TanStack/react-table#3593]
**Describe the bug (required)**
Resizing simple two columns full-width column flickers and reflect odd behavior, please take a look at the example in codesandbox I made.

I took the example from docs to resizeable full width table: https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/full-width-resizable-table?file=/src/App.js

and Modified the columns variable to fit my needs - just a simple two columns table and when I tried to resize it, I faced tons of issues.

Take a look on the example link below:

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/shy-forest-9vq8t?file=/src/App.js:0-4735

**Steps To Reproduce (required)**

1. Go to https://codesandbox.io/s/shy-forest-9vq8t?file=/src/App.js:0-4735
2. Try to resize any of the two colums

**Expected behavior (Recommended)**
The column start/end to follow the cursor, but instead it just behaves oddly.

**Desktop (please complete the following information):**

- OS: mac OS
- Browser:  chrome

**Comment by gabrielsch** [comment]
I'm having the same issue, I wonder if it has to do with `useFlexLayout`

**Comment by austincondiff** [comment]
Duplicate of #2972
