### ISSUE TITLE
Table with useExpanded and useGlobalFilter not working properly

### ISSUE THREAD

**Issue by mahadazad** [TanStack/react-table#3614]
**Describe the bug (required)**
I am trying to create a table with sub rows and filtering (global) functionality. When the filtration is applied the expand functionality breaks and we no longer see the expand buttons. Notice I am doing a very simple filtration, just on the root level and not on the sub rows.

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/busy-stallman-1tcx5?file=/src/App.js

**Steps To Reproduce (required)**

1. Go to the search field
2. Type some characters to filter
3. See the expand buttons are no longer available

**Expected behavior (Recommended)**
The table should still expand.

**Screenshots**
![CleanShot 2022-01-06 at 19 05 26](https://user-images.githubusercontent.com/696470/148396071-6cc73a71-9fb2-47a4-bff0-70c376b35bb5.gif)

**Desktop (please complete the following information):**

- OS: MacOS 12.1
- Browser: chrome
- Version: Version 97.0.4692.71 (Official Build) (x86_64)

**Comment by ZiedHf** [comment]
Did you manage to fix it or find a work-around ?

It's the same issue I mentionned [here](https://github.com/TanStack/react-table/discussions/3695) but I think this is the behavior they're expecting since the line "instance" in that case does not have SubRows anyway.

However I don't understand why clearing the filter does not return the old state of "instance" ?

Maybe I have to implement a custom filter function or something ? I didn't find a way yet to display the SubRows of an unfiltred/displayed Parent.

**Comment by ZiedHf** [comment]
See [this](https://github.com/TanStack/react-table/issues/2064#issuecomment-1033845120)

**Comment by ZiedHf** [comment]
It looks like there is a bug with the same plugins

[Take a look here, an example was provided there](https://github.com/TanStack/react-table/discussions/3745)

It seems that this part in [useGlobalFilter](https://github.com/TanStack/react-table/blob/v7/src/plugin-hooks/useGlobalFilter.js#L137) need an intialSubRows state better than changing the subRows. So we execute the filter on the intialSubRows instead.

**Comment by GulinaTayier** [comment]
> See [this](https://github.com/TanStack/react-table/issues/2064#issuecomment-1033845120)

This example didn't work for me.. defaultGlobalFilter has error: 
```
const defaultGlobalFilter: (rows: any, columnIds: any, filterValue: any, options: any) => any
Expected 4 arguments, but got 3.ts(2554)
defaultGlobalFilter.tsx(7, 5): An argument for 'options' was not provided.
```

**Comment by ZiedHf** [comment]
@GulinaTayier you're using TS clearly and you need to make the last argument as an optional argument

```
export type FilterOptions = {
    filteredIds: string[];
};

// Better to use Generics for rows == Row<T> https://www.typescriptlang.org/docs/handbook/2/generics.html
// options is optional
const defaultGlobalFilter = (rows: Row<any>, columnIds: string[], filterValue: any, options?: FilterOptions ) => {
```

With that being said, this example is just a work around for v7 and I suggest to try first v8.
