### ISSUE TITLE
References isSorted and isSortedDesc never changes when a column is provided under hiddenColumns

### ISSUE THREAD

**Issue by aravindtrue** [TanStack/react-table#3635]
**Describe the bug (required)**
1. I would like to hide a column, and table header for all the columns
2. I still want to use sort feature in a different way i.e., I will place the sort option right above the table where user can click to change the order of the list view
3. In this case, Global search and Filter above the table are working as expected where the sorting is not. `isSorted` and `isSortedDesc` never changes when I click the sort for the hidden column

**Provide an example via Codesandbox! (required)**
[react-table codesandbox](https://codesandbox.io/s/tannerlinsley-react-table-sorting-forked-ytns6?file=/src/App.js:1421-1433) to reproduce the issue.

**Steps To Reproduce (required)**
1. Click `Device Usage`, you will see an arrow appears and changes up/down.
2. Click `Memory`, you will see an arrow appears and changes up/down.
3. When you click `Name`, you will NOT see the same behavior but the list view still orders in the asc order

**Expected behavior (Recommended)**
Arrow should appear when `Name` is clicked i.e., `isSorted` and `isSortedDesc` must change when clicking the sort option for the hidden column

**Desktop (please complete the following information):**

- OS: MacOS BigSur 11.6
- Browser Chrome
- Version 96.0

**Comment by aravindtrue** [comment]
Any updates on this issue?

**Comment by Go1dExperience** [comment]
I don't think this is a possible situation. For the sorting icons to appear, the `isVisible` must be true, that's the short answer. The long answer is the column must exist in **flatHeaders**, which depends on **headerGroups** array. And for a column to be in **headerGroups**, it must have isVisible = true. If you go to https://github.com/TanStack/react-table/blob/76a4a861ee56b782404ef91987c3b5691ecf2ebc/src/hooks/useTable.js#L364-L369 and change the 2 return statements to true, you will get the result you want.
