### ISSUE TITLE
`Column` type declaration is wrong for deeply nested values

### ISSUE THREAD

**Issue by BanderasPRO** [TanStack/react-table#3645]
From the documention
**Column Options**
`accessor: String | Function(originalRow, rowIndex) => any`
If a string is passed, the column's value will be looked up on the original row via that key, eg. If your column's accessor is firstName then its value would be read from row['firstName']. **You can also specify deeply nested values with accessors like `info.hobbies` or even `address[0].street`**

Next example shows how wrong `Column` type declaration makes TS errors: 

```js
import { Column } from "react-table";

export interface RowData {
  person: Person,
  profile: Profile
}

const columns: Column<RowData>[] = [
  {
    accessor: 'person.name'   // <--- TS2322: Type "person.name" is not assignable to type "person" | "profile".
  },
  {
    accessor: 'profile.userName' // <--- TS2322: Type "profile.userName" is not assignable to type "person" | "profile".
  }
]
```

The cause of the issue is too strict declaration of `accessor` field
```js
{ accessor?: (keyof D extends never ? IdType<D> | Accessor<D> : Accessor<D>) | undefined; };
```

You should give more flexible rule for the field (add ` | string` option)
```js
export type ColumnWithLooseAccessor<D extends object = {}> =
    & ColumnInterface<D>
    & ColumnInterfaceBasedOnValue<D>
    & (
        | { Header: string }
        | { id: IdType<D> }
        | { accessor: keyof D extends never ? IdType<D> : never | string}  // <-- here 
    )
    & { accessor?: (keyof D extends never ? IdType<D> | Accessor<D> : Accessor<D>) | string | undefined; }; // <-- and here 
```

**Comment by JeomJeom** [comment]
I have this issue as well when running it with ts. 
Looking for a solution or suggestion...

@BanderasPRO Did you manage to solve this issue?
