### ISSUE TITLE
I think the last release has killed the sandbox?

### ISSUE THREAD

**Issue by lorna-moneybox** [TanStack/react-table#3655]
**Describe the bug (required)**
https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/basic

INVALID_REQUEST - No commit found for SHA: master

**Provide an example via Codesandbox! (required)**
😅

**Steps To Reproduce (required)**
Go here: https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/basic

**Comment by reaganmac** [comment]
Seems to be fixed now in 17fe3a879466fdd323a608dcdd50db896e3930ad

**Comment by jaiakash** [comment]
Yeah, that's true. I can't access codebox on the example given on the website.
![Screenshot from 2022-01-26 01-08-13](https://user-images.githubusercontent.com/33419526/151047347-0b2e5de2-80bb-4893-a1c8-5f35dcae0b87.png)
![Screenshot from 2022-01-26 01-08-27](https://user-images.githubusercontent.com/33419526/151047359-1cd508ef-6268-49ad-ae9b-2318bba124ce.png)

**Comment by tannerlinsley** [comment]
The sandboxes have been changed to point at the `v7` branch. If you find any old sandboxes that don't work, change the `master` in their URL to `v7` and you'll be fine.
