### ISSUE TITLE
Selected rows always resetting when changing page 

### ISSUE THREAD

**Issue by rafi-p** [TanStack/react-table#3658]
<img width="623" alt="Screen Shot 2022-01-26 at 16 22 22" src="https://user-images.githubusercontent.com/70462270/151138235-1fd3934c-59a3-4af1-a3ad-ffa166354048.png">
As you can see from the picture, I have my autoResetSelectedRows to false, and manualPagination to true because I'm using controlled pagination (getting data when changing page) but every time I'm changing the page, selectedRowsId became {}

Is there a solution? or is this a bug?

**Comment by rafi-p** [comment]
[https://codesandbox.io/s/react-table-server-side-pagination-row-select-5gfrp?file=/src/App.js](url)
This is my reference for selected row with controlled pagination
The difference is, I'm fetching in parent component

**Comment by Go1dExperience** [comment]
Hi, it seems like it works fine in the code sandbox right? Can you provide an example where it doesn't work, or am I misunderstanding you, because the rows are not reset in the example I believe.

**Comment by rafi-p** [comment]
> Hi, it seems like it works fine in the code sandbox right? Can you provide an example where it doesn't work, or am I misunderstanding you, because the rows are not reset in the example I believe.

```
	loadingData
		?
		<MyLoader />
		: 
		<TableComponent/>
```
Hai, so sorry I forgot to close this thread
Anyway, the problem has been solved
The selectedRow are resetting because the UI is gone from the DOM everytime changing the page (I need some loader), so the table should be in the DOM for this to works

**Comment by sermiribrahim** [comment]
Hi @rafi-p I having a very similar issue, I get data for the table from an api call, and when the user click on the pagination for for second record set, it makes another api to the data for the second record set of the table, but "selectedRowIds": {}" gets empty every time I change the pagination. I can please provide an example how you solve it?

**Comment by savalemilind6984** [comment]
> I having a very similar issue, I get data for the table from an api call, and when the user clicks on the pagination for for second record set, it makes another api call to get the data for the second record set of the table, but "selectedRowIds": {}" gets empty every time I change the pagination. Can you please provide an example if how you solv

I am also looking for same kind of solution... @rafi-p : can you provide example here
