### ISSUE TITLE
V8 csb examples not running correctly 

### ISSUE THREAD

**Issue by Bezmehrabi** [TanStack/react-table#3675]
**Describe the bug (required)**
V8 codesandbox examples are not running correctly.

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/github/tanstack/react-table/tree/master/examples/basic

**Comment by adnanhassan23** [comment]
These examples are working https://react-table.tanstack.com/docs/examples/sorting

**Comment by tannerlinsley** [comment]
Should all be working now :)
