### ISSUE TITLE
useRowSelect does not work when loading new data

### ISSUE THREAD

**Issue by emdotem** [TanStack/react-table#3676]
**Describe the bug (required)**
Using useRowSelect in conjunction with InfiniteScroll deselect the rows once new data comes in. More in general, if you update the data of the table with new rows, the selection disappear

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/react-table-infinite-scroll-with-selected-1iuzv?file=/src/App.js

**Steps To Reproduce (required)**

1. Go to the bottom
2. Select some random rows
3. Scroll down to the bottom again
4. New data will be loader
5. The previously selected rows disappear

**Expected behavior (Recommended)**
Expected behaviour is to keep the selection even if new data comes in.

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: Chrom

**Smartphone (please complete the following information):**
Any

**Additional context**
N/A

**Comment by Go1dExperience** [comment]
So in src/plugin-hooks/useRowSelect.js:227, we have this line:
` autoResetSelectedRows = true` for the useInstance function.
Also in the same file:
`
  useMountedLayoutEffect(() => {
    if (getAutoResetSelectedRows()) {
      dispatch({ type: actions.resetSelectedRows })
    }
  }, [dispatch, data])
`
Everytime 2 rows are added, it counts as data is changed, so the reset action is dispatched. Either setting autoResetSelectedRows to false, or remove data from dependency array work. @tannerlinsley  can you please provide your thought? I'm not too sure why they are this way, but maybe you can tell which change is more favorable.

**Comment by emdotem** [comment]
Your solution works pretty well, thank you very much and sorry for not having spot the FAQ earlier.
