### ISSUE TITLE
Why some react-table examples use div tags instead of table/thead/tbody/tr/th/td?

### ISSUE THREAD

**Issue by leodevbro** [TanStack/react-table#3685]
Hello, as I see, in `react-table` examples, some codesandbox examples use `table/thead/tbody/tr/th/td` tags like this sandbox:

https://react-table-v7.tanstack.com/docs/examples/basic

But some examples use just `div` tags:

https://react-table-v7.tanstack.com/docs/examples/column-resizing

Which approach is better if I want to build very responsive and very feature-rich/advanced table? And why?
I mentioned the word "responsive ", yeah, I know `react-table` (headless) does not do CSS design/responsive styles, it's a tabling engine, but I think the decision between these two (`div` or `table/thead/tbody/tr/th/td`) approaches will effect the CSS styling experience.

**Comment by benjamincharity** [comment]
It becomes useful when implementing both virtualized and resizable tables that must also be able to stretch to fill all available space.

Docs reference: 
- https://react-table.tanstack.com/docs/api/useBlockLayout
- https://react-table.tanstack.com/docs/api/useFlexLayout
- https://react-table.tanstack.com/docs/api/useAbsoluteLayout

**Comment by Devanshu-mile9** [comment]
will it be alright if i used div tag instead of table tags with react-table for a large data?
