### ISSUE TITLE
Selected rows always resetting when click on toggle sidebar

### ISSUE THREAD

**Issue by AjayShivanagol** [TanStack/react-table#3687]
Please find the code link https://codesandbox.io/s/funny-phoebe-ux3e5?file=/src/nestead-table/index.js

select any records and click and then click on the Toggle side bar the selected checkbox is getting reset.

Please help Thanks in Advance!

**Comment by rkulinski** [comment]
Hey! Please always send minimal reproduction example. It's very difficult to identify problems in a big chunk of a code. I think your problem might be that you unmount and mount table component every time you click Toggle side bar, hence clearing a state. You need to reafactor your code  IMO. In case you will encounter problems, please prepare minimal reproduction example.
