### ISSUE TITLE
Got 'Cannot set properties of undefined (setting 'indeterminate')' when using custom checkbox for IndeterminateCheckbox component

### ISSUE THREAD

**Issue by handhikadj** [TanStack/react-table#3700]
**Describe the bug (required)**
I raised this issue from [Discussions](https://github.com/TanStack/react-table/discussions/3679) to Bug because has yet to answered for a week.

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/nice-wave-86bbu?file=/src/App.js

**Steps To Reproduce (required)**

1. Go to https://codesandbox.io/s/nice-wave-86bbu?file=/src/App.js
2. you will see the error right away

**Expected behavior (Recommended)**
Can use the custom checkbox component

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: Mac Monterey
- Browser Chrome
- Version 98.0.4758.80 (Official Build) (arm64)

**Additional context**
N/A

**Comment by Go1dExperience** [comment]
I'm not sure what the value of **indeterminate** is, or how you want to handle it, but this is a rough example of how to use ref. You have to pass an actual ref down to `<IndeterminateCheckBox>` if you want to read it inside the component.
https://codesandbox.io/s/sleepy-silence-zhum1

**Comment by handhikadj** [comment]
thank you for the response. much appreciated. 
I think the sandbox is enough to sort this out.
