### ISSUE TITLE
Unable to use useGroupBy and useRowSelect together when there are subRows

### ISSUE THREAD

**Issue by Evadon-Nathan** [TanStack/react-table#3714]
When trying to use the grouping functionality (useGroupBy) with selection functionality (useRowSelect) and with data that has subRows (useExpanded), it crashes with the following error:

useRowSelect.js:157 Uncaught TypeError: Cannot read properties of undefined (reading 'isGrouped')

This is the probably the same issue as [Issue 2465](https://github.com/TanStack/react-table/issues/2465). But that one has been closed despite the problem still apparently being there.

I have created a Codesandbox from a fork of the Grouping example and added a hook that adds the selection column and data that has subRows:
[https://codesandbox.io/s/fervent-poincare-213pvc?file=/src/App.js](https://codesandbox.io/s/fervent-poincare-213pvc?file=/src/App.js)

1. Create a table that uses useGroupBy, useRowSelect and where the data has subRows
2. Click on a selection box
3. See error useRowSelect.js:157 Uncaught TypeError: Cannot read properties of undefined (reading 'isGrouped')

- OS: MacOs
- Browser: Chrome and Firefox
- react-table Version: 7.7.0

**Comment by andrii-chernienko-fb-rgare** [comment]
The same with v8. Here is an example of the problem

https://codesandbox.io/s/relaxed-pascal-ich1jv?file=/src/main.tsx
