### ISSUE TITLE
v.7.7.0 Pagination: setPageSize(-1) hides the last row

### ISSUE THREAD

**Issue by jukkahuuskonen** [TanStack/react-table#3740]
**Describe the bug (required)**
With Pagination when setting pagesize to (-1), to show all rows, it actually hides the last row from data.

**Provide an example via Codesandbox! (required)**
Here is a codesandbox copied from your example [react-table codesandbox](https://codesandbox.io/s/strange-neumann-hlhbxp?file=/src/App.js) to reproduce the issue.

Things I changed:
1. Added a useEffect to set pagesize to -1 on first load:
![image](https://user-images.githubusercontent.com/42405685/156165252-f62fb59d-38a8-4d49-a5bc-da117852e079.png)
2. changed table data size to 15 rows:
![image](https://user-images.githubusercontent.com/42405685/156165362-cc84b898-223d-46f7-b3b7-84359f79f025.png)

**Steps To Reproduce (required)**

1. Open sandbox, page size is automatically set to -1, should show all rows, but it already says it is hiding one row
![image](https://user-images.githubusercontent.com/42405685/156165589-f5e6adce-3c08-4a73-8d40-b76e364aa032.png)
2. Change pagination to show min 20 rows
3. See error: 1 missing row is shown
![image](https://user-images.githubusercontent.com/42405685/156204680-9a356f55-061d-4c40-add0-bb1b034543ce.png)

**Expected behavior (Recommended)**
setPageSize(-1) to show all rows.

**Desktop (please complete the following information):**

- OS: Win10
- Browser: Chrome

**Comment by jukkahuuskonen** [comment]
Anyone looking into this or is the v8 taking priority?

**Comment by tannerlinsley** [comment]
This is fixed in v8 :)

**Comment by borie88** [comment]
Seems to be broken again. As long as getPaginationRowModel() is being used, pageSize -1 will hide the last row of data for some reason. Either I'm using it wrong or something weird is happening.
https://codesandbox.io/p/sandbox/intelligent-dust-2kg9kk?file=%2Fsrc%2Fmain.tsx%3A107%2C3-107%2C36
