### ISSUE TITLE
VScode changing its theme when I'm changing the branch

### ISSUE THREAD

**Issue by alexander-vashchuk** [TanStack/react-table#3751]
When I'm changing the branch of this project, the top header of the editor changes the color
![image](https://user-images.githubusercontent.com/86713661/157267926-630d1dad-8956-4556-8f90-3ab7dc279b15.png)
Can someone tell me what does this pinky colors means, and how to implement this feature?

**Comment by Gummy47** [comment]
I'm not sure what your question is about, but color customizations like this are typically done with the **Peacock** extension in VSCode, and those customizations are stored as `settings.json` in a `.vscode` subfolder.

The color in itself doesn't mean anything, it's just the author of react-table who commited and pushed his `.vscode` settings file. Typically, those are `.gitignored` but it seems it's not the case here.

If you wish to get rid of those colors, just delete the `settings.json` file, but by doing so you risk encountering conflicts when pulling changes. If it's _really_ a problem for you, you'd be best forking the repo and removing this file completely for yourself.

**Comment by alexander-vashchuk** [comment]
The thing is, I do not have Peacock extension installed

And I'm just curious how to achieve such a result, and how this VS Code API works

**Comment by Gummy47** [comment]
The color customization is a feature built in VSCode.
Peacock is just a helper plugin to make it easier to customize. It is not required to change the colors and appearance of VSCode.

If you're interested in seeing all configurable VSCode settings, use the fuzzy finder (CTRL+P by default) and type ">settings" and select "Preferences : open user settings".

**Comment by alexander-vashchuk** [comment]
Thanks, finally makes sense 👍
