### ISSUE TITLE
Most of the examples in the documentation don't work

### ISSUE THREAD

**Issue by alexander-vashchuk** [TanStack/react-table#3752]
```bash
git clone https://github.com/TanStack/react-table
cd react-table/examples/basic
yarn && yarn dev
```
And then it crashes
![image](https://user-images.githubusercontent.com/86713661/157272297-bf8a3835-1d30-4ef3-9a9f-487aa1e3953a.png)

- Next.js examples are crashing
- create-react-app examples are crashing
- I've tried this example https://react-table.tanstack.com/docs/quick-start with react + vite + ts. It is also crashing, and typescript is throwing lots of errors.

Every project bundler is throwing some odd errors, so I can't tell some specific issue

This library only works on CodeSandbox

**Comment by geniusit** [comment]
I tried the same v8.0.0-alpha.a basic sample and can't make it work.


![image](https://user-images.githubusercontent.com/3659037/158082808-2e5ff83f-6d80-4815-83e1-d501df1b46ca.png)

Sample on codesanbbox don' work for me : 

![image](https://user-images.githubusercontent.com/3659037/158082846-6ec6e02d-70c5-46a9-ada3-1a54efe76dba.png)

**Comment by tannerlinsley** [comment]
All of the examples should now be working
