### ISSUE TITLE
React 18: Hydration error

### ISSUE THREAD

**Issue by johnmagbag1995** [TanStack/react-table#3782]
**Describe the bug (required)**
`cell.render('Cell')` is causing an hydration error on React 18.0

![image](https://user-images.githubusercontent.com/61783659/160679280-58a15308-bfb9-4ace-ad09-ed43bd905995.png)

**Comment by tannerlinsley** [comment]
React.18 is not currently supported in v7. Feel free to investigate and open a PR, but for now, efforts are being put into v8.
