### ISSUE TITLE
table.createDataColumn(): the cell `info.value` type is `unknown` but could be derived via generics

### ISSUE THREAD

**Issue by Obiwarn** [TanStack/react-table#3787]
From the examples folder:

The info value type below could be derived via generics (e.g. here `string`) but is `unknown`

```
    table.createDataColumn("firstName", {
        cell: (info) => info.value,  // <= type unknown
    //...
```

**Comment by tannerlinsley** [comment]
This should already be working so it looks like a bug.

Tanner Linsley
