### ISSUE TITLE
Union types issue with Column<T> generic

### ISSUE THREAD

**Issue by mateNemeth** [TanStack/react-table#3789]
Hi,

I have a project where one of the tables can receive multiple types of rows. I've created a discriminating union type for them, they have a lot of common props and some unique ones as well. But when I tried typing the columns array I've run into an issue. I usually do it like this:
```
const columns = useMemo<Column<Type>[]>(() => [...], []);
```

But in this case inside the `useMemo` when setting the Cell prop, the `row.original` isn't the union type anymore, but the first type of the union. For example:
```
export interface IBaseOption {
  commonValue: string;
}

export interface IOptionOne extends IBaseOption {
  type: "optionOne";
  x: string;
}

export interface IOptionTwo extends IBaseOption {
  type: "optionTwo";
  y: "string";
}

export type Options = IOptionOne | IOptionTwo;

....

const columns = useMemo<Column<Options>[]>(
    () => [
      {
        accessor: "commonValue",
        Cell: ({ row }) => {                    // the type for row.original here is IOptionOne instead of Options
          switch (row.original.type) {
            case "optionOne":
              return row.original.x;        // no error here
            case "optionTwo":             // Type '"optionTwo"' is not comparable to type '"optionOne"'
              return row.original.y;       // Property 'y' does not exist on type 'IOptionOne'
            default:
              return null;
          }
        }
      }
    ],
    []
  );
```
**CodeSandBox example:**
https://codesandbox.io/s/vibrant-poitras-2mgcy4

**Steps to reproduce the behavior:**
Pretty straightforward.

**Expected behavior:**
I would expect that `row.original` keeps the originally declared union type.

**Desktop (please complete the following information):**

- OS: any
- Browser any
- Version: 7.0.0 -

**Comment by tannerlinsley** [comment]
These types are community maintained and now that v8 is native typescript, this is even less of an issue. You'll need to file an issue in the community types repo.

**Comment by Falcowoski** [comment]
Hello!

I know it's been a while, but did you find a solution? I looked for a issue related to this in the community repository and did not find it.

@mateNemeth

**Comment by mateNemeth** [comment]
Hi @Falcowoski,
I just forced type assertion and created guards to catch errors:

`{
  Header: 'Column 1',
  accessor: 'id',
  Cell: ({row}) => {
    const data = row.original as MyUnionType;
    if (isTypeA(data)) {
      return 'it is A'
    } else if (isTypeB(data)) {
      return 'it is B'
    } else {
      ....
    }
  }
}`

**Comment by Falcowoski** [comment]
Perfect! Thank u.
