### ISSUE TITLE
8.0.0-alpha.14 tableCore.init Is Not a Function Error

### ISSUE THREAD

**Issue by brandon-schabel** [TanStack/react-table#3790]
**Describe the bug**
After installing @tanstack/react-table@8.0.0-alpha.14, I am getting the following error:
`error - TypeError: tableCore.init is not a function`

It occurs in both Create React App and Next

**Codesandbox**
I tried to use the provided sandbox but it said not available. So I created one based on React 17.0.2 with Create React App - TypeScript
https://codesandbox.io/s/youthful-margulis-7fcc97

**Steps To Reproduce**
- Copy the basic example - https://github.com/TanStack/react-table/blob/alpha/examples/basic/src/main.tsx
- Run the app and the error should show immediately

**Screenshots**
<img width="842" alt="Screen Shot 2022-04-01 at 4 10 44 PM" src="https://user-images.githubusercontent.com/18100375/161354286-2c1176e6-ab51-4857-b1ef-677471d82d88.png">

**Desktop (please complete the following information):**

- OS: [MacOS Big Sur 11.4]
- Browser [Edge]
- Version [99.0.1150.55 (Official build) (arm64)]

**Comment by brandon-schabel** [comment]
Resolved after updating to `8.0.0-alpha.16`.

**Comment by tannerlinsley** [comment]
A fix is deploying.

Tanner Linsley
