### ISSUE TITLE
v8alpha: createDataColumn() within createColumns() => many TS errors

### ISSUE THREAD

**Issue by Obiwarn** [TanStack/react-table#3796]
If I call createDataColumn() without using groups, I get TS errrors.

```
table.createColumns([
  table.createDataColumn(
  // ...
```

Error:
`
TS2322: Type 'ColumnDef<Overwrite<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>, { ...; }>>' is not assignable to type 'ColumnDef<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>>'.   Type 'ColumnDef<Overwrite<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>, { ...; }>>' is not assignable to type 'CoreColumnDef<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>>'.     Types of property 'columns' are incompatible.       Type 'ColumnDef<Overwrite<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>, { ...; }>>[] | undefined' is not assignable to type 'ColumnDef<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>>[] | undefined'.         Type 'ColumnDef<Overwrite<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>, { ...; }>>[]' is not assignable to type 'ColumnDef<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>>[]'.           Type 'ColumnDef<Overwrite<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>, { ...; }>>' is not assignable to type 'ColumnDef<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>>'.             Type 'ColumnDef<Overwrite<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>, { ...; }>>' is not assignable to type 'CoreColumnDef<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>>'.               Types of property 'columns' are incompatible.                 Type 'ColumnDef<Overwrite<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>, { ...; }>>[] | undefined' is not assignable to type 'ColumnDef<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>>[] | undefined'.                   Type 'ColumnDef<Overwrite<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>, { ...; }>>[]' is not assignable to type 'ColumnDef<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>>[]'.                     Type 'ColumnDef<Overwrite<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>, { ...; }>>' is not assignable to type 'ColumnDef<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>>'.                       Type 'ColumnDef<Overwrite<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>, { ...; }>>' is not assignable to type 'CoreColumnDef<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>>'.                         Types of property 'columns' are incompatible.                           Type 'ColumnDef<Overwrite<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>, { ...; }>>[] | undefined' is not assignable to type 'ColumnDef<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>>[] | undefined'.                             Type 'ColumnDef<Overwrite<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>, { ...; }>>[]' is not assignable to type 'ColumnDef<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>>[]'.                               Type 'ColumnDef<Overwrite<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>, { ...; }>>' is not assignable to type 'ColumnDef<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>>'.                                 Type 'ColumnDef<Overwrite<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>, { ...; }>>' is not assignable to type 'GroupingColumnDef<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>>'.                                   Types of property 'aggregatedCell' are incompatible.                                     Type 'Renderable<Overwrite<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>, { ...; }>, { ...; }> | undefined' is not assignable to type 'Renderable<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>, { ...; }> | undefined'.                                       Type '(props: { instance: TableInstance<Overwrite<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>, { ...; }>>; row: Row<...>; column: Column<...>; cell: Cell<...>; value: string; }) => ReactNode' is not assignable to type 'Renderable<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>, { ...; }> | undefined'.                                         Type '(props: { instance: TableInstance<Overwrite<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>, { ...; }>>; row: Row<...>; column: Column<...>; cell: Cell<...>; value: string; }) => ReactNode' is not assignable to type '(props: { instance: TableInstance<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>>; row: Row<...>; column: Column<...>; cell: Cell<...>; value: unknown; }) => ReactNode'.                                           Types of parameters 'props' and 'props' are incompatible.                                             Type '{ instance: TableInstance<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>>; row: Row<...>; column: Column<...>; cell: Cell<...>; value: unknown; }' is not assignable to type '{ instance: TableInstance<Overwrite<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>, { ...; }>>; row: Row<...>; column: Column<...>; cell: Cell<...>; value: string; }'.                                               Types of property 'instance' are incompatible.                                                 Type 'TableInstance<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>>' is not assignable to type 'TableInstance<Overwrite<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>, { ...; }>>'.                                                   Type 'TableInstance<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>>' is not assignable to type 'TableCore<Overwrite<Overwrite<Overwrite<Partial<DefaultGenerics>, { Render: <TProps extends {}>(Comp: Renderable<TProps>, props: TProps) => ReactNode; }>, { ...; }>, { ...; }>>'.                                                     Types of property 'options' are incompatib`

**Comment by tannerlinsley** [comment]
Try again with the latest alpha release.

**Comment by Obiwarn** [comment]
I am on alpha 19, isn't that the latest?

**Comment by promontis** [comment]
I think `8.0.0-alpha.20` has the same problem (a lot of TS errors) unfortunately. I'm using the following code...

```
  const defaultColumns = table.createColumns([
    table.createDataColumn("firstName", {
      cell: (info) => info.value,
      footer: (props) => props.column.id,
    }),
    table.createDataColumn((row) => row.lastName, {
      id: "lastName",
      cell: (info) => info.value,
      header: () => <span>Last Name</span>,
      footer: (props) => props.column.id,
    }),
  ]);
``` 

Or, is this maybe not the correct api 😅 ?

**Comment by tannerlinsley** [comment]
Code sandbox or paste the ts error?

Tanner Linsley

**Comment by promontis** [comment]
I'll create a sandbox tomorrow when I get home 🤗

**Comment by promontis** [comment]
Seems to work all fine now! See https://codesandbox.io/s/great-perlman-t2y324?file=/src/index.tsx
I updated to latest version of React and such as well.

**Comment by tannerlinsley** [comment]
Nice!

Tanner Linsley
