### ISSUE TITLE
useExpanded markdown has incorrect instance property listed

### ISSUE THREAD

**Issue by JohnZecobee** [TanStack/react-table#3797]
**Describe the bug (required)**
Small markdown issue

**Steps To Reproduce (required)**

1. Go to https://react-table.tanstack.com/docs/api/useExpanded#instance-properties
2. Look at `rows`

**Expected behavior (Recommended)**
Property should be `expandedRows` (`rows` is the list of all rows)

**Screenshots**
<img width="1130" alt="Screen Shot 2022-04-04 at 1 30 56 PM" src="https://user-images.githubusercontent.com/25017133/161599215-2b9f99ab-eb62-42d5-b642-3efa42f1c458.png">

**Comment by tannerlinsley** [comment]
Will fix in the next doc release!
