### ISSUE TITLE
Property 'setFilter' does not exist on type 'TableInstance<object>'.

### ISSUE THREAD

**Issue by maskedmage77** [TanStack/react-table#3800]
I am attempting to use setFilter in a typescript project and I am receiving the following error. This occurs after reinstalling all packages.
`Property 'setFilter' does not exist on type 'TableInstance<object>'.`

**Screenshots**
![image](https://user-images.githubusercontent.com/39139848/161874475-a32d5608-bfca-4233-aeac-49fced25bd60.png)

- Version 7.7.0
- Types Version 7.7.10

**Comment by lindapaiste** [comment]
The `setFilter` property is added by the `useFilters` plugin, so it’s not included in the base type declarations.

You will need to follow [these instructions](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-table#configuration-using-declaration-merging) to add TypeScript support for the `useFilters` plugin.

**Comment by tannerlinsley** [comment]
These are community types, so you'll need to submit an issue there. Luckily v8 is written in Typescript, so this won't be an issue going forward.
