### ISSUE TITLE
not able to use useRowSelect with server side pagination

### ISSUE THREAD

**Issue by AjayShivanagol** [TanStack/react-table#3817]
### Describe the bug

I have implemented server-side pagination. where I wanted to use the checkbox.
I have tried to use **useRowSelect**  but it's giving maximum depth reached an error.

please find the code link below.

https://codesandbox.io/s/determined-voice-b0n991?file=/src/PokemonTable.js

please uncomment the following code in the link so that the error is reproduced.
   ```
 // useRowSelect
    // (hooks) => {
    //   hooks.visibleColumns.push((columns) => [
    //     {
    //       id: "selection",
    //        Header: ({ getToggleAllPageRowsSelectedProps }) => (
    //         <div>
    //           <IndeterminateCheckbox {...getToggleAllPageRowsSelectedProps()} />
    //         </div>
    //       ),
    //       Cell: ({ row }) => (
    //         <div>
    //         <IndeterminateCheckbox {...row.getToggleRowSelectedProps()} />
    //         </div>
    //       )
    //     },
    //     ...columns
    //   ]);
    // }
```

### Your minimal, reproducible example

 https://codesandbox.io/s/determined-voice-b0n991?file=/src/PokemonTable.js

### Steps to reproduce

uncomment on the above-mentioned line. we will see the error. 

### Expected behavior

it should display a checkbox and select and unselect just to work

### Platform

chrome browser

### react-table version

7.7.0

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [x] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
This should work for you: https://codesandbox.io/s/withered-frog-u1om0u?file=/src/PokemonTable.js

**Comment by AjayShivanagol** [comment]
@tannerlinsley but with these changes server side pagination stopped working.
