### ISSUE TITLE
V8 rowSelection in TableState not updating

### ISSUE THREAD

**Issue by promontis** [TanStack/react-table#3832]
### Describe the bug

I would expect the `rowSelection` to be updated, but it never does. It remains `{}`

### Your minimal, reproducible example

https://codesandbox.io/s/compassionate-moon-qfog95

### Steps to reproduce

Select some rows

### Expected behavior

I would expect the `rowSelection` property of the TableState to update with the selected row ids.

### Platform

macOS, Chrome

### react-table version

8.0.0-alpha.26

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
If you comment out these lines, and reference the state by `instance.getState()` instead, it works fine

<img width="809" alt="image" src="https://user-images.githubusercontent.com/28243511/163698201-8710fcbc-6765-447a-a8e7-6da3da6409f8.png">

**Comment by nrayburn-tech** [comment]
Modified version here https://codesandbox.io/s/loving-napier-zgujem.

If you are using `onStateChange`, then I don't think you need to use `rowSelection` as a separate variable.  You can access the value from `state.rowSelection`.

Note, you need to pass `state` into the `instance.setOptions` call.  You aren't currently doing this, so your state is probably being reset to `prev`.
```js
instance.setOptions((prev) => ({
  ...prev,
  state,
  onStateChange: setState
});
```

If you really need `rowSelection` separately with the full controlled state, then I am not sure what the solution would be.

**Comment by tannerlinsley** [comment]
@promontis, You are attempting to both fully and partially control the state, which cannot be done. Either you control it fully or partially, but not both. Here is your example, but using a fully controlled approach: https://codesandbox.io/s/goofy-mountain-yot2ys?file=/src/main.tsx

**Comment by promontis** [comment]
It works! Thank you guys 🤗
