### ISSUE TITLE
[v8.0.0-alpha.31] Sorting and subsequent filtering results in "Warning: Cannot update a component (`App`) while rendering a different component"

### ISSUE THREAD

**Issue by balthz** [TanStack/react-table#3842]
### Describe the bug

The bug manifests in a slightly but I think legitimate variation of the [`examples/filters`](https://github.com/TanStack/react-table/tree/v8.0.0-alpha.31/examples/filters) sample code of `react/table` version `v8.0.0-alpha.31`.

 * The change I made is keep the state in the `<App/>` component and pass it to a new `<Tbl … />` component. 
 * To rule out this has to do with the global filter, I removed code related to the latter.
 * Complete code is in [this diff gist](https://gist.github.com/balthz/2b8ffecd3619a3b80a237e8087209895/revisions#diff-61ee70fcb1659759aa75fd34ebdeb68a2164aa59817e5be66419a100f15788dd).

### Your minimal, reproducible example

https://gist.github.com/balthz/2b8ffecd3619a3b80a237e8087209895/revisions#diff-61ee70fcb1659759aa75fd34ebdeb68a2164aa59817e5be66419a100f15788dd

### Steps to reproduce

1. Start the example using `npm run start`
2. Click on "Last Name" column to sort it. This will show: 

     <img width="967" alt="image" src="https://user-images.githubusercontent.com/17190858/163888216-3a275cd5-0d61-41a6-b9ac-9a4009ade409.png">

3. Click in he "Last Name" filter field and type e.g. the letter `a`. This shows

     <img width="1275" alt="image" src="https://user-images.githubusercontent.com/17190858/163888505-7ad399e0-73fd-4062-a544-b5d38845fb25.png">

### Expected behavior

I expect no error message to appear.

### How often does this bug happen?

Every time

### Platform

macOS, Safari (Version 15.4 (17613.1.17.1.6))

### react-table version

v8.0.0-alpha.31

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by balthz** [comment]
@tannerlinsley I can confirm that the error has gone in `v8.0.0.-alpha.58` but I'm now seeing

![image](https://user-images.githubusercontent.com/17190858/166290572-8c037c63-23bb-4028-a830-82d1828fc9ff.png)

These seems related to a recent change:

<img width="593" alt="image" src="https://user-images.githubusercontent.com/17190858/166290808-4dc4c19e-da85-4163-9087-d672ddb85d07.png">

Let me know in case you want a separate ticket for this.

**Comment by tannerlinsley** [comment]
Yes, can you please open a new issue with a Screenshots?

**Comment by balthz** [comment]
> Yes, can you please open a new issue with a Screenshots?

See https://github.com/TanStack/react-table/issues/3877
