### ISSUE TITLE
[v8.0.0-alpha.30] global filter not working

### ISSUE THREAD

**Issue by brunoti** [TanStack/react-table#3846]
### Describe the bug

Column filters are ok but global filters are not working.

### Your minimal, reproducible example

https://codesandbox.io/s/github/TanStack/react-table/tree/alpha/examples/filters

### Steps to reproduce

1. Copy a name from the first column
2. Paste on global filter input
3. It will bring no data

### Expected behavior

If you do the same step and paste on the column filter it works. That should be the same behavior on global filters.

### Screenshots or Videos

https://user-images.githubusercontent.com/6011421/164127485-adf04d10-d9b8-41be-a772-8bb64240b059.mov

### Platform

macOs

### react-table version

v8.0.0-alpha.30

### TypeScript version

latest

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by brunoti** [comment]
Also, the pagination doesn't change when filtered. It shows the same page size and allows navigation even when empty.

**Comment by tannerlinsley** [comment]
Pagination reset is also fixed 👍
