### ISSUE TITLE
[v8-alpha-47] globalFilter not working

### ISSUE THREAD

**Issue by Paul6552** [TanStack/react-table#3856]
### Describe the bug

Thanks to [brunoti](https://github.com/brunoti) for the codesandbox.

GlobalFilter not working

### Your minimal, reproducible example

https://codesandbox.io/s/github/TanStack/react-table/tree/alpha/examples/filters

### Steps to reproduce

Try to enter something in the "search all columns" textfield. Nothing changes.

### Expected behavior

Should filter

### How often does this bug happen?

Every time

### Platform

chrome latest version
node 16
linux

### react-table version

alpha-47

### TypeScript version

4.6.3

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by Paul6552** [comment]
Yes, the "test" filter is only for the column "firstname" and for testing, but global filter should still work.

**Comment by KevinVandy** [comment]
> Sry, I misunderstood the function test. Thanks @KevinVandy 

Yeah, that code probably needs to be removed from the example since it's confusing. It was just used to verify that custom global filter fns could be set.
