### ISSUE TITLE
TypeError: props.getToggleAllRowsSelectedProps is not a function

### ISSUE THREAD

**Issue by TimmyGOGO** [TanStack/react-table#3858]
### Describe the bug

**Problem:**
Selection props for react-table don't work.

**Details:**
I'm using create-react-app.
I tried to implement a rows selection for my react-table component. I added a special column with checkbox, but keep getting strange error: "TypeError: props.getToggleAllRowsSelectedProps is not a function". Component for first column is really simple but despite that I couldn't find any info on my problem on stackoverflow, so I decided to report it here.

**Column element:**
`{
        accessor: 'selection',
        Header: props => {
          console.log('TableSelection: Header: ', { props });
          return (
            <div>
              <input type="checkbox" {...props.getToggleAllRowsSelectedProps()} />
            </div>
          );
        },
        Cell: ({ row }) => {
          console.log('TableSelection: Cell: ', { row });
          return (
            <div>
              <input type="checkbox" /* {...row.getToggleRowSelectedProps()} */ />
            </div>
          );
        },`

Maybe I do something wrong, so could you provide me with a link with explanations in this case? 

 

### Your minimal, reproducible example

no

### Steps to reproduce

Just add column with input checkbox and pass {...getToggleAllRowsSelectedProps()} to it.

### Expected behavior

Everything works as it works in the example: 
https://react-table.tanstack.com/docs/examples/row-selection-and-pagination

### How often does this bug happen?

Every time

### Screenshots or Videos

**Error:**
![Inked165192550-47718f4f-f766-4fe7-b535-c0e205fefae4_LI](https://user-images.githubusercontent.com/11355318/165262166-cd903bc0-67e8-4831-b16a-490e7fd440d4.jpg)

**Even console.log gives strange output as though there is no selection props at all:**
![image](https://user-images.githubusercontent.com/11355318/165192678-452f445f-85a7-4860-9092-00d28daa1ada.png)

### Platform

Windows 10

### react-table version

7.0.4

### TypeScript version

3.9.7

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
Are you including the useRowSelection hook?

**Comment by TimmyGOGO** [comment]
> Are you including the useRowSelection hook?

I added but to no avail:
![problem](https://user-images.githubusercontent.com/11355318/165590903-96b9495d-be29-42c7-b6cc-324f6a1c07f1.jpg)

And still getting this error:
![problem2](https://user-images.githubusercontent.com/11355318/165591150-13b67761-e7bf-4e34-9089-67fecc7e5f2d.jpg)

**Comment by tannerlinsley** [comment]
The `getToggleAllRowsSelectedProps` method you are looking for is on the instance, eg. `instance. getToggleAllRowsSelectedProps`

**Comment by TimmyGOGO** [comment]
> The `getToggleAllRowsSelectedProps` method you are looking for is on the instance, eg. `instance. getToggleAllRowsSelectedProps`

In a theoretical aspect (like it was described here: https://react-table.tanstack.com/docs/api/useRowSelect) I understand that there should be a react-table instance, but in practical way I don't understand what should I do. In the example: https://codesandbox.io/s/github/tannerlinsley/react-table/tree/v7/examples/row-selection
we don't work with a created instance of a react-table, we are implementing Table component by using useTable hook. So, in my project I'm also implementing Table component with useTable hook. What do I miss? Could you give more explanation?
