### ISSUE TITLE
sortType: "datetime" doesn't work

### ISSUE THREAD

**Issue by kevbarns** [TanStack/react-table#3860]
### Describe the bug

When adding `sortType: "datetime"` to a datetime field (initial data comes from mongodb, formatted in the accessor using dayjs), the sorting crashes

### Your minimal, reproducible example

https://codesandbox.io/s/hopeful-snowflake-m7985k

### Steps to reproduce

1. Click on the date header column
2. crash happens

### Expected behavior

Should filter the column accordingly

### How often does this bug happen?

Every time

### Screenshots or Videos

![Capture d’écran 2022-04-26 à 19 24 52](https://user-images.githubusercontent.com/22106329/165358043-5138dec2-51f1-41b0-8dbc-234c8f57ce2e.png)

### Platform

Codesandbox

### react-table version

7.7.0

### TypeScript version

NA

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
It must be a date object, not a string

**Comment by kevbarns** [comment]
Thanks @tannerlinsley for the light ! 

One (last) question : 

How can I, at the same time, return a primitive to the accessor and a date object to the sorting plugin through the _sortType: "datetime"_

**Comment by tannerlinsley** [comment]
The accessed value is what is passed to the sorting interface.

**Comment by kevbarns** [comment]
yes that was my issue, I had to dig into the object return by each rows. Thank yo 🙏
