### ISSUE TITLE
Filter resets column sorting

### ISSUE THREAD

**Issue by Obiwarn** [TanStack/react-table#3866]
### Describe the bug

v8: changing a column filter value resets column sorting

### Your minimal, reproducible example

https://codesandbox.io/s/filter-and-sort-pkdr7m?file=/src/main.tsx

### Steps to reproduce

1. code: merge the Filter and Sorting examples

2. sort a column
3. enter some filter
4. sorting is reset

### Expected behavior

Keep sorting, like in the v7 kitchen sink example: https://react-table.tanstack.com/docs/examples/kitchen-sink

### How often does this bug happen?

Every time

### Platform

web

### react-table version

    "@tanstack/react-table": "8.0.0-alpha.56"

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
Fixed!
