### ISSUE TITLE
[v8.0.0-alpha.58] Can’t perform a React state update

### ISSUE THREAD

**Issue by balthz** [TanStack/react-table#3877]
### Describe the bug

I’m seeing

![image](https://user-images.githubusercontent.com/17190858/166290572-8c037c63-23bb-4028-a830-82d1828fc9ff.png) 

<img width="593" alt="image" src="https://user-images.githubusercontent.com/17190858/166290808-4dc4c19e-da85-4163-9087-d672ddb85d07.png">

on `v8.0.0-alpha.58`. 

### Your minimal, reproducible example

https://user-images.githubusercontent.com/17190858/166290808-4dc4c19e-da85-4163-9087-d672ddb85d07.png

### Steps to reproduce

I didn’t manage to reproduce this in e.g. https://github.com/TanStack/react-table/blob/v8.0.0-alpha.58/examples/filters/src/main.tsx but I think that's expected because Vite, according to its [docs](https://vitejs.dev/guide/features.html#typescript), doesn't type check:

> Vite only performs transpilation on `.ts` files and does **NOT** perform type checking.

### Expected behavior

No such React warning should show. 

### How often does this bug happen?

Every time

### Platform

Safari and macOS

### react-table version

V8.0.0-alpha.58

### TypeScript version

4

### Additional context

I don’t have a reproducible example but am filing this per discussion from https://github.com/TanStack/react-table/issues/3842#issuecomment-1115404483. Happy to look into coming up with an example (doing so it would be easier if the examples in the code would run the type checker I think). 

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
With the latest changes, this might be alleviated. Going to close until we can get a new issue with a codesandbox example
