### ISSUE TITLE
[8.0.0-alpha.55] Error "TS2322: Type 'number' is not assignable to type 'Timeout'." in core.ts

### ISSUE THREAD

**Issue by balthz** [TanStack/react-table#3878]
### Describe the bug

Has anybody hit this error?

Running `8.0.0-alpha.58` results in

```
ERROR in <REMOVED>/node_modules/@tanstack/table-core/src/core.ts
274:8-21
[tsl] ERROR in <REMOVED>/node_modules/@tanstack/table-core/src/core.ts(137,9)
      TS2322: Type 'number' is not assignable to type 'Timeout'.
```

https://github.com/TanStack/react-table/blob/v8.0.0-alpha.58/packages/table-core/src/core.ts#L137

Potentially related: https://github.com/Microsoft/TypeScript/issues/30128#issuecomment-807394387

### Your minimal, reproducible example

Happy to submit if it helps further let me know 

### Steps to reproduce

I can't reproduce this in e.g. https://github.com/TanStack/react-table/blob/v8.0.0-alpha.58/examples/filters/src/main.tsx but I think that's expected because Vite, according to its [docs](https://vitejs.dev/guide/features.html#typescript), doesn't type check:

> Vite only performs transpilation on `.ts` files and does **NOT** perform type checking.

According to https://stackoverflow.com/questions/45802988/typescript-use-correct-version-of-settimeout-node-vs-window, specifying the type as `ReturnType<typeof setTimeout>` in `core.ts` might help or `import { setTimeout } from 'timers';`. @tannerlinsley Do you think one of these options is worth a try? If so, let me know and I'll make a PR to change `core.ts` accordingly.

### Expected behavior

No compilation error 

### How often does this bug happen?

Every time

### Platform

MacOS Safari

### react-table version

V8.0.0-alpha.58

### TypeScript version

4

### Additional context

This is from discussion https://github.com/TanStack/react-table/discussions/3868. 

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
This type has been fixed. Huzzah!

**Comment by balthz** [comment]
Awesome, thank you so much!
