### ISSUE TITLE
[v8.0.0-alpha.58] Can’t infer the props type of PropGetter functions for getHeaderProps, getResizerProps, getCellProps and getFooterProps

### ISSUE THREAD

**Issue by talatkuyuk** [TanStack/react-table#3881]
### Describe the bug

I am trying to implement the column resizing example.

I get the typescript type inference error: Parameter 'props' implicitly has an 'any' type.  ts(7006)

### Your minimal, reproducible example

none

### Steps to reproduce

I get the typescript type inference error: Parameter 'props' implicitly has an 'any' type.  ts(7006)

### Expected behavior

I expect to not receive the typescript error

### How often does this bug happen?

Every time

### Screenshots or Videos

![the screen that shows the typescript error](https://user-images.githubusercontent.com/30029208/166495562-b14bbf2a-c1ce-45a3-a02b-d7ce281cf76f.jpeg)

### Platform

macos, macbook pro, vscode, chrome

### react-table version

v8.0.0-alpha.58

### TypeScript version

v.4.6.3

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by talatkuyuk** [comment]
All the PropGetter functions gone :) as of version 8.0.0-alpha59. **We can close the issue.** 

**but ....**

I am trying to implement column-reordering with the drag-drop the column-header at the same time with resizing functionality. The problem is that if you add a draggable property into the column header (I mean `th` in the `thead` ), it conflicts with the resizing action. When you starts the resizing action without release the mouse down yet, if the mouse pointer moves a little bit outside of the column header's border, the drag action takes over the mouse behavior and starts the drag the column header unintentionally stopping the resizing action which is I don't want.

I have to maintain a state if any of columns is resizing, so as that I can disable the draggable property. How I can get the information about any of columns is resizing at the moment?

```ts
      <Table style={{ width: instance.getTotalSize() }} ref={tableRef}>
        <thead>
          {instance.getHeaderGroups().map((headerGroup) => (
            <tr key={headerGroup.id}>
              {headerGroup.headers.map((header) => (
                <th
                  draggable.  <------ here I added draggable
                  key={header.id}
                  colSpan={header.colSpan}
                  style={{ width: header.getSize() }}
                >
                  {header.isPlaceholder ? null : header.renderHeader()}
                  <div
                    {...{
                      onMouseDown: header.getResizeHandler(),
                      onTouchStart: header.getResizeHandler(),
                      className: `resizer ${
                        header.column.getIsResizing() ? "isResizing" : ""
                      }`,
                    }}
                  />
                </th>
              ))}
            </tr>
          ))}
        </thead>
        <tbody>
           // rest of the table is omitted.
```

**Comment by tannerlinsley** [comment]
Instance.getState().columnSizingInfo I believe holds that state.

**Comment by talatkuyuk** [comment]
Thanks..

`draggable={ !instance.getState().columnSizingInfo.isResizingColumn}` is helped me. This worked.

Then, I realized that,

`draggable={!header.column.getIsResizing()}` also worked. But I use above snippet for consistency.

Thanks again.
