### ISSUE TITLE
Update npmjs v7 to include support for React 18

### ISSUE THREAD

**Issue by NebraskaCoder** [TanStack/react-table#3897]
### Describe the bug

Recently, you added support for React 18 in #3847 and #3873

Can you update https://www.npmjs.com/package/react-table so it includes it in v7 or tell a better way to get React-Tables using npm? I know about the new repo for @tanstack/react-table but that is alpha right now.

### Your minimal, reproducible example

https://www.npmjs.com/package/react-table

### Steps to reproduce

Go to npmjs.com

### Expected behavior

A version that supports React 18

### Platform

NPM

### react-table version

N/A

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by IVIyg0t** [comment]
+1

**Comment by tannerlinsley** [comment]
Released!
