### ISSUE TITLE
v.8 The pagination.pageIndex becomes 0 zero unintentionally in server side pagination controlled

### ISSUE THREAD

**Issue by talatkuyuk** [TanStack/react-table#3900]
### Describe the bug

I am trying to implement a server side pagination with react-table v.8.

I describe the problem in the discussion: https://github.com/TanStack/react-table/discussions/3898

The main problem is that the pagination state (only pagination.pageIndex) becomes zero in a couple of milliseconds after clicking the pagination buttons (next, previous or last page buttons).

### Your minimal, reproducible example

none

### Steps to reproduce

There is an example with v.7 
https://codesandbox.io/s/github/tannerlinsley/react-table/tree/v7/examples/pagination-controlled

After creating the discussion, I implemented the same example pagination-controlled with v.8 without using RTK Query. The problem is the same. The pagination state (only pagination.pageIndex) becomes zero in a couple of milliseconds after clicking the pagination buttons (next, previous or last page buttons) 

### Expected behavior

I expect the pagination.pageIndex not to become zero unintentionally.

### How often does this bug happen?

Every time

### Platform

macOs, macbookpro 2019, chrome

### react-table version

8.0.0-alpha.63

### TypeScript version

4.6.3

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
Set options.autoResetPageIndex to false. In a future release, I’ll make options.manualSorting default that to false.

Tanner Linsley

**Comment by talatkuyuk** [comment]
I didn't know that. Thank you. (not knowing that spent my whole weekend)

My another question: What is the reason of the option `getPaginationRowModel`? 

Should I use the option for manualPagination: `getPaginationRowModel: getPaginationRowModel(),` ?

What is pipeline ? I see that in the comment line 123 at the pagination example (https://github.com/TanStack/react-table/blob/34f616b61a3c901d76fb4315468b7d9eec227927/examples/react/pagination/src/main.tsx)

**Comment by tannerlinsley** [comment]
manualPagination bypasses the pagination row model option. You’ll paginate the rows on your own (slice them down to the right page size)

Tanner Linsley

**Comment by diego-lipinski-de-castro** [comment]
Seems to be happening in vue 3.4.0 table 8.20.5
