### ISSUE TITLE
v67: `column.cell()` called three times on render, why?

### ISSUE THREAD

**Issue by Obiwarn** [TanStack/react-table#3901]
### Describe the bug

I am not sure with this, but during my search for performance bottlenecks, I found this:

I added a `console.log()` to the first cell render function in the filter example. 

### Your minimal, reproducible example

https://codesandbox.io/s/exciting-snow-8xfj5c?file=/src/main.tsx

### Steps to reproduce

Clear the console log.

Enter one letter in the first search field.

The `"Why am i called for every visible row three times?"` log is called for all 10 visible rows three times. 

Isn't that too much?

### Expected behavior

only called 10 times.

### Platform

x

### react-table version

x

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
I'm shipping a fix for this right this second. There was some funkiness going on with the auto-reset functionality for pageIndex and expanded that was causing some unwanted renders. Update your example in a few minutes and you should be good :)
