### ISSUE TITLE
v73: broken group column resizing

### ISSUE THREAD

**Issue by Obiwarn** [TanStack/react-table#3914]
### Describe the bug

v73 is on fire! so fast!

little bug in the column-sizing example:

resize a group column (e.g. "Name") => resize handler is too fast 

### Your minimal, reproducible example

https://codesandbox.io/s/great-cookies-qw9o1k

### Steps to reproduce

x

### Expected behavior

resize as in https://react-table.tanstack.com/docs/examples/column-resizing

### Platform

x

### react-table version

    "@tanstack/react-table": "8.0.0-alpha.73"

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by talatkuyuk** [comment]
Yes, you are right. I suppose when the mouse moves only 1px on group column, that 1px is added to all the sub column width at the same time. That is why the second group has more sub columns and moves faster than the first group column.
