### ISSUE TITLE
Uncaught Error: Hydration failed on Next12 w/React18 after adding react-table 8

### ISSUE THREAD

**Issue by softmarshmallow** [TanStack/react-table#3918]
### Describe the bug

Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.

https://nextjs.org/docs/messages/react-hydration-error

https://github.com/vercel/next.js/discussions/35773

<img width="983" alt="Screen Shot 2022-05-15 at 8 15 52 AM" src="https://user-images.githubusercontent.com/16307013/168450995-27aba5b0-faa1-4d2c-b116-d1f3af420705.png">

### Your minimal, reproducible example

.

### Steps to reproduce

1. `npx create-next-app --typescript`
2. `yarn add @tanstack/react-table@alpha`
3. import react-table

### Expected behavior

.

### Platform

- react-table: ^8.0.0-alpha.76
-    "next": "^12.1.4",
    "react": "^18.1.0",
    "react-dom": "^18.1.0"

### react-table version

8.0.0-alpha.76

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
Can we get a codesandbox?
