### ISSUE TITLE
Need to filter a column with boolean values

### ISSUE THREAD

**Issue by talatkuyuk** [TanStack/react-table#3930]
### Describe the bug

That is not a bug. But, in my use case, **one of the data column has boolean values** which the table's RowType consists. When I try to implement **column filtering**, I realize that there is no check for filtering the boolean values in the filter feature.  

In my opinion below code snippet in `getAutoFilterFn` in `/Filters.ts` may satisfy the issue. If you agree I can create a PR or you decide. 

```typescript
if (typeof value === 'boolean') {
    return filterFns.equals
}
```

Thank you.

### Your minimal, reproducible example

none

### Steps to reproduce

none

### Expected behavior

I expected the column with boolean values can be filtered as well.

### Platform

macos, macbook pro, chrome

### react-table version

v8.0.0-alpha.82

### TypeScript version

v.4.6.3

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
I think this would be a great addition. Feel free to open a PR :)
